// Package pysource provides the contAIned Python runtime source tree as an
// in-memory fs.FS so the Go binary can supply it as the Docker build context
// without any PyPI dependency.
//
// The source is generated by gen/main.go into source_gen.go. To regenerate
// after changing the Python source:
//
//	go generate contained.dev/cli/internal/pysource
package pysource

//go:generate go run gen/main.go

import "io/fs"

// Source is the embedded Python runtime source tree (pyproject.toml + src/).
var Source fs.FS = sourceFS
