"""
Templates for files generated by `contAIned init`.
All generated content lives here so the init logic stays clean.
"""

# NOTE: .claude/settings.json is NOT written by contained init.
# All hook registration, sandbox rules, permissions, and statusLine are owned
# exclusively by /etc/claude-code/managed-settings.json, baked into the Docker
# image.  Claude Code merges hooks from all settings levels — any .claude/
# settings.json with a "hooks" key would cause every hook to fire twice.
# contained init retires any existing .claude/settings.json by renaming it
# to .claude/settings.json.bak.<timestamp>.

POLICY_MANIFEST = """\
# contAIned policy manifest
#
# Three sections:
#   1. runtime — Docker container resource settings.
#   2. agent   — model selection passed to the claude CLI.
#   3. policy  — all governance settings read by the hook scripts,
#                including build-time provenance (sigstore).
#
# Action values accepted by policy settings:
#   block    — deny the operation outright; agent receives a clear reason
#   allow    — permit unconditionally
#   escalate — pass through to the SDK's canUseTool callback for operator approval
#
# Note: writes to .contAIned/ are always denied regardless of policy settings —
# control-plane protection is hardcoded and not configurable.

# ── Runtime ───────────────────────────────────────────────────────────────────
# Docker resource limits. Set by `contAIned init`. Require container restart to apply.
runtime:
  docker:
    image: contained:latest
    memory: 2g
    cpus: 2
    network: contAIned-net
    agent_config_volume: contAIned-agent-config
  # Work unit payloads are POSTed to mainlined.url at git push time.
  # MAINLINED_API_KEY is injected as an environment variable (not stored here).
  mainlined:
    url: ""   # e.g. https://mainlined.example.com

# ── Agent ─────────────────────────────────────────────────────────────────────
agent:
  # Model passed via --model to the claude CLI. Leave blank to use claude's default.
  model: claude-sonnet-4-6
  budget_tokens: 1024

policy:

  # ── Sigstore provenance ──────────────────────────────────────────────────────
  # When enabled, the Docker image is signed with Sigstore (cosign) during
  # `contAIned init`.  Provenance is stored in .contAIned/provenance.yaml and
  # verified on each session start.  Requires cosign to be installed.
  # Provenance is also stamped into every task closure in tracer.db, binding
  # each task to the exact signed image that enforced its policy.
  sigstore:
    enabled: true
    rekor_url: https://rekor.sigstore.dev
    fulcio_url: https://fulcio.sigstore.dev

  # ── Secret-file protection ──────────────────────────────────────────────────
  # rules — evaluated in order; first matching pattern wins.
  #   action: allow — permit unconditionally (use for safe variants like .env.example)
  #   action: block — deny the operation; agent receives the reason string
  # List allow rules before block rules so safe variants are exempted first.
  # Patterns are compiled with re.IGNORECASE.
  secrets:
    rules:
      - name: safe-variants
        patterns: ['\\.(example|sample|template)']
        action: allow

      - name: dotenv
        patterns: ['(^|[/\\\\])\\.env(\\.[^/\\\\]+)?$']
        reason: "Secret files (credentials, keys, .env) may not be accessed."
        action: block

      - name: keys
        patterns: ['\\.(pem|key|p12|pfx|jks|keystore)$']
        reason: "Secret files (credentials, keys, .env) may not be accessed."
        action: block

      - name: ssh-keys
        patterns: ['(^|[/\\\\])id_(rsa|dsa|ecdsa|ed25519)$']
        reason: "Secret files (credentials, keys, .env) may not be accessed."
        action: block

      - name: credential-files
        patterns: ['(^|[/\\\\])(credentials|secrets|service_account)\\.(json|yaml|yml)$']
        reason: "Secret files (credentials, keys, .env) may not be accessed."
        action: block

      - name: secret-extension
        patterns: ['\\.(secret|secrets)$']
        reason: "Secret files (credentials, keys, .env) may not be accessed."
        action: block

      # add project-specific rules here, e.g.:
      # - name: vault-token
      #   patterns: ['(^|[/\\])vault-token(\\..*)?$']
      #   reason: "Vault tokens may not be accessed."
      #   action: block

  # ── Bash command restrictions ────────────────────────────────────────────────
  # rules — evaluated in order; first matching pattern wins.
  #   action: allow    — auto-approve without prompting the operator
  #   action: block    — deny outright; agent receives the reason string
  #   action: escalate — surface operator approval prompt; logged as exception
  # List allow rules before block rules so safe commands are exempted first.
  bash:
    rules:
      - name: safe-git-reads
        patterns:
          - '^git\\s+status\\b'
          - '^git\\s+log\\b'
          - '^git\\s+diff\\b'
          - '^git\\s+show\\b'
          - '^git\\s+branch\\b'
          - '^git\\s+stash\\s+list\\b'
          - '^git\\s+remote\\b'
        action: allow

      - name: safe-read-only
        patterns: ['^ls\\b', '^pwd\\b', '^echo\\s', '^which\\s', '^grep\\b', '^rg\\b', '^find\\b', '^cat\\b', '^wc\\b']
        action: allow

      - name: destructive
        patterns: ['^rm\\s', '.*\\brm\\s+-rf\\b.*']
        reason: "Destructive file deletion is not permitted."
        action: block

      - name: privilege_escalation
        patterns: ['^sudo\\s']
        reason: "Privilege escalation is not permitted."
        action: block

      - name: network_exfiltration
        patterns: ['^(curl|wget|nc|ncat)\\s']
        reason: "Outbound network calls from Bash are not permitted."
        action: block

      - name: package_publish
        patterns: ['^(npm\\s+publish|pip\\s+upload|twine\\s+upload)\\b']
        reason: "Package publishing requires explicit operator approval."
        action: block

  # ── Network policy ────────────────────────────────────────────────────────────
  # Controls outbound network access for both Claude Code tools and subprocesses.
  #
  # allowed_domains — domains that are silently permitted:
  #   - WebFetch / WebSearch: requests to these domains are auto-approved.
  #     Requests to any other domain surface an operator confirmation prompt and
  #     are logged as exceptions.
  #   - Bash subprocesses: HTTP traffic is filtered by the Claude Code sandbox;
  #     requests to non-allowed domains are blocked.
  #
  # api.anthropic.com must remain in allowed_domains — the agent cannot function
  # without it.  Add project-specific domains (package registries, APIs) as needed.
  network:
    enabled: false
    allowed_domains:
      - api.anthropic.com    # required — Anthropic API
      - code.claude.com      # Claude Code telemetry / auth
      - docs.anthropic.com   # documentation lookups

  # ── Audit logging ─────────────────────────────────────────────────────────────
  # Always enabled — cannot be disabled.
  audit:
    enabled: true
    jsonl_export: false  # set true to also write .contAIned/audit/pipeline.jsonl

  # ── QA gate (stop hook) ───────────────────────────────────────────────────────
  # checks — list of commands to run when the agent signals it is done.
  # Each entry is either a bare exec-form array or a named object:
  #
  #   - ["ruff", "check", "."]                    # bare — name inferred from command[0]
  #   - name: tests
  #     command: ["pytest", "tests/", "-x", "-q"]
  #     when_changed: ["*.py"]                    # skip if no .py files were touched
  #
  # If checks is empty, QA passes trivially.
  # Commands run with shell=False; use exec-form arrays, not shell strings.
  qa:
    checks:
      - name: lint
        command: ["ruff", "check", "."]
        when_changed: ["*.py"]

      - name: format
        command: ["ruff", "format", "--check", "."]
        when_changed: ["*.py"]

      - name: types
        command: ["pyright"]
        when_changed: ["*.py"]

      - name: tests
        command: ["python", "-m", "pytest", "tests/", "-x", "--tb=short", "-q"]
        when_changed: ["*.py"]

      - name: coverage
        command: ["python", "-m", "pytest", "tests/", "--cov", "--cov-report=term-missing", "--cov-fail-under=80", "-q"]
        when_changed: ["*.py"]

  # ── MCP server approvals ──────────────────────────────────────────────────────
  # List of approved MCP server names.  Each entry generates an allow rule for
  # all tools from that server (mcp__<server>__*) in managed-settings.json.
  # Only servers listed here can be added when allowManagedMcpServersOnly is set.
  mcp:
    approved_servers: []   # e.g. [github, puppeteer]

  # ── Skill approvals ───────────────────────────────────────────────────────────
  # Explicit allowlist of skill names.  Each entry generates a Skill(<name>)
  # allow rule in managed-settings.json.  Unlisted skills surface an operator
  # confirmation prompt and are logged as exceptions.
  skills:
    approved_skills: []    # e.g. [commit, review-pr]

  # ── m<AI>nlined policy coordination ──────────────────────────────────────────
  # When url is set, `contAIned init` pulls the resolved policy from m<AI>nlined
  # and bakes it into this manifest.  policy_ref and policy_version are written
  # by `policy pull` and must not be edited manually — they are cargo-carried
  # into invocation_hash so every proof is bound to a specific central policy
  # version.  Leave url empty to operate fully offline with local policy only.
  mainlined:
    url: ""              # e.g. https://mainlined.example.com
    policy_name: ""      # human-readable policy identity used in m<AI>nlined
    policy_ref: ""       # written by `policy pull`; SHA-256 of the policy at pull time
    policy_version: ""   # written by `policy pull`; semantic version from m<AI>nlined

# ── Sandbox ───────────────────────────────────────────────────────────────────
# Claude Code's built-in OS-level sandbox (Seatbelt on macOS, bubblewrap on
# Linux).  Complements contAIned's PreToolUse hooks: the sandbox blocks subprocess
# writes (shell scripts, Python files run via Bash, build tools, etc.) while
# contAIned hooks block Claude's own Write/Edit SDK tool calls.  Both layers are
# needed — neither alone is sufficient.
#
# This section is read by `contAIned init` and written into .claude/settings.json.
# Changes here take effect after re-running `contAIned init` (or editing
# .claude/settings.json directly).
sandbox:
  enabled: true
  filesystem:
    denyWrite:
      - .contAIned   # protect the control-plane directory from subprocess writes
"""

POLICY_LOADER_HOOK = '''\
#!/usr/bin/env python3
"""Shared policy loader for contAIned hooks.

Reads the policy: section from /etc/contained/manifest.yaml (baked into the
container image by contAIned init) and merges it with structural defaults so
that every key is always present.  The manifest is the sole source of rule
data — if it cannot be read, hooks receive empty pattern lists and apply no
secret-file checks.

Manifest location:
  /etc/contained/manifest.yaml  — baked into the image by contAIned init

Action values: "block" | "allow"
  block    — deny the operation; hook exits 2 with a reason on stderr
  allow    — permit unconditionally
"""
from pathlib import Path

_DEFAULTS = {
    "secrets": {
        "rules": [],
    },
    "bash": {
        "rules": [],
    },
    "audit": {
        "enabled": True,
        "jsonl_export": False,
    },
    "qa": {
        "checks": [],
    },
    "network": {
        "enabled":        False,
        "allowed_domains": [
            "api.anthropic.com",
            "code.claude.com",
            "docs.anthropic.com",
        ],
    },
    "mcp": {
        "approved_servers": [],
    },
    "skills": {
        "approved_skills": [],
    },
}


def _deep_merge(base, override):
    """Recursively merge *override* into *base*, returning a new dict."""
    result = dict(base)
    for key, val in override.items():
        if isinstance(val, dict) and isinstance(result.get(key), dict):
            result[key] = _deep_merge(result[key], val)
        else:
            result[key] = val
    return result


def _compile_patterns(policy):
    """Compile all manifest pattern strings into regex objects in-place.

    Populates:
      policy["secrets"]["_compiled_rules"] — list[(action, [re.Pattern], reason)]
      policy["bash"]["_compiled_rules"]    — list[(action, [re.Pattern], reason)]

    Called once per load_policy() invocation.  All rule data comes
    exclusively from the manifest; there are no hardcoded built-ins.
    First-match-wins: list allow rules before block rules in the manifest.
    """
    import re as _re

    def _compile_rules(rules, flags=0):
        return [
            (
                rule["action"],
                [_re.compile(p, flags) for p in rule.get("patterns", [])],
                rule.get("reason", ""),
            )
            for rule in rules
        ]

    policy["secrets"]["_compiled_rules"] = _compile_rules(
        policy["secrets"].get("rules", []), _re.IGNORECASE
    )
    policy["bash"]["_compiled_rules"] = _compile_rules(
        policy["bash"].get("rules", [])
    )


def load_policy(cwd="."):
    """Return the fully-merged policy dict with all patterns pre-compiled.

    Always succeeds: if the manifest is unreadable the structural defaults
    are returned (empty pattern lists — no checks applied).
    """
    try:
        import yaml
        manifest_path = Path("/etc/contained/manifest.yaml")
        with manifest_path.open() as fh:
            manifest = yaml.safe_load(fh) or {}
        policy = _deep_merge(_DEFAULTS, manifest.get("policy", {}))
    except Exception:
        policy = dict(_DEFAULTS)
    _compile_patterns(policy)
    return policy


'''

RESTRICT_WRITES_HOOK = '''\
#!/usr/bin/env python3
"""
PreToolUse hook — restricts Write, Edit, MultiEdit.

Checks in order:
  1. Control-plane protection  — .contAIned/ writes are ALWAYS denied (not configurable)
  2. Settings protection       — .claude/settings.json is ALWAYS denied (not configurable)
  3. Secret file               — driven by policy.secrets.writes

Workspace boundary is enforced by the Docker container at the kernel level.

Exits 0 to allow, 2 to deny (reason on stderr fed back to agent).
Denials are written to the audit log before blocking.
"""
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _policy import load_policy  # noqa: E402


def log_denial(event, target, reason):
    """Append a denial entry to the audit log. Never raises — audit must not block."""
    try:
        project_root = Path(event.get("cwd", "."))
        audit_log = project_root / ".contAIned" / "audit" / "pipeline.jsonl"
        audit_log.parent.mkdir(parents=True, exist_ok=True)
        entry = {
            "ts":         datetime.now(timezone.utc).isoformat(),
            "session_id": event.get("session_id"),
            "tool":       event.get("tool_name"),
            "input":      {"file_path": target},
            "outcome":    "denied",
            "reason":     reason,
        }
        with audit_log.open("a") as f:
            f.write(json.dumps(entry) + "\\n")
    except OSError:
        pass
    # Mirror denial into tracer.db so it is queryable alongside allowed events.
    try:
        from contained.tracer import contAInedTracer  # noqa: PLC0415
        _db = str(Path(event.get("cwd", ".")) / ".contAIned" / "tracer.db")
        contAInedTracer(_db).log_event(
            session_id=event.get("agent_id") or event.get("session_id"),
            tool=event.get("tool_name", ""),
            tool_input={"file_path": target},
            outcome="denied",
            reason=reason,
        )
    except Exception:
        pass


def enforce(action, event, target, msg):
    """Act on *action*: block exits 2; allow/escalate pass through."""
    if action == "block":
        log_denial(event, target, msg)
        print(msg, file=sys.stderr)
        sys.exit(2)


try:
    event = json.load(sys.stdin)
except json.JSONDecodeError:
    sys.exit(0)  # malformed input — pass through, don\'t block

tool       = event.get("tool_name", "")
tool_input = event.get("tool_input", {})

if tool not in ("Write", "Edit", "MultiEdit"):
    sys.exit(0)

target = tool_input.get("file_path", "")
if not target:
    sys.exit(0)

cwd          = event.get("cwd", ".")
policy       = load_policy(cwd)
project_root = Path(cwd).resolve()
contAIned_dir    = project_root / ".contAIned"
resolved     = Path(target).resolve()

# ── Check 1: inside .contAIned/ control-plane (always enforced, not configurable) ─
try:
    resolved.relative_to(contAIned_dir)
    log_denial(event, target, f"write into control-plane directory: {target}")
    print(
        f"Write denied: \\'{target}\\' is inside the .contAIned/ control-plane directory.\\n"
        "Hook and policy files are managed by contAIned and must not be edited directly.",
        file=sys.stderr,
    )
    sys.exit(2)
except ValueError:
    pass  # not inside .contAIned/ — continue

# ── Check 2: .claude/settings.json — Claude Code hook registration file ───────
claude_settings = (project_root / ".claude" / "settings.json").resolve()
if resolved == claude_settings:
    log_denial(event, target, f"write to Claude Code settings file: {target}")
    print(
        f"Write denied: \\'{target}\\' is the Claude Code settings file.\\n"
        "Hook registration is managed by contAIned and must not be edited directly.",
        file=sys.stderr,
    )
    sys.exit(2)

# ── Check 3: secret file ───────────────────────────────────────────────────────
for _action, _patterns, _reason in policy["secrets"]["_compiled_rules"]:
    if any(p.search(str(resolved)) for p in _patterns):
        if _action == "allow":
            break  # safe variant — permit
        enforce(
            _action, event, target,
            _reason or f"Write denied: \\'{target}\\' looks like a secret file.",
        )
        break

sys.exit(0)
'''

RESTRICT_READS_HOOK = '''\
#!/usr/bin/env python3
"""
PreToolUse hook — restricts Read, Glob, and Grep tool calls.

Checks are driven by the policy: section of .contAIned/manifest.yaml.
  policy.secrets.reads         — action for secret-file read attempts
  policy.secrets.safe_variants — action for .env.example / template variants

Workspace boundary is enforced by the Docker container at the kernel level.

Action values: block | allow | escalate
  block    — deny (exit 2, reason on stderr)
  allow    — permit unconditionally; skip the check
  escalate — pass through (exit 0); SDK\'s canUseTool callback decides

Exits 0 to allow, 2 to deny (reason on stderr fed back to agent).
Denials are written to the audit log before blocking.
"""
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _policy import load_policy  # noqa: E402


def log_denial(event, target, reason):
    """Append a denial entry to the audit log. Never raises."""
    try:
        project_root = Path(event.get("cwd", "."))
        audit_log = project_root / ".contAIned" / "audit" / "pipeline.jsonl"
        audit_log.parent.mkdir(parents=True, exist_ok=True)
        entry = {
            "ts":         datetime.now(timezone.utc).isoformat(),
            "session_id": event.get("session_id"),
            "tool":       event.get("tool_name"),
            "input":      {"target": target},
            "outcome":    "denied",
            "reason":     reason,
        }
        with audit_log.open("a") as f:
            f.write(json.dumps(entry) + "\\n")
    except OSError:
        pass
    # Mirror denial into tracer.db so it is queryable alongside allowed events.
    try:
        from contained.tracer import contAInedTracer  # noqa: PLC0415
        _db = str(Path(event.get("cwd", ".")) / ".contAIned" / "tracer.db")
        contAInedTracer(_db).log_event(
            session_id=event.get("agent_id") or event.get("session_id"),
            tool=event.get("tool_name", ""),
            tool_input={"file_path": target},
            outcome="denied",
            reason=reason,
        )
    except Exception:
        pass


def enforce(action, event, target, msg):
    """Act on *action*: block exits 2; allow/escalate pass through."""
    if action == "block":
        log_denial(event, target, msg)
        print(msg, file=sys.stderr)
        sys.exit(2)


try:
    event = json.load(sys.stdin)
except json.JSONDecodeError:
    sys.exit(0)

cwd        = event.get("cwd", ".")
policy     = load_policy(cwd)
tool       = event.get("tool_name", "")
tool_input = event.get("tool_input", {})

if tool == "Read":
    target = tool_input.get("file_path", "")
elif tool == "Grep":
    target = tool_input.get("path", "")
elif tool == "Glob":
    target = tool_input.get("pattern", "")
else:
    sys.exit(0)

if not target:
    sys.exit(0)

# ── Secret file ───────────────────────────────────────────────────────────────
for _action, _patterns, _reason in policy["secrets"]["_compiled_rules"]:
    if any(p.search(target) for p in _patterns):
        if _action == "allow":
            break  # safe variant — permit
        enforce(
            _action, event, target,
            _reason or "Access denied: secret files (credentials, keys, .env) may not be read.",
        )
        break

sys.exit(0)
'''

RESTRICT_BASH_HOOK = '''\
#!/usr/bin/env python3
"""
PreToolUse hook — restricts Bash tool calls.

All checks are driven by manifest.yaml (baked into the container image).

Checks applied in order:
  1. policy.secrets.rules — read cmds targeting secret files (first match wins)
  2. policy.bash.rules    — ordered rule list; first match wins
     Each rule: {name, patterns, reason, action: allow|block|escalate}

For each command this hook outputs one of three JSON decisions:
  permissionDecision: "deny"  — blocked by a bash rule or secret-file check
  permissionDecision: "allow" — matches an action:allow rule in policy.bash.rules
  permissionDecision: "ask"   — no rule matched; operator prompt fires

The "allow" and "ask" paths exist because a PreToolUse hook returning "ask"
overrides the managed-settings allow list.  Safe commands must therefore be
listed first in policy.bash.rules with action:allow so they are not accidentally
caught by the "ask" fallback.

Outputs JSON to stdout; denials also written to the audit log.
"""
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _policy import load_policy  # noqa: E402


READ_CMD_RE = re.compile(
    r\'^\\s*(cat|head|tail|less|more|bat|pg|view|grep|egrep|fgrep|rg|ag|ack|sed|awk)\\s\',
    re.IGNORECASE,
)



def abs_path_tokens(command):
    """Extract tokens that resolve to absolute paths, including ~/... home-relative paths."""
    result = []
    for t in command.split():
        expanded = os.path.expanduser(t)
        if expanded.startswith("/") and len(expanded) > 1:
            result.append(expanded)
    return result


def log_denial(event, command, reason):
    try:
        project_root = Path(event.get("cwd", "."))
        audit_log = project_root / ".contAIned" / "audit" / "pipeline.jsonl"
        audit_log.parent.mkdir(parents=True, exist_ok=True)
        entry = {
            "ts":         datetime.now(timezone.utc).isoformat(),
            "session_id": event.get("session_id"),
            "tool":       event.get("tool_name"),
            "input":      {"command": command},
            "outcome":    "denied",
            "reason":     reason,
        }
        with audit_log.open("a") as f:
            f.write(json.dumps(entry) + "\\n")
    except OSError:
        pass
    # Mirror denial into tracer.db so it is queryable alongside allowed events.
    try:
        from contained.tracer import contAInedTracer  # noqa: PLC0415
        _db = str(Path(event.get("cwd", ".")) / ".contAIned" / "tracer.db")
        contAInedTracer(_db).log_event(
            session_id=event.get("agent_id") or event.get("session_id"),
            tool=event.get("tool_name", ""),
            tool_input={"command": command},
            outcome="denied",
            reason=reason,
        )
    except Exception:
        pass


def enforce(action, event, command, msg):
    """Block the tool call: log denial, output JSON deny decision, exit 2."""
    if action == "block":
        log_denial(event, command, msg)
        print(json.dumps({
            "hookSpecificOutput": {
                "hookEventName": "PreToolUse",
                "permissionDecision": "deny",
                "permissionDecisionReason": msg,
            }
        }))
        sys.exit(2)


def _ask():
    """Output a permissionDecision:ask response and exit 0."""
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "ask",
        }
    }))
    sys.exit(0)


try:
    event = json.load(sys.stdin)
except json.JSONDecodeError:
    _ask()

command = event.get("tool_input", {}).get("command", "")
if not command:
    _ask()

cwd    = event.get("cwd", ".")
policy = load_policy(cwd)

# ── Check 1: secret file reads ────────────────────────────────────────────────
_sec_rules = policy["secrets"]["_compiled_rules"]
if READ_CMD_RE.match(command):
    for token in command.split():
        for _action, _patterns, _reason in _sec_rules:
            if any(p.search(token) for p in _patterns):
                if _action == "allow":
                    break  # safe variant token — skip
                enforce(
                    _action, event, command,
                    _reason or f"Bash denied: \\'{token}\\' looks like a secret file.",
                )
                break  # first matching rule for this token wins

# ── Bash command rules (allow / block / escalate) ────────────────────────────
for _action, _patterns, _reason in policy["bash"]["_compiled_rules"]:
    if any(pat.search(command) for pat in _patterns):
        if _action == "allow":
            print(json.dumps({
                "hookSpecificOutput": {
                    "hookEventName": "PreToolUse",
                    "permissionDecision": "allow",
                }
            }))
            sys.exit(0)
        elif _action == "block":
            enforce(_action, event, command, _reason)
        else:  # escalate
            _ask()

# No rule matched — ask the operator for explicit approval.
_ask()
'''

AUDIT_HOOK = '''\
#!/usr/bin/env python3
"""
PostToolUse hook — records a structured audit entry for every tool execution.

Primary store : tracer.db via contAInedTracer.log_event() (SQLite, concurrent-safe).
Optional mirror: .contAIned/audit/pipeline.jsonl, controlled by policy.audit.jsonl_export.

Logging is controlled by policy.audit.enabled in manifest.yaml.
This hook must never block execution (always exits 0).
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _policy import load_policy  # noqa: E402


try:
    event = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError):
    sys.exit(0)

cwd    = event.get("cwd", ".")
policy = load_policy(cwd)

if not policy["audit"]["enabled"]:
    sys.exit(0)

session_id    = event.get("session_id")
agent_id      = event.get("agent_id")
actor_id      = agent_id or session_id
tool          = event.get("tool_name", "")
tool_input    = event.get("tool_input") or {}
tool_response = event.get("tool_response") or {}

is_error = tool_response.get("is_error", False)
outcome  = "denied" if is_error else "success"

reason = None
if is_error:
    content = tool_response.get("content")
    if isinstance(content, list):
        reason = " ".join(
            block.get("text", "") for block in content if isinstance(block, dict)
        ).strip() or None
    elif isinstance(content, str):
        reason = content or None

# ── Exception detection ───────────────────────────────────────────────────────
# Flag successful WebFetch/WebSearch/Skill/MCP calls that were approved outside
# the policy allowlist — these required operator confirmation and are exceptions.
approved_exception = False
exception_detail: str | None = None
if outcome == "success":
    network_policy = policy.get("network", {})
    allowed_domains = network_policy.get("allowed_domains", [])
    if tool == "WebFetch":
        try:
            from urllib.parse import urlparse  # noqa: PLC0415
            domain = urlparse(tool_input.get("url", "")).hostname or ""
            if domain and domain not in allowed_domains:
                approved_exception = True
                exception_detail = domain
        except Exception:
            pass
    elif tool == "WebSearch":
        approved_exception = True
    elif tool == "Skill":
        skill_name = tool_input.get("skill", "") or tool_input.get("name", "")
        approved_skills = policy.get("skills", {}).get("approved_skills", [])
        if skill_name and skill_name not in approved_skills:
            approved_exception = True
            exception_detail = skill_name
    elif tool.startswith("mcp__"):
        parts = tool.split("__", 2)
        server = parts[1] if len(parts) > 1 else ""
        approved_servers = policy.get("mcp", {}).get("approved_servers", [])
        if server and server not in approved_servers:
            approved_exception = True
            exception_detail = server

# ── Primary store: tracer.db ──────────────────────────────────────────────────
try:
    from contained.tracer import contAInedTracer  # noqa: PLC0415
    db_path = str(Path(cwd) / ".contAIned" / "tracer.db")
    tracer  = contAInedTracer(db_path)
    tracer.log_event(
        session_id        = actor_id,
        tool              = tool,
        tool_input        = tool_input,
        outcome           = outcome,
        reason            = reason,
        tool_response     = tool_response,
        approved_exception = approved_exception,
        exception_detail   = exception_detail,
    )
except Exception:
    pass  # never block execution due to logging failure

# ── Optional JSONL mirror ─────────────────────────────────────────────────────
if policy["audit"].get("jsonl_export", False):
    from datetime import datetime, timezone  # noqa: PLC0415
    entry = {
        "ts":         datetime.now(timezone.utc).isoformat(),
        "session_id": actor_id,
        "tool":       tool,
        "input":      tool_input,
        "outcome":    outcome,
    }
    if reason:
        entry["reason"] = reason
    if approved_exception:
        entry["approved_exception"] = True
        if exception_detail:
            entry["exception_detail"] = exception_detail
    try:
        audit_log = Path(cwd) / ".contAIned" / "audit" / "pipeline.jsonl"
        audit_log.parent.mkdir(parents=True, exist_ok=True)
        with audit_log.open("a") as f:
            f.write(json.dumps(entry) + "\\n")
    except OSError:
        pass

sys.exit(0)
'''

PERMISSION_REQUEST_HOOK = '''\
#!/usr/bin/env python3
"""
PermissionRequest hook — audits every permission request to tracer.db.

Records the fact that the agent requested permission for a tool call.
Never blocks execution (always exits 0 without output).

To infer the user\'s decision, cross-reference with PostToolUse:
  - PermissionRequest entry + matching PostToolUse success  → user approved
  - PermissionRequest entry + no matching PostToolUse ~30s  → user denied (inferred)

Matching key: (session_id, tool_name, tool_input) + temporal proximity.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _policy import load_policy  # noqa: E402

try:
    event = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError):
    sys.exit(0)

cwd    = event.get("cwd", ".")
policy = load_policy(cwd)

if not policy["audit"]["enabled"]:
    sys.exit(0)

session_id = event.get("session_id")
agent_id   = event.get("agent_id")
actor_id   = agent_id or session_id
tool       = event.get("tool_name", "")
tool_input = event.get("tool_input") or {}

try:
    from contained.tracer import contAInedTracer  # noqa: PLC0415
    db_path = str(Path(cwd) / ".contAIned" / "tracer.db")
    tracer  = contAInedTracer(db_path)
    tracer.log_event(
        session_id    = actor_id,
        tool          = tool,
        tool_input    = tool_input,
        outcome       = "permission_requested",
        reason        = None,
        tool_response = {},
    )
except Exception:
    pass  # never block execution due to logging failure

sys.exit(0)
'''

QA_HOOK = '''\
#!/usr/bin/env python3
"""
Stop hook — runs QA checks when the agent signals it is done.

Which checks run is controlled by policy.qa.checks in manifest.yaml.
Each entry is either a bare exec-form array or a named object:

  - ["ruff", "check", "."]
  - name: tests
    command: ["pytest", "tests/", "-x", "-q"]
    when_changed: ["*.py"]   # skip if no matching files were touched

If checks is empty, QA passes trivially.
If any check fails → prints JSON with decision:block, agent receives feedback.
"""
import fnmatch
import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _policy import load_policy  # noqa: E402

try:
    event = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError):
    event = {}

cwd      = event.get("cwd", ".")
TASK_DIR = Path(cwd).resolve()
policy   = load_policy(cwd)
checks   = policy["qa"].get("checks", [])

# ── Fetch touched files for when_changed evaluation ───────────────────────────
_touched: list[str] = []
_session_id = event.get("session_id")
if _session_id:
    try:
        from contained.tracer import contAInedTracer  # noqa: PLC0415
        _tracer  = contAInedTracer(str(Path(cwd) / ".contAIned" / "tracer.db"))
        _touched = _tracer.list_touched_files(_session_id)
    except Exception:
        pass  # tracer unavailable — when_changed guards will not filter


def run(cmd: list) -> tuple[int, str]:
    result = subprocess.run(cmd, cwd=TASK_DIR, capture_output=True, text=True)
    return result.returncode, result.stdout + result.stderr


def _expand(entry) -> dict:
    """Normalise a bare array or named-object check entry into a uniform dict."""
    if isinstance(entry, list):
        return {"name": entry[0], "command": entry, "when_changed": []}
    return {
        "name":         entry.get("name", (entry.get("command") or ["?"])[0]),
        "command":      entry.get("command", []),
        "when_changed": entry.get("when_changed", []),
    }


def _files_match(touched: list[str], patterns: list[str]) -> bool:
    """Return True if any touched filename matches any fnmatch glob pattern."""
    return any(
        fnmatch.fnmatch(Path(f).name, pat)
        for f in touched
        for pat in patterns
    )


check_results: list = []
failures: list = []


def record(name: str, status: str, output: str = "") -> None:
    check_results.append({"name": name, "status": status, "output": output})


# ── Run checks ────────────────────────────────────────────────────────────────
for _entry in checks:
    _check = _expand(_entry)
    _name  = _check["name"]
    _cmd   = _check["command"]
    _when  = _check["when_changed"]

    if not _cmd:
        record(_name, "skip", "no command specified")
        continue

    if _when and not _files_match(_touched, _when):
        record(_name, "skip", "no matching files touched")
        continue

    try:
        _code, _out = run(_cmd)
    except FileNotFoundError:
        record(_name, "skip", f"{_cmd[0]!r} not found")
        continue

    # Exit code 5 from pytest means no tests collected — treat as pass.
    if _code not in (0, 5):
        failures.append({"check": _name, "output": _out})
        record(_name, "fail", _out)
    else:
        record(_name, "pass")

# ── Emit result JSON (always) ─────────────────────────────────────────────────
result: dict = {"checks": check_results}
if failures:
    feedback = "QA failed — fix the following issues before finishing:\\n\\n"
    for item in failures:
        feedback += f"### {item[\'check\']}\\n```\\n{item[\'output\']}\\n```\\n\\n"
    result["decision"] = "block"
    result["reason"] = feedback
print(json.dumps(result))
sys.exit(0)
'''

CLAUDE_MD = """\
# contAIned Agent — Operating Instructions

You are a coding agent operating within a contAIned pipeline.

## Your environment

- **Policy** is enforced automatically by hooks before every tool call.
  You do not need to second-guess what is allowed — just attempt the operation.
  If it is not permitted, you will receive a clear denial message explaining why.

## Task format

Each task you receive will specify:
- A clear description of what to produce
- Acceptance criteria — what "done" looks like
- The source files you should read

## Rules

1. Always attempt tool calls as requested — policy is enforced automatically by hooks.
   If a call is denied you will receive a clear reason; read it and adapt your approach.
2. Do not retry a denied tool call with the same arguments.
3. When you believe the task is complete, stop. The QA hook will run automatically and
   will give you feedback if anything needs fixing.
4. Do not modify files in `.contAIned/` — these are control-plane files.

## Signals

- Tool denied + reason → read the reason, change approach
- QA feedback after stopping → fix the issues described, then stop again
- Session summary after stopping (reason starts with "QA:") → present it to the operator and stop again without making any changes
"""

GITIGNORE_BLOCK = """
# contAIned — control plane
# The .contAIned/ directory contains hooks, policy, and audit logs managed by contAIned.
# Keep it out of version control.
.contAIned/
"""

GITIGNORE_TEMPLATE = """\
# ── OS ────────────────────────────────────────────────────────────────────────
.DS_Store
Thumbs.db
desktop.ini

# ── Editors ───────────────────────────────────────────────────────────────────
.idea/
.vscode/
*.swp
*.swo

# ── Python ────────────────────────────────────────────────────────────────────
__pycache__/
*.py[cod]
*.egg-info/
dist/
build/
.venv/
.env

# ── Node ──────────────────────────────────────────────────────────────────────
node_modules/

# ── contAIned — control plane ─────────────────────────────────────────────────────
# The .contAIned/ directory contains hooks, policy, and audit logs managed by contAIned.
# Keep it out of version control.
.contAIned/
"""

WORKSPACE_GITKEEP = ""  # empty — just creates the directory marker

# ── New Phase-2 hook templates ─────────────────────────────────────────────────

TRACER_PRE_HOOK = '''\
#!/usr/bin/env python3
"""
PreToolUse hook — captures file baselines before Write, Edit, or MultiEdit.

Runs after restrict_writes.py in the PreToolUse chain.  When restrict_writes.py
exits 2 (deny), the SDK aborts the chain and this hook never fires — no baseline
is recorded for denied writes.  This is correct behaviour.

Actor ID resolution:
  actor_id = agent_id or session_id   (agent_id present only for sub-agent calls)

This hook must never block writes (always exits 0).
"""
import json
import sys
from pathlib import Path

try:
    event = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError):
    sys.exit(0)

tool = event.get("tool_name", "")
if tool not in ("Write", "Edit", "MultiEdit"):
    sys.exit(0)

tool_input = event.get("tool_input") or {}
cwd        = event.get("cwd", ".")

# ── Actor ID resolution ────────────────────────────────────────────────────────
session_id = event.get("session_id")
agent_id   = event.get("agent_id")
actor_id   = agent_id or session_id

if not actor_id:
    sys.exit(0)

# ── Collect file paths ─────────────────────────────────────────────────────────
if tool == "MultiEdit":
    edits      = tool_input.get("edits") or []
    file_paths = list({e["file_path"] for e in edits if e.get("file_path")})
else:
    fp         = tool_input.get("file_path")
    file_paths = [fp] if fp else []

if not file_paths:
    sys.exit(0)

# ── Capture baselines ──────────────────────────────────────────────────────────
db_path = str(Path(cwd) / ".contAIned" / "tracer.db")

try:
    from contained.tracer import contAInedTracer  # noqa: PLC0415
    tracer = contAInedTracer(db_path)
    for file_path in file_paths:
        tracer.capture_baseline(actor_id, file_path)
except Exception:
    pass  # tracer must never block writes

sys.exit(0)
'''

TRACER_POST_HOOK = '''\
#!/usr/bin/env python3
"""
PostToolUse hook — records file snapshots after Write, Edit, or MultiEdit.

Reads each affected file from disk (not from tool_input) so the stored blob
always matches what is actually on disk.  Handles Write, Edit, and MultiEdit
uniformly by resolving file paths from tool_input.

Actor ID resolution:
  actor_id = agent_id or session_id

This hook must never block execution (always exits 0).
"""
import json
import sys
from pathlib import Path

try:
    event = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError):
    sys.exit(0)

tool = event.get("tool_name", "")
if tool not in ("Write", "Edit", "MultiEdit"):
    sys.exit(0)

tool_input    = event.get("tool_input") or {}
tool_response = event.get("tool_response") or {}
cwd           = event.get("cwd", ".")

# Skip if the write failed (is_error means the tool errored out)
if tool_response.get("is_error"):
    sys.exit(0)

# ── Actor ID resolution ────────────────────────────────────────────────────────
session_id = event.get("session_id")
agent_id   = event.get("agent_id")
actor_id   = agent_id or session_id

if not actor_id:
    sys.exit(0)

# ── Collect file paths ─────────────────────────────────────────────────────────
if tool == "MultiEdit":
    edits      = tool_input.get("edits") or []
    file_paths = list({e["file_path"] for e in edits if e.get("file_path")})
else:
    fp         = tool_input.get("file_path")
    file_paths = [fp] if fp else []

if not file_paths:
    sys.exit(0)

# ── Record snapshots ───────────────────────────────────────────────────────────
db_path = str(Path(cwd) / ".contAIned" / "tracer.db")

try:
    from contained.tracer import contAInedTracer  # noqa: PLC0415
    tracer = contAInedTracer(db_path)
    for file_path in file_paths:
        path = Path(file_path)
        if path.exists():
            content = path.read_bytes()
            tracer.track_write(actor_id, file_path, content)
except Exception:
    pass  # tracer must never block execution

sys.exit(0)
'''

SUBAGENT_START_HOOK = '''\
#!/usr/bin/env python3
"""
SubagentStart hook — registers a new sub-agent task in tracer.db.

Fires when a sub-agent is spawned via the Agent tool.  Records the sub-agent
as an open task, linked to the root session via parent_session_id.

Event fields used:
  agent_id   — the sub-agent\'s unique identifier  (actor for this task)
  session_id — always the root session\'s ID        (parent reference)

This hook must never block execution (always exits 0).
"""
import json
import sys
from pathlib import Path

try:
    event = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError):
    sys.exit(0)

cwd        = event.get("cwd", ".")
session_id = event.get("session_id")   # root session (parent)
agent_id   = event.get("agent_id")     # sub-agent being spawned

if not agent_id or not session_id:
    sys.exit(0)

# Derive a human-readable prompt from whatever context the event provides.
agent_type  = event.get("agent_type") or event.get("subagent_type") or "sub-agent"
description = event.get("description") or event.get("prompt") or ""
prompt = ("[" + agent_type + "] " + description).strip() if description else ("[" + agent_type + "]")

db_path = str(Path(cwd) / ".contAIned" / "tracer.db")

try:
    from contained.tracer import contAInedTracer  # noqa: PLC0415
    tracer = contAInedTracer(db_path)
    tracer.open_task(agent_id, prompt, parent_session_id=session_id)
except Exception:
    pass

sys.exit(0)
'''

SUBAGENT_STOP_HOOK = '''\
#!/usr/bin/env python3
"""
SubagentStop hook — marks a sub-agent task as closed in tracer.db.

Fires when a sub-agent finishes (successfully or otherwise).  Transitions the
sub-agent\'s task from open → closed so the root summarizer can proceed.

Event fields used:
  agent_id — the sub-agent that just finished

This hook must never block execution (always exits 0).
"""
import json
import sys
from pathlib import Path

try:
    event = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError):
    sys.exit(0)

cwd      = event.get("cwd", ".")
agent_id = event.get("agent_id")

if not agent_id:
    sys.exit(0)

db_path = str(Path(cwd) / ".contAIned" / "tracer.db")

try:
    from contained.tracer import contAInedTracer  # noqa: PLC0415
    tracer = contAInedTracer(db_path)
    tracer.set_task_status(agent_id, "closed")
except Exception:
    pass

sys.exit(0)
'''

SUMMARIZER_HOOK = '''\
#!/usr/bin/env python3
"""
Stop hook — runs QA checks, processes any pending git push, and closes the task.

Fires only for root-agent Stop events (not SubagentStop — that is wired to
subagent_stop.py).  This is the sole Stop hook; it owns QA, push processing,
and task closure.

Flow:
  1. Sentinel check: if task already "closed", exit 0 (no-op).
  2. Run qa.py inline — if any check fails, block and return to agent immediately.
  3. Defensive child check: poll up to 3 × 200 ms for open sub-agent sessions.
  4. Build provenance_log — append current container provenance to any existing
     entries so resumed tasks preserve the full signing history across rebuilds.
  5. Collect file diffs and action log for the operator summary UI.
  6. If a git push happened this session: build_actions, assemble_payload, POST,
     mark work unit pushed, open next work unit.
  7. Store transcript_path; set task status = closed.
  8. Block with a formatted summary so Claude surfaces it to the operator.
"""
import json
import os
import subprocess
import sys
import time
from pathlib import Path

try:
    event = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError):
    event = {}

cwd        = event.get("cwd", ".")
session_id = event.get("session_id")

# A Stop event for a sub-agent carries agent_id; the summarizer only runs for
# the root session.  This guard is a safety net — the hook is registered for
# Stop only, not SubagentStop, so agent_id should never be present here.
if event.get("agent_id"):
    sys.exit(0)

if not session_id:
    sys.exit(0)

# ── Phase 1: QA checks ────────────────────────────────────────────────────────
# Run qa.py inline before building the summary or showing the approval UI.
# This guarantees QA always completes first regardless of whether the SDK
# executes Stop hooks sequentially or in parallel.
_qa_checks: list = []
_qa_script = Path(cwd) / ".contAIned" / "hooks" / "qa.py"
if _qa_script.exists():
    try:
        _qa_proc = subprocess.run(
            [sys.executable, str(_qa_script)],
            input=json.dumps(event),
            capture_output=True,
            text=True,
            cwd=cwd,
        )
        if _qa_proc.stdout.strip():
            try:
                _qa_out = json.loads(_qa_proc.stdout.strip())
                if _qa_out.get("decision") == "block":
                    # QA failed — relay only the block decision to the SDK.
                    print(json.dumps({
                        "decision": "block",
                        "reason": _qa_out.get("reason", "QA checks failed"),
                    }))
                    sys.exit(0)
                _qa_checks = _qa_out.get("checks", [])
            except json.JSONDecodeError:
                _qa_checks = []
    except Exception:
        _qa_checks = []
        pass  # qa unavailable — proceed to approval UI

db_path = str(Path(cwd) / ".contAIned" / "tracer.db")

# ── Import tracer ──────────────────────────────────────────────────────────────
try:
    from contained.tracer import contAInedTracer  # noqa: PLC0415
    tracer = contAInedTracer(db_path)
except Exception:
    # If the tracer is unavailable the agent should still be allowed to stop.
    sys.exit(0)

# ── Sentinel: second Stop after Claude has already presented the summary ───────
# The first pass stores the summary and blocks with it for Claude to format.
# On the second Stop (after Claude has presented and stopped again), the task
# is already "closed" — exit 0 so the agent stops cleanly.
try:
    _status_row = tracer.conn.execute(
        "SELECT status FROM tasks WHERE session_id = ?", (session_id,)
    ).fetchone()
    if _status_row and _status_row[0] == "closed":
        sys.exit(0)
except Exception:
    pass

# ── Defensive child check ──────────────────────────────────────────────────────
# The SDK fires SubagentStop for all children before the root Stop, but under
# parallel sub-agent execution there may be a brief race.  Poll up to 3 times.
open_children = []
for _attempt in range(3):
    try:
        rows = tracer.conn.execute(
            "SELECT session_id FROM tasks WHERE parent_session_id = ? AND status = \'open\'",
            (session_id,),
        ).fetchall()
        open_children = [r[0] for r in rows]
    except Exception:
        open_children = []
    if not open_children:
        break
    time.sleep(0.2)

# ── Build provenance log ───────────────────────────────────────────────────────
# Read the provenance snapshot bind-mounted read-only at container startup
# (see docker_runner.py).  Merge with any existing log entries so that tasks
# resumed after a container rebuild accumulate the full signing history —
# each closure records exactly which signed image was running at that point.
_prov_log: list = []
try:
    _existing_row = tracer.conn.execute(
        "SELECT summary FROM tasks WHERE session_id = ?", (session_id,)
    ).fetchone()
    if _existing_row and _existing_row[0]:
        _prov_log = json.loads(_existing_row[0]).get("provenance_log", [])
except Exception:
    pass

_prov_snapshot = Path("/run/contained/provenance.yaml")
if _prov_snapshot.exists():
    try:
        import yaml as _yaml
        _prov = _yaml.safe_load(_prov_snapshot.read_text()) or {}
        _prov_log.append({
            "closed_at":         time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "image_digest":      _prov.get("image_digest", ""),
            "operator_identity": _prov.get("operator_identity", ""),
            "oidc_issuer":       _prov.get("oidc_issuer", ""),
            "signed_at":         _prov.get("signed_at", ""),
            "rekor_log_index":   _prov.get("rekor_log_index"),
            "rekor_entry_url":   _prov.get("rekor_entry_url", ""),
        })
    except Exception:
        pass

# ── Collect file diffs ─────────────────────────────────────────────────────────
try:
    touched_files = tracer.list_touched_files(session_id)
except Exception:
    touched_files = []

# ── Skip summary UI if nothing was written this session ───────────────────────
if not touched_files:
    try:
        tracer.set_task_status(session_id, "closed", summary={"provenance_log": _prov_log, "file_changes": [], "action_log": [], "qa_checks": _qa_checks})
    except Exception:
        pass
    sys.exit(0)

# Build a lookup of write-tool audit events per file path (for reasons).
try:
    all_audit = tracer.recent_audit_events(session_id, limit=500)
    _write_events_by_file: dict = {}
    for _ev in reversed(all_audit):
        if _ev["tool"] in ("Write", "Edit", "MultiEdit") and _ev.get("input"):
            _fp = _ev["input"].get("file_path") or ""
            if _fp:
                _write_events_by_file.setdefault(_fp, []).append(_ev)
            # MultiEdit may touch multiple files
            for _mfp in (_ev["input"].get("file_paths") or []):
                _write_events_by_file.setdefault(_mfp, []).append(_ev)
except Exception:
    _write_events_by_file = {}

# Resolve session tree once for baseline lookups.
try:
    _tree_ids = tracer.tree_session_ids(session_id)
    _tree_placeholders = ",".join("?" * len(_tree_ids)) if _tree_ids else "\'__none__\'"
except Exception:
    _tree_ids = []
    _tree_placeholders = "\'__none__\'"

file_diffs: list[dict] = []
for file_path in touched_files:
    try:
        diff_text = tracer.diff_task(session_id, file_path)
        if not diff_text:
            continue
        lines_added   = sum(1 for ln in diff_text.splitlines() if ln.startswith("+") and not ln.startswith("+++"))
        lines_removed = sum(1 for ln in diff_text.splitlines() if ln.startswith("-") and not ln.startswith("---"))

        # Determine change type from the earliest baseline pre_hash.
        change_type = "modified"
        try:
            if _tree_ids:
                _bl = tracer.conn.execute(
                    f"SELECT pre_hash FROM baselines WHERE file_path = ? AND session_id IN ({_tree_placeholders}) ORDER BY captured_at ASC LIMIT 1",
                    [file_path, *_tree_ids],
                ).fetchone()
                if _bl is not None:
                    change_type = "new file" if _bl[0] is None else "modified"
        except Exception:
            pass

        # Build a short human-readable reason from write-tool events for this file.
        _file_write_evs = _write_events_by_file.get(file_path, [])
        if _file_write_evs:
            _tools_used = list(dict.fromkeys(e["tool"] for e in _file_write_evs))
            reason = ", ".join(t.lower() for t in _tools_used)
        else:
            reason = change_type

        file_diffs.append({
            "file_path":     file_path,
            "diff":          diff_text,
            "lines_added":   lines_added,
            "lines_removed": lines_removed,
            "change_type":   change_type,
            "reason":        reason,
        })
    except Exception:
        pass

# ── Build action log ───────────────────────────────────────────────────────────
try:
    raw_events = tracer.recent_audit_events(session_id, limit=200)
    action_log = [
        e for e in reversed(raw_events)
        if e["tool"] in ("Bash", "Agent") or e["outcome"] == "denied"
    ]
except Exception:
    action_log = []

# ── Look up task prompt ────────────────────────────────────────────────────────
try:
    row = tracer.conn.execute(
        "SELECT prompt, started_at FROM tasks WHERE session_id = ?", (session_id,)
    ).fetchone()
    task_prompt    = row[0] if row else "(unknown)"
    task_started   = row[1] if row else None
except Exception:
    task_prompt  = "(unknown)"
    task_started = None

# ── Assemble and store summary ─────────────────────────────────────────────────
summary = {
    "provenance_log": _prov_log,
    "file_changes": [
        {
            "file_path":   d["file_path"],
            "lines_added": d["lines_added"],
            "lines_removed": d["lines_removed"],
            "change_type": d["change_type"],
            "reason":      d["reason"],
        }
        for d in file_diffs
    ],
    "action_log": action_log,
    "incomplete_children": open_children,
    "qa_checks": _qa_checks,
}

# ── Locate Claude Code transcript for this session ────────────────────────────
# Claude Code injects transcript_path directly into the hook event payload.
# Do NOT reconstruct this path from cwd: inside the container cwd resolves to
# /workspace, but Claude Code names the project directory using the host
# absolute path, so a reconstructed path would never match the real file.
_transcript_path = event.get("transcript_path", "") or ""

# ── Enrich action_log Bash entries with full stdout from transcript ────────────
# The transcript holds untruncated tool outputs; the audit_events table has only
# the first 500 chars.  We merge in-memory so the stored summary is richer.
if _transcript_path and Path(_transcript_path).exists():
    try:
        from contained.tracer import extract_tool_outputs_from_transcript  # noqa: PLC0415
        _tool_outputs = extract_tool_outputs_from_transcript(_transcript_path)
        # Build per-command output lists (same command may be run multiple times).
        _bash_outputs: dict = {}
        for _to in _tool_outputs:
            if _to["tool_name"] == "Bash":
                _cmd = (_to["input"].get("command") or "").strip()
                if _cmd:
                    _bash_outputs.setdefault(_cmd, []).append({
                        "output":    _to["output"],
                        "exit_code": _to["exit_code"],
                    })
        # Enrich action_log entries in-place (mutates the in-memory list only).
        _bash_use_counts: dict = {}
        for _entry in action_log:
            if _entry.get("tool") == "Bash":
                _cmd = ((_entry.get("input") or {}).get("command") or "").strip()
                _idx = _bash_use_counts.get(_cmd, 0)
                _bash_use_counts[_cmd] = _idx + 1
                _avail = _bash_outputs.get(_cmd, [])
                if _idx < len(_avail):
                    _full = _avail[_idx]
                    _entry.setdefault("input", {})
                    _entry["input"]["stdout"] = _full["output"][:10240]  # cap at 10 KB
                    if _full["exit_code"] is not None:
                        _entry["input"]["exit_code"] = _full["exit_code"]
    except Exception:
        pass

# Rebuild summary with enriched action_log.
summary["action_log"] = action_log

# ── Process any pending git push ───────────────────────────────────────────────
# Detect a successful git push this session; if found, build the ATP work unit
# payload, POST it to mainlined, close the work unit, and open the next one.
try:
    _wu_id = tracer.get_active_work_unit(session_id)
    if _wu_id:
        _push_events = tracer.conn.execute(
            """
            SELECT input FROM audit_events
            WHERE session_id = ? AND tool = \'Bash\' AND outcome = \'success\'
            ORDER BY id DESC LIMIT 50
            """,
            (session_id,),
        ).fetchall()
        _push_found = False
        for (_ae_input,) in _push_events:
            _inp = json.loads(_ae_input) if _ae_input else {}
            _cmd = (_inp.get("command") or "").strip()
            _exit = _inp.get("exit_code")
            if (
                _exit == 0
                and "git" in _cmd
                and "push" in _cmd
                and "--dry-run" not in _cmd
            ):
                _push_found = True
                break

        if _push_found:
            _head_res = subprocess.run(
                ["git", "rev-parse", "HEAD"],
                capture_output=True, text=True, cwd=cwd, timeout=10,
            )
            _head_commit = _head_res.stdout.strip() if _head_res.returncode == 0 else ""

            if _qa_checks:
                _qa_passed = all(
                    c.get("status") == "pass"
                    for c in _qa_checks
                    if c.get("status") != "skip"
                )
                tracer.record_qa_result(_wu_id, {"checks": _qa_checks, "passed": _qa_passed})

            _wu_narrative = None
            if _transcript_path and Path(_transcript_path).exists():
                try:
                    from contained.tracer import extract_narrative_from_transcript  # noqa: PLC0415
                    _wu_narrative = extract_narrative_from_transcript(_transcript_path) or None
                except Exception:
                    pass
            if _wu_narrative:
                try:
                    tracer.record_narrative(_wu_id, _wu_narrative)
                except Exception:
                    pass

            tracer.build_actions(_wu_id, [t for t in [_transcript_path] if t])

            try:
                _payload = tracer.assemble_payload(_wu_id)
            except Exception:
                _payload = None

            if _payload:
                try:
                    _mainlined_url = None
                    _manifest_path = Path(cwd) / ".contAIned" / "manifest.yaml"
                    if _manifest_path.exists():
                        import yaml as _yaml  # noqa: PLC0415
                        _manifest = _yaml.safe_load(_manifest_path.read_text()) or {}
                        _mainlined_url = _manifest.get("runtime", {}).get("mainlined", {}).get("url")
                    _mainlined_key = os.environ.get("MAINLINED_API_KEY")
                    if _mainlined_url and _mainlined_key:
                        import urllib.request  # noqa: PLC0415
                        _req = urllib.request.Request(
                            _mainlined_url,
                            data=json.dumps(_payload).encode("utf-8"),
                            headers={
                                "Content-Type": "application/json",
                                "Authorization": f"Bearer {_mainlined_key}",
                            },
                            method="POST",
                        )
                        urllib.request.urlopen(_req, timeout=30)
                except Exception:
                    pass

            if _head_commit:
                tracer.complete_work_unit(_wu_id, _head_commit)
                try:
                    _wu_row = tracer.conn.execute(
                        "SELECT repo_url, branch FROM work_units WHERE id = ?",
                        (_wu_id,),
                    ).fetchone()
                    if _wu_row:
                        tracer.open_or_find_work_unit(
                            repo_url=_wu_row[0],
                            branch=_wu_row[1],
                            base_commit=_head_commit,
                            prompt="(continued after push)",
                        )
                except Exception:
                    pass
except Exception:
    pass

# ── Store transcript path and close task ──────────────────────────────────────
if _transcript_path:
    try:
        tracer.set_task_transcript_path(session_id, _transcript_path)
    except Exception:
        pass

try:
    tracer.set_task_status(session_id, "closed", summary=summary)
except Exception:
    pass

# Block with a formatted summary so Claude surfaces it to the operator.
# On the next Stop (after Claude acknowledges), the sentinel check at the top
# detects status == "closed" and exits 0 cleanly — no infinite loop.
_status_icons = {"pass": "✓", "fail": "✗", "skip": "·"}
_qa_line = "  ".join(
    f"{_status_icons.get(c['status'], '?')} {c['name']}"
    for c in _qa_checks
) if _qa_checks else "(no checks recorded)"

_changed = summary.get("file_changes", [])
_files_line = "\\n".join(
    f"- {c['file_path'].replace('/workspace/', '')} (+{c['lines_added']}/-{c['lines_removed']})"
    for c in _changed
) if _changed else "- (no file changes)"

_prov_line = ""
if _prov_log:
    _latest = _prov_log[-1]
    _digest_short = (_latest.get("image_digest") or "")[:19]
    _operator = _latest.get("operator_identity") or ""
    _rekor = _latest.get("rekor_log_index")
    _prov_line = f"\\nProvenance: {_digest_short}… · {_operator}" + (f" · Rekor #{_rekor}" if _rekor else "")

_summary_msg = f"QA: {_qa_line}\\n\\nChanged:\\n{_files_line}{_prov_line}\\n"
print(json.dumps({"decision": "block", "reason": _summary_msg}))
sys.exit(0)
'''

USER_PROMPT_SUBMIT_HOOK = '''\
#!/usr/bin/env python3
"""
UserPromptSubmit hook — registers the root session in tracer.db on the first prompt,
opens or finds the current work unit, and records a policy snapshot.

Also audits operator shell escapes (! commands) if the SDK delivers them here.

Claude Code docs state this hook fires "when the user submits a prompt, before Claude
processes it" with no documented exception for ! shell escapes.  Whether ! commands
actually reach this hook is unconfirmed; the detection below is conditional — it logs
only when the prompt starts with "!" so legitimate prompts are unaffected either way.

Session history, audit logs, and file diffs are queryable via the /contained:tracer
skill backed by the tracer MCP server.
"""
import json
import subprocess
import sys
from pathlib import Path

try:
    event = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError):
    sys.exit(0)

prompt     = (event.get("prompt") or "").strip()
cwd        = event.get("cwd", ".")
session_id = event.get("session_id")
agent_id   = event.get("agent_id")

if session_id and not agent_id:
    db_path = Path(cwd) / ".contAIned" / "tracer.db"
    if db_path.exists():
        try:
            from contained.tracer import contAInedTracer  # noqa: PLC0415
            tracer = contAInedTracer(str(db_path))

            # ── Register root session on first prompt (idempotent) ────────────
            tracer.open_task(session_id, prompt)

            # ── Work unit registration ────────────────────────────────────────
            # Detect git state and associate this session with a work unit.
            # Errors are silently swallowed so git absence never blocks the agent.
            try:
                _git_url = subprocess.run(
                    ["git", "remote", "get-url", "origin"],
                    capture_output=True, text=True, cwd=cwd, timeout=5,
                ).stdout.strip()
                _git_branch = subprocess.run(
                    ["git", "rev-parse", "--abbrev-ref", "HEAD"],
                    capture_output=True, text=True, cwd=cwd, timeout=5,
                ).stdout.strip()
                _git_base = subprocess.run(
                    ["git", "rev-parse", "HEAD"],
                    capture_output=True, text=True, cwd=cwd, timeout=5,
                ).stdout.strip()
                if _git_url and _git_branch and _git_base:
                    _work_unit_id = tracer.open_or_find_work_unit(
                        repo_url=_git_url,
                        branch=_git_branch,
                        base_commit=_git_base,
                        prompt=prompt or "(no prompt)",
                    )
                    tracer.register_session_in_work_unit(_work_unit_id, session_id)
                    tracer.record_policy_snapshot(
                        work_unit_id=_work_unit_id,
                        session_id=session_id,
                        manifest_path=str(Path(cwd) / ".contAIned" / "manifest.yaml"),
                        provenance_path="/run/contained/provenance.yaml",
                    )
            except Exception:
                pass

            # ── Audit operator shell escapes (! commands) ─────────────────────
            # If the SDK delivers ! commands to this hook, prompt starts with "!".
            # Log them as OperatorShell events so they appear in the audit trail
            # alongside agent tool calls.  If the SDK intercepts ! before firing
            # this hook, this block never runs — no false positives either way.
            if prompt.startswith("!"):
                tracer.log_event(
                    session_id=session_id,
                    tool="OperatorShell",
                    tool_input={"command": prompt[1:].strip()},
                    outcome="operator",
                    reason="operator shell escape (!)",
                )
        except Exception:
            pass

sys.exit(0)
'''

PUSH_HOOK = '''\
#!/usr/bin/env python3
"""
PostToolUse hook — detects successful git push Bash commands and logs a GitPush
audit event so the stop hook\'s push-processing path can detect it reliably.

The actual payload assembly (build_actions, assemble_payload, POST) happens in
the stop hook (summarizer.py) which has the full session transcript available.

This hook must never block execution (always exits 0).
"""
import json
import sys

try:
    event = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError):
    sys.exit(0)

tool = event.get("tool_name", "")
if tool != "Bash":
    sys.exit(0)

tool_input    = event.get("tool_input") or {}
tool_response = event.get("tool_response") or {}

cmd = (tool_input.get("command") or "").strip()
if not ("git" in cmd and "push" in cmd and "--dry-run" not in cmd):
    sys.exit(0)

exit_code = tool_response.get("exit_code")
if exit_code is not None and exit_code != 0:
    sys.exit(0)

session_id = event.get("session_id")
agent_id   = event.get("agent_id")
actor_id   = agent_id or session_id
cwd        = event.get("cwd", ".")

if not actor_id:
    sys.exit(0)

try:
    from pathlib import Path
    from contained.tracer import contAInedTracer  # noqa: PLC0415
    db_path = str(Path(cwd) / ".contAIned" / "tracer.db")
    tracer = contAInedTracer(db_path)
    tracer.log_event(
        session_id=actor_id,
        tool="GitPush",
        tool_input={"command": cmd},
        outcome="success",
        reason=None,
    )
except Exception:
    pass

sys.exit(0)
'''
