"""
Templates for files generated by `contAIned init`.
All generated content lives here so the init logic stays clean.
"""

SETTINGS_JSON = """\
{{
  "permissions": {{
    "allow": [
      "Read({workspace}/**)",
      "Glob({workspace}/**)",
      "Grep({workspace}/**)"
    ]
  }},
  "hooks": {{
    "PreToolUse": [
      {{
        "matcher": "Read|Glob|Grep",
        "hooks": [
          {{
            "type": "command",
            "command": "python3 .contAIned/hooks/restrict_reads.py"
          }}
        ]
      }},
      {{
        "matcher": "Write|Edit|MultiEdit",
        "hooks": [
          {{
            "type": "command",
            "command": "python3 .contAIned/hooks/restrict_writes.py"
          }},
          {{
            "type": "command",
            "command": "python3 .contAIned/hooks/tracer_pre.py"
          }}
        ]
      }},
      {{
        "matcher": "Bash",
        "hooks": [
          {{
            "type": "command",
            "command": "python3 .contAIned/hooks/restrict_bash.py"
          }}
        ]
      }}
    ],
    "PostToolUse": [
      {{
        "matcher": "Write|Edit|MultiEdit",
        "hooks": [
          {{
            "type": "command",
            "command": "python3 .contAIned/hooks/tracer_post.py"
          }}
        ]
      }},
      {{
        "matcher": "*",
        "hooks": [
          {{
            "type": "command",
            "command": "python3 .contAIned/hooks/audit.py"
          }}
        ]
      }}
    ],
    "SubagentStart": [
      {{
        "hooks": [
          {{
            "type": "command",
            "command": "python3 .contAIned/hooks/subagent_start.py"
          }}
        ]
      }}
    ],
    "SubagentStop": [
      {{
        "hooks": [
          {{
            "type": "command",
            "command": "python3 .contAIned/hooks/subagent_stop.py"
          }}
        ]
      }}
    ],
    "Stop": [
      {{
        "hooks": [
          {{
            "type": "command",
            "command": "python3 .contAIned/hooks/summarizer.py"
          }}
        ]
      }}
    ],
    "UserPromptSubmit": [
      {{
        "hooks": [
          {{
            "type": "command",
            "command": "python3 .contAIned/hooks/user_prompt_submit.py"
          }}
        ]
      }}
    ]
  }},
  "sandbox": {{
    "enabled": true,
    "filesystem": {{
      "denyWrite": [".contAIned"]
    }}
  }},
  "statusLine": {{
    "type": "command",
    "command": "python3 /workspace/.claude/statusline.py"
  }}
}}
"""

STATUSLINE_PY = '''\
#!/usr/bin/env python3
"""
contAIned status line — git branch, diff stat, session cost, context %.

Installed by `contAIned init` to .claude/statusline.py and wired into
Claude Code via the statusLine setting in .claude/settings.json.
Claude Code pipes a JSON object on stdin on every update; this script
reads it and prints a single formatted line to stdout.
"""
import json
import subprocess
import sys

# ── ANSI helpers ─────────────────────────────────────────────────────────────
_RESET  = "\\033[0m"
_GREEN  = "\\033[32m"
_RED    = "\\033[31m"

# Foreground colours
_FG_BLACK = "\\033[30m"
_FG_WHITE = "\\033[97m"

# Background colours
_BG_WHITE  = "\\033[107m"
_BG_GREEN  = "\\033[42m"
_BG_ORANGE = "\\033[43m"   # standard yellow — renders as amber/orange
_BG_RED    = "\\033[41m"


def _git(cwd: str, *args: str) -> str:
    """Run a git command in *cwd*; return stdout or empty string on error."""
    try:
        return subprocess.check_output(
            ["git", "-C", cwd, *args],
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
    except Exception:
        return ""


def main() -> None:
    try:
        data = json.load(sys.stdin)
    except Exception:
        return

    contained_part = f"{_GREEN} [✦]{_RESET}"

    cwd = data.get("cwd") or ""

    # ── Git branch + uncommitted diff stat ───────────────────────────────────
    git_part = ""
    if cwd and _git(cwd, "rev-parse", "--git-dir"):
        branch = _git(cwd, "branch", "--show-current") or _git(cwd, "rev-parse", "--short", "HEAD")
        shortstat = _git(cwd, "diff", "--shortstat", "HEAD")
        ins = del_ = 0
        for token in shortstat.split(","):
            token = token.strip()
            if "insertion" in token:
                ins = int(token.split()[0])
            elif "deletion" in token:
                del_ = int(token.split()[0])

        # Branch badge: nerd-font branch icon + name on white bg / black fg
        branch_badge = f"{_BG_WHITE}{_FG_BLACK} ⎇ {branch} {_RESET}"
        git_part = branch_badge

        if ins or del_:
            ins_str = f"{_GREEN}+{ins}{_RESET}"
            del_str = f"{_RED}-{del_}{_RESET}"
            git_part += f"  {ins_str} {del_str}"

    # ── Session cost ─────────────────────────────────────────────────────────
    cost_part = ""
    cost = (data.get("cost") or {}).get("total_cost_usd")
    if cost is not None:
        cost_part = f"${cost:.4f}"

    # ── Context window usage ─────────────────────────────────────────────────
    ctx_part = ""
    ctx = (data.get("context_window") or {}).get("used_percentage")
    if ctx is not None:
        if ctx <= 50:
            bg, fg = _BG_GREEN, _FG_BLACK
        elif ctx <= 80:
            bg, fg = _BG_ORANGE, _FG_BLACK
        else:
            bg, fg = _BG_RED, _FG_WHITE
        ctx_part = f"{bg}{fg} ctx {ctx}% {_RESET}"

    parts = [p for p in (contained_part, git_part, cost_part, ctx_part) if p]
    if parts:
        print("  │  ".join(parts))


if __name__ == "__main__":
    main()
'''

POLICY_MANIFEST = """\
# contAIned policy manifest
#
# Two sections:
#   1. runtime — Docker container resource settings.
#   2. policy  — enforcement settings read by the hook scripts.
#   3. agent   — model selection passed to the claude CLI.
#
# Action values accepted by policy settings:
#   block    — deny the operation outright; agent receives a clear reason
#   allow    — permit unconditionally
#   escalate — pass through to the SDK's canUseTool callback for operator approval
#
# Note: writes to .contAIned/ are always denied regardless of policy settings —
# control-plane protection is hardcoded and not configurable.

# ── Runtime ───────────────────────────────────────────────────────────────────
# Docker resource limits. Set by `contAIned init`. Require container restart to apply.
runtime:
  docker:
    image: contained:latest
    memory: 2g
    cpus: 2
    network: contAIned-net
    agent_config_volume: contAIned-agent-config

policy:

  # ── Secret-file protection ──────────────────────────────────────────────────
  secrets:
    reads:         block    # Read / Glob / Grep on secret files
    writes:        block    # Write / Edit / MultiEdit on secret files
    bash_reads:    block    # cat / head / tail / etc. targeting secret files
    safe_variants: allow    # .env.example / .env.sample / .env.template exemption

  # ── Bash command restrictions ────────────────────────────────────────────────
  bash:
    destructive:          block     # rm / rm -rf
    privilege_escalation: block     # sudo
    network_exfiltration: block     # curl / wget / nc / ncat
    git_mutations:        escalate  # git push / push --force → operator approval required
    package_publish:      block     # npm publish / pip upload / twine upload

  # ── Audit logging ─────────────────────────────────────────────────────────────
  # Always enabled — cannot be disabled.
  audit:
    enabled: true
    jsonl_export: false  # set true to also write .contAIned/audit/pipeline.jsonl

  # ── QA gate (stop hook) ───────────────────────────────────────────────────────
  qa:
    syntax:             true   # py_compile
    lint:               true   # ruff check
    format:             true   # ruff format --check
    type:               true   # pyright
    test:               true   # pytest tests/
    coverage:           true   # pytest --cov --cov-fail-under (requires pytest-cov)
    coverage_threshold: 80     # minimum % line coverage when coverage is true

# ── Agent ─────────────────────────────────────────────────────────────────────
agent:
  # Model passed via --model to the claude CLI. Leave blank to use claude's default.
  model: claude-sonnet-4-6
    budget_tokens: 1024

# ── Sandbox ───────────────────────────────────────────────────────────────────
# Claude Code's built-in OS-level sandbox (Seatbelt on macOS, bubblewrap on
# Linux).  Complements contAIned's PreToolUse hooks: the sandbox blocks subprocess
# writes (shell scripts, Python files run via Bash, build tools, etc.) while
# contAIned hooks block Claude's own Write/Edit SDK tool calls.  Both layers are
# needed — neither alone is sufficient.
#
# This section is read by `contAIned init` and written into .claude/settings.json.
# Changes here take effect after re-running `contAIned init` (or editing
# .claude/settings.json directly).
sandbox:
  enabled: true
  filesystem:
    denyWrite:
      - .contAIned   # protect the control-plane directory from subprocess writes
"""

POLICY_LOADER_HOOK = '''\
#!/usr/bin/env python3
"""Shared policy loader for contAIned hooks.

Reads the policy: and runtime: sections from .contAIned/manifest.yaml and merges
them with built-in defaults so that every key is always present.  If the
manifest cannot be read for any reason the defaults are returned unchanged —
hooks degrade gracefully to the original hardcoded behaviour.

Manifest location:
  Primary:   .contAIned/manifest.yaml          (new path, written by contAIned init)
  Fallback:  .contAIned/policy/manifest.yaml   (legacy path — compatibility shim)

Action values: "block" | "allow" | "escalate"
  block    — deny the operation; hook exits 2 with a reason on stderr
  allow    — permit unconditionally
  escalate — pass through (exit 0); the SDK\'s canUseTool callback decides
"""
from pathlib import Path

_DEFAULTS = {
    "secrets": {
        "reads":         "block",
        "writes":        "block",
        "bash_reads":    "block",
        "safe_variants": "allow",
    },
    "bash": {
        "destructive":          "block",
        "privilege_escalation": "block",
        "network_exfiltration": "block",
        "git_mutations":        "block",
        "package_publish":      "block",
    },
    "audit": {
        "enabled": True,
        "jsonl_export": False,
    },
    "qa": {
        "syntax":             True,
        "lint":               True,
        "format":             True,
        "type":               True,
        "test":               True,
        "coverage":           True,
        "coverage_threshold": 80,
    },
}


def _deep_merge(base, override):
    """Recursively merge *override* into *base*, returning a new dict."""
    result = dict(base)
    for key, val in override.items():
        if isinstance(val, dict) and isinstance(result.get(key), dict):
            result[key] = _deep_merge(result[key], val)
        else:
            result[key] = val
    return result


def _find_manifest(cwd="."):
    """Return the manifest Path, preferring the new location with fallback."""
    root = Path(cwd)
    new_path = root / ".contAIned" / "manifest.yaml"
    if new_path.exists():
        return new_path
    old_path = root / ".contAIned" / "policy" / "manifest.yaml"
    if old_path.exists():
        return old_path
    return new_path  # return new path even if missing — caller handles FileNotFoundError


def load_policy(cwd="."):
    """Return the fully-merged policy dict for the project rooted at *cwd*.

    Always succeeds: if the manifest is unreadable the built-in defaults
    are returned so hooks continue to enforce the current behaviour.
    """
    try:
        import yaml
        manifest_path = _find_manifest(cwd)
        with manifest_path.open() as fh:
            manifest = yaml.safe_load(fh) or {}
        return _deep_merge(_DEFAULTS, manifest.get("policy", {}))
    except Exception:
        return dict(_DEFAULTS)


'''

RESTRICT_WRITES_HOOK = '''\
#!/usr/bin/env python3
"""
PreToolUse hook — restricts Write, Edit, MultiEdit.

Two checks in order:
  1. Control-plane protection  — .contAIned/ writes are ALWAYS denied (not configurable)
  2. Secret file               — driven by policy.secrets.writes

Workspace boundary is enforced by the Docker container at the kernel level.

Exits 0 to allow, 2 to deny (reason on stderr fed back to agent).
Denials are written to the audit log before blocking.
"""
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _policy import load_policy  # noqa: E402


SECRET_FILE_PATTERNS = [
    re.compile(r\'(^|[/\\\\])\\.env(\\.[^/\\\\]+)?$\', re.IGNORECASE),
    re.compile(r\'\\.(pem|key|p12|pfx|jks|keystore)$\', re.IGNORECASE),
    re.compile(r\'(^|[/\\\\])id_(rsa|dsa|ecdsa|ed25519)$\', re.IGNORECASE),
    re.compile(r\'(^|[/\\\\])(credentials|secrets|service_account)\\.(json|yaml|yml)$\', re.IGNORECASE),
    re.compile(r\'\\.(secret|secrets)$\', re.IGNORECASE),
]
SAFE_VARIANT_RE = re.compile(r\'\\.(example|sample|template)\', re.IGNORECASE)


def is_secret_file(path):
    """Return True if path refers to a secret file that should not be written."""
    if SAFE_VARIANT_RE.search(Path(path).name):
        return False
    return any(pattern.search(path) for pattern in SECRET_FILE_PATTERNS)


def log_denial(event, target, reason):
    """Append a denial entry to the audit log. Never raises — audit must not block."""
    try:
        project_root = Path(event.get("cwd", "."))
        audit_log = project_root / ".contAIned" / "audit" / "pipeline.jsonl"
        audit_log.parent.mkdir(parents=True, exist_ok=True)
        entry = {
            "ts":         datetime.now(timezone.utc).isoformat(),
            "session_id": event.get("session_id"),
            "tool":       event.get("tool_name"),
            "input":      {"file_path": target},
            "outcome":    "denied",
            "reason":     reason,
        }
        with audit_log.open("a") as f:
            f.write(json.dumps(entry) + "\\n")
    except OSError:
        pass
    # Mirror denial into tracer.db so it is queryable alongside allowed events.
    try:
        from contained.tracer import contAInedTracer  # noqa: PLC0415
        _db = str(Path(event.get("cwd", ".")) / ".contAIned" / "tracer.db")
        contAInedTracer(_db).log_event(
            session_id=event.get("agent_id") or event.get("session_id"),
            tool=event.get("tool_name", ""),
            tool_input={"file_path": target},
            outcome="denied",
            reason=reason,
        )
    except Exception:
        pass


def enforce(action, event, target, msg):
    """Act on *action*: block exits 2; allow/escalate pass through."""
    if action == "block":
        log_denial(event, target, msg)
        print(msg, file=sys.stderr)
        sys.exit(2)


try:
    event = json.load(sys.stdin)
except json.JSONDecodeError:
    sys.exit(0)  # malformed input — pass through, don\'t block

tool       = event.get("tool_name", "")
tool_input = event.get("tool_input", {})

if tool not in ("Write", "Edit", "MultiEdit"):
    sys.exit(0)

target = tool_input.get("file_path", "")
if not target:
    sys.exit(0)

cwd          = event.get("cwd", ".")
policy       = load_policy(cwd)
project_root = Path(cwd).resolve()
contAIned_dir    = project_root / ".contAIned"
resolved     = Path(target).resolve()

# ── Check 1: inside .contAIned/ control-plane (always enforced, not configurable) ─
try:
    resolved.relative_to(contAIned_dir)
    log_denial(event, target, f"write into control-plane directory: {target}")
    print(
        f"Write denied: \\'{target}\\' is inside the .contAIned/ control-plane directory.\\n"
        "Hook and policy files are managed by contAIned and must not be edited directly.",
        file=sys.stderr,
    )
    sys.exit(2)
except ValueError:
    pass  # not inside .contAIned/ — continue

# ── Check 3: secret file ───────────────────────────────────────────────────────
if is_secret_file(str(resolved)):
    enforce(
        policy["secrets"]["writes"], event, target,
        f"Write denied: \\'{target}\\' looks like a secret file.\\n"
        "Writing to credentials, keys, and .env files is not permitted.",
    )

sys.exit(0)
'''

RESTRICT_READS_HOOK = '''\
#!/usr/bin/env python3
"""
PreToolUse hook — restricts Read, Glob, and Grep tool calls.

Checks are driven by the policy: section of .contAIned/manifest.yaml.
  policy.secrets.reads         — action for secret-file read attempts
  policy.secrets.safe_variants — action for .env.example / template variants

Workspace boundary is enforced by the Docker container at the kernel level.

Action values: block | allow | escalate
  block    — deny (exit 2, reason on stderr)
  allow    — permit unconditionally; skip the check
  escalate — pass through (exit 0); SDK\'s canUseTool callback decides

Exits 0 to allow, 2 to deny (reason on stderr fed back to agent).
Denials are written to the audit log before blocking.
"""
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _policy import load_policy  # noqa: E402


SECRET_FILE_PATTERNS = [
    re.compile(r\'(^|[/\\\\])\\.env(\\.[^/\\\\]+)?$\', re.IGNORECASE),
    re.compile(r\'\\.(pem|key|p12|pfx|jks|keystore)$\', re.IGNORECASE),
    re.compile(r\'(^|[/\\\\])id_(rsa|dsa|ecdsa|ed25519)$\', re.IGNORECASE),
    re.compile(r\'(^|[/\\\\])(credentials|secrets|service_account)\\.(json|yaml|yml)$\', re.IGNORECASE),
    re.compile(r\'\\.(secret|secrets)$\', re.IGNORECASE),
]
SAFE_VARIANT_RE = re.compile(r\'\\.(example|sample|template)\', re.IGNORECASE)


def matches_secret_pattern(path):
    """Return True if path matches a secret file pattern (ignoring safe-variant exception)."""
    return any(pattern.search(path) for pattern in SECRET_FILE_PATTERNS)


def is_safe_variant(path):
    """Return True if path looks like a safe template/example variant."""
    return bool(SAFE_VARIANT_RE.search(Path(path).name))


def log_denial(event, target, reason):
    """Append a denial entry to the audit log. Never raises."""
    try:
        project_root = Path(event.get("cwd", "."))
        audit_log = project_root / ".contAIned" / "audit" / "pipeline.jsonl"
        audit_log.parent.mkdir(parents=True, exist_ok=True)
        entry = {
            "ts":         datetime.now(timezone.utc).isoformat(),
            "session_id": event.get("session_id"),
            "tool":       event.get("tool_name"),
            "input":      {"target": target},
            "outcome":    "denied",
            "reason":     reason,
        }
        with audit_log.open("a") as f:
            f.write(json.dumps(entry) + "\\n")
    except OSError:
        pass
    # Mirror denial into tracer.db so it is queryable alongside allowed events.
    try:
        from contained.tracer import contAInedTracer  # noqa: PLC0415
        _db = str(Path(event.get("cwd", ".")) / ".contAIned" / "tracer.db")
        contAInedTracer(_db).log_event(
            session_id=event.get("agent_id") or event.get("session_id"),
            tool=event.get("tool_name", ""),
            tool_input={"file_path": target},
            outcome="denied",
            reason=reason,
        )
    except Exception:
        pass


def enforce(action, event, target, msg):
    """Act on *action*: block exits 2; allow/escalate pass through."""
    if action == "block":
        log_denial(event, target, msg)
        print(msg, file=sys.stderr)
        sys.exit(2)


try:
    event = json.load(sys.stdin)
except json.JSONDecodeError:
    sys.exit(0)

cwd        = event.get("cwd", ".")
policy     = load_policy(cwd)
tool       = event.get("tool_name", "")
tool_input = event.get("tool_input", {})

if tool == "Read":
    target = tool_input.get("file_path", "")
elif tool == "Grep":
    target = tool_input.get("path", "")
elif tool == "Glob":
    target = tool_input.get("pattern", "")
else:
    sys.exit(0)

if not target:
    sys.exit(0)

# ── Secret file (with safe-variant override) ──────────────────────────────────
if matches_secret_pattern(target):
    if is_safe_variant(target):
        enforce(
            policy["secrets"]["safe_variants"], event, target,
            f"Access denied: \\'{target}\\' is a secret file "
            "(safe-variant exemption is disabled by policy).",
        )
    else:
        enforce(
            policy["secrets"]["reads"], event, target,
            "Access denied: secret files (credentials, keys, .env) may not be read. "
            "Only example/sample/template variants (e.g. .env.example) are permitted.",
        )

sys.exit(0)
'''

RESTRICT_BASH_HOOK = '''\
#!/usr/bin/env python3
"""
PreToolUse hook — restricts Bash tool calls.

All checks are driven by the policy: section of .contAIned/policy/manifest.yaml.

Checks applied in order:
  1. policy.secrets.bash_reads        — read cmds (cat, head, ...) on secret files
  2. policy.bash.destructive          — rm / rm -rf
  3. policy.bash.privilege_escalation — sudo
  4. policy.bash.network_exfiltration — curl / wget / nc / ncat
  5. policy.bash.git_mutations        — git commit / reset / rebase / merge / push
  6. policy.bash.package_publish      — npm publish / pip upload / twine upload

Workspace boundary is enforced by the Docker container at the kernel level.

Action values: block | allow | escalate
  block    — deny (exit 2, reason on stderr)
  allow    — permit unconditionally; skip the check
  escalate — pass through (exit 0); SDK\'s canUseTool callback decides

Exits 0 to allow, 2 to deny (reason on stderr fed back to agent).
Denials are written to the audit log before blocking.
"""
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _policy import load_policy  # noqa: E402


SECRET_FILE_PATTERNS = [
    re.compile(r\'(^|[/\\\\])\\.env(\\.[^/\\\\]+)?$\', re.IGNORECASE),
    re.compile(r\'\\.(pem|key|p12|pfx|jks|keystore)$\', re.IGNORECASE),
    re.compile(r\'(^|[/\\\\])id_(rsa|dsa|ecdsa|ed25519)$\', re.IGNORECASE),
    re.compile(r\'(^|[/\\\\])(credentials|secrets|service_account)\\.(json|yaml|yml)$\', re.IGNORECASE),
    re.compile(r\'\\.(secret|secrets)$\', re.IGNORECASE),
]
SAFE_VARIANT_RE = re.compile(r\'\\.(example|sample|template)\', re.IGNORECASE)
READ_CMD_RE     = re.compile(r\'^\\s*(cat|head|tail|less|more|bat|pg|view)\\s\', re.IGNORECASE)

# (policy key, compiled patterns, denial reason)
_BASH_RULES = [
    (
        "destructive",
        [re.compile(r\'^rm\\s\'), re.compile(r\'.*\\brm\\s+-rf\\b.*\')],
        "Destructive file deletion is not permitted.",
    ),
    (
        "privilege_escalation",
        [re.compile(r\'^sudo\\s\')],
        "Privilege escalation is not permitted.",
    ),
    (
        "network_exfiltration",
        [re.compile(r\'^(curl|wget|nc|ncat)\\s\')],
        "Outbound network calls from Bash are not permitted.",
    ),
    (
        "git_mutations",
        [re.compile(r\'^git\\s+(commit|reset|rebase|merge)\\b\'), re.compile(r\'^git\\s+push\\b\')],
        "Git mutations require explicit operator approval.",
    ),
    (
        "package_publish",
        [re.compile(r\'^(npm\\s+publish|pip\\s+upload|twine\\s+upload)\\b\')],
        "Package publishing requires explicit operator approval.",
    ),
]


def is_secret_file(path):
    """Return True if path refers to a secret file."""
    if SAFE_VARIANT_RE.search(Path(path).name):
        return False
    return any(pattern.search(path) for pattern in SECRET_FILE_PATTERNS)


def abs_path_tokens(command):
    """Extract tokens that resolve to absolute paths, including ~/... home-relative paths."""
    result = []
    for t in command.split():
        expanded = os.path.expanduser(t)
        if expanded.startswith("/") and len(expanded) > 1:
            result.append(expanded)
    return result


def log_denial(event, command, reason):
    try:
        project_root = Path(event.get("cwd", "."))
        audit_log = project_root / ".contAIned" / "audit" / "pipeline.jsonl"
        audit_log.parent.mkdir(parents=True, exist_ok=True)
        entry = {
            "ts":         datetime.now(timezone.utc).isoformat(),
            "session_id": event.get("session_id"),
            "tool":       event.get("tool_name"),
            "input":      {"command": command},
            "outcome":    "denied",
            "reason":     reason,
        }
        with audit_log.open("a") as f:
            f.write(json.dumps(entry) + "\\n")
    except OSError:
        pass
    # Mirror denial into tracer.db so it is queryable alongside allowed events.
    try:
        from contained.tracer import contAInedTracer  # noqa: PLC0415
        _db = str(Path(event.get("cwd", ".")) / ".contAIned" / "tracer.db")
        contAInedTracer(_db).log_event(
            session_id=event.get("agent_id") or event.get("session_id"),
            tool=event.get("tool_name", ""),
            tool_input={"command": command},
            outcome="denied",
            reason=reason,
        )
    except Exception:
        pass


def enforce(action, event, command, msg):
    """Act on *action*: block exits 2; allow/escalate pass through."""
    if action == "block":
        log_denial(event, command, msg)
        print(msg, file=sys.stderr)
        sys.exit(2)


try:
    event = json.load(sys.stdin)
except json.JSONDecodeError:
    sys.exit(0)

command = event.get("tool_input", {}).get("command", "")
if not command:
    sys.exit(0)

cwd    = event.get("cwd", ".")
policy = load_policy(cwd)

# ── Check 1: secret file reads ────────────────────────────────────────────────
if READ_CMD_RE.match(command):
    for token in command.split():
        if is_secret_file(token):
            enforce(
                policy["secrets"]["bash_reads"], event, command,
                f"Bash denied: \\'{token}\\' looks like a secret file.\\n"
                "Secret files (credentials, keys, .env) may not be read.",
            )

# ── Checks 2–6: bash command rules ────────────────────────────────────────────
for rule_key, patterns, reason in _BASH_RULES:
    action = policy["bash"][rule_key]
    if action == "allow":
        continue
    if any(pat.search(command) for pat in patterns):
        enforce(action, event, command, reason)

sys.exit(0)
'''

AUDIT_HOOK = '''\
#!/usr/bin/env python3
"""
PostToolUse hook — records a structured audit entry for every tool execution.

Primary store : tracer.db via contAInedTracer.log_event() (SQLite, concurrent-safe).
Optional mirror: .contAIned/audit/pipeline.jsonl, controlled by policy.audit.jsonl_export.

Logging is controlled by policy.audit.enabled in manifest.yaml.
This hook must never block execution (always exits 0).
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _policy import load_policy  # noqa: E402


try:
    event = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError):
    sys.exit(0)

cwd    = event.get("cwd", ".")
policy = load_policy(cwd)

if not policy["audit"]["enabled"]:
    sys.exit(0)

session_id    = event.get("session_id")
agent_id      = event.get("agent_id")
actor_id      = agent_id or session_id
tool          = event.get("tool_name", "")
tool_input    = event.get("tool_input") or {}
tool_response = event.get("tool_response") or {}

is_error = tool_response.get("is_error", False)
outcome  = "denied" if is_error else "success"

reason = None
if is_error:
    content = tool_response.get("content")
    if isinstance(content, list):
        reason = " ".join(
            block.get("text", "") for block in content if isinstance(block, dict)
        ).strip() or None
    elif isinstance(content, str):
        reason = content or None

# ── Primary store: tracer.db ──────────────────────────────────────────────────
try:
    from contained.tracer import contAInedTracer  # noqa: PLC0415
    db_path = str(Path(cwd) / ".contAIned" / "tracer.db")
    tracer  = contAInedTracer(db_path)
    tracer.log_event(
        session_id    = actor_id,
        tool          = tool,
        tool_input    = tool_input,
        outcome       = outcome,
        reason        = reason,
        tool_response = tool_response,
    )
except Exception:
    pass  # never block execution due to logging failure

# ── Optional JSONL mirror ─────────────────────────────────────────────────────
if policy["audit"].get("jsonl_export", False):
    from datetime import datetime, timezone  # noqa: PLC0415
    entry = {
        "ts":         datetime.now(timezone.utc).isoformat(),
        "session_id": actor_id,
        "tool":       tool,
        "input":      tool_input,
        "outcome":    outcome,
    }
    if reason:
        entry["reason"] = reason
    try:
        audit_log = Path(cwd) / ".contAIned" / "audit" / "pipeline.jsonl"
        audit_log.parent.mkdir(parents=True, exist_ok=True)
        with audit_log.open("a") as f:
            f.write(json.dumps(entry) + "\\n")
    except OSError:
        pass

sys.exit(0)
'''

QA_HOOK = '''\
#!/usr/bin/env python3
"""
Stop hook — runs QA checks when the agent signals it is done.

Which checks run is controlled by policy.qa.* flags in manifest.yaml:
  syntax      — py_compile on all Python files
  lint        — ruff check
  format      — ruff format --check
  type        — pyright
  test        — pytest tests/  (skipped silently if no tests/ directory exists)
  coverage    — pytest tests/ --cov --cov-fail-under=<threshold>
                requires pytest-cov; skipped silently if not installed
                threshold is policy.qa.coverage_threshold (default 80)

If all enabled checks pass  → exits 0, agent stops cleanly.
If any enabled check fails  → prints JSON with decision:block, agent receives feedback.
"""
import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _policy import load_policy  # noqa: E402

try:
    event = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError):
    event = {}

cwd      = event.get("cwd", ".")
TASK_DIR = Path(cwd).resolve()
policy   = load_policy(cwd)
qa       = policy["qa"]

# ── Skip QA if no Python source files were written this session ───────────────
_session_id = event.get("session_id")
if _session_id:
    try:
        from contained.tracer import contAInedTracer
        _tracer = contAInedTracer(str(Path(cwd) / ".contAIned" / "tracer.db"))
        _touched = _tracer.list_touched_files(_session_id)
        if not any(f.endswith(".py") for f in _touched):
            sys.exit(0)
    except Exception:
        pass  # tracer unavailable — fall through and run checks normally


def run(cmd):
    result = subprocess.run(
        cmd,
        cwd=TASK_DIR,
        capture_output=True,
        text=True,
    )
    return result.returncode, result.stdout + result.stderr


# ── Ensure dev dependencies are installed (pytest, pytest-cov, etc.) ──────────
# Run uv sync --dev silently so that subsequent uv run calls can find pytest
# even if the venv is missing or stale.  Failures are non-fatal — if uv is not
# present the individual check steps will handle missing tools gracefully.
if (TASK_DIR / "pyproject.toml").exists() or (TASK_DIR / "uv.lock").exists():
    subprocess.run(
        ["uv", "sync", "--dev", "--quiet"],
        cwd=TASK_DIR,
        capture_output=True,
    )


def block(reason):
    """Tell the SDK to keep the agent running with this feedback."""
    print(json.dumps({"decision": "block", "reason": reason}))
    sys.exit(0)


# ── Collect Python files (skip generated/tool directories) ────────────────────
_SKIP_DIRS = {".venv", "__pycache__", ".git", "node_modules", ".contAIned"}
py_files = [
    f
    for f in TASK_DIR.rglob("**/*.py")
    if not _SKIP_DIRS.intersection(f.parts)
]

failures = []

# ── Syntax check ──────────────────────────────────────────────────────────────
if qa["syntax"]:
    for f in py_files:
        code, out = run(["uv", "run", "python", "-m", "py_compile", str(f)])
        if code != 0:
            failures.append({"check": "syntax", "file": str(f.relative_to(TASK_DIR)), "output": out})
    if failures:
        feedback = "QA failed — fix the following issues before finishing:\\n\\n"
        for item in failures:
            feedback += f"### {item[\'check\']} error in `{item[\'file\']}`\\n```\\n{item[\'output\']}\\n```\\n\\n"
        block(feedback)

# ── ruff check (linting) ──────────────────────────────────────────────────────
if qa["lint"] and py_files:
    try:
        code, out = run(["ruff", "check"] + [str(f) for f in py_files])
        if code != 0:
            failures.append({"check": "ruff check", "file": "python files", "output": out})
    except FileNotFoundError:
        print("ruff not installed — skipping ruff check", file=sys.stderr)

# ── ruff format --check ───────────────────────────────────────────────────────
if qa["format"] and py_files:
    try:
        code, out = run(["ruff", "format", "--check"] + [str(f) for f in py_files])
        if code != 0:
            failures.append({"check": "ruff format", "file": "python files", "output": out})
    except FileNotFoundError:
        print("ruff not installed — skipping ruff format --check", file=sys.stderr)

# ── pyright (type checking) ───────────────────────────────────────────────────
if qa["type"] and py_files:
    try:
        code, out = run(["pyright"])
        if code != 0:
            failures.append({"check": "pyright", "file": "python files", "output": out})
    except FileNotFoundError:
        print("pyright not installed — skipping type checks", file=sys.stderr)

# ── pytest (unit tests) ───────────────────────────────────────────────────────
if qa["test"]:
    tests_dir = TASK_DIR / "tests"
    if tests_dir.is_dir():
        code, out = run(["uv", "run", "pytest", str(tests_dir),
                         "-x", "--tb=short", "-q"])
        # Exit code 5 means pytest collected no tests — not a failure.
        if code not in (0, 5):
            failures.append({"check": "pytest", "file": "tests/", "output": out})

# ── pytest coverage ───────────────────────────────────────────────────────────
if qa["coverage"]:
    tests_dir = TASK_DIR / "tests"
    if tests_dir.is_dir():
        # Check that pytest-cov is available before attempting the run.
        probe_code, _ = run(["uv", "run", "python", "-c", "import pytest_cov"])
        if probe_code != 0:
            print("pytest-cov not installed — skipping coverage check", file=sys.stderr)
        else:
            threshold = int(qa.get("coverage_threshold", 80))
            code, out = run([
                "uv", "run", "pytest", str(tests_dir),
                "--cov", "--cov-report=term-missing",
                f"--cov-fail-under={threshold}",
                "-q",
            ])
            # Exit code 5 = no tests collected; treat as pass.
            if code not in (0, 5):
                failures.append({"check": f"coverage (threshold: {threshold}%)",
                                  "file": "tests/", "output": out})

if failures:
    feedback = "QA failed — fix the following issues before finishing:\\n\\n"
    for item in failures:
        feedback += f"### {item[\'check\']} error in `{item[\'file\']}`\\n```\\n{item[\'output\']}\\n```\\n\\n"
    block(feedback)

# All checks passed
sys.exit(0)
'''

CLAUDE_MD = """\
# contAIned Agent — Operating Instructions

You are a coding agent operating within a contAIned pipeline.

## Your environment

- **Policy** is enforced automatically by hooks before every tool call.
  You do not need to second-guess what is allowed — just attempt the operation.
  If it is not permitted, you will receive a clear denial message explaining why.

## Task format

Each task you receive will specify:
- A clear description of what to produce
- Acceptance criteria — what "done" looks like
- The source files you should read

## Rules

1. Always attempt tool calls as requested — policy is enforced automatically by hooks.
   If a call is denied you will receive a clear reason; read it and adapt your approach.
2. Do not retry a denied tool call with the same arguments.
3. When you believe the task is complete, stop. The QA hook will run automatically and
   will give you feedback if anything needs fixing.
4. Do not modify files in `.contAIned/` — these are control-plane files.

## Signals

- Tool denied + reason → read the reason, change approach
- QA feedback after stopping → fix the issues described, then stop again
"""

GITIGNORE_BLOCK = """
# contAIned — control plane
# The .contAIned/ directory contains hooks, policy, and audit logs managed by contAIned.
# Keep it out of version control.
.contAIned/
"""

GITIGNORE_TEMPLATE = """\
# ── OS ────────────────────────────────────────────────────────────────────────
.DS_Store
Thumbs.db
desktop.ini

# ── Editors ───────────────────────────────────────────────────────────────────
.idea/
.vscode/
*.swp
*.swo

# ── Python ────────────────────────────────────────────────────────────────────
__pycache__/
*.py[cod]
*.egg-info/
dist/
build/
.venv/
.env

# ── Node ──────────────────────────────────────────────────────────────────────
node_modules/

# ── contAIned — control plane ─────────────────────────────────────────────────────
# The .contAIned/ directory contains hooks, policy, and audit logs managed by contAIned.
# Keep it out of version control.
.contAIned/
"""

WORKSPACE_GITKEEP = ""  # empty — just creates the directory marker

# ── New Phase-2 hook templates ─────────────────────────────────────────────────

TRACER_PRE_HOOK = '''\
#!/usr/bin/env python3
"""
PreToolUse hook — captures file baselines before Write, Edit, or MultiEdit.

Runs after restrict_writes.py in the PreToolUse chain.  When restrict_writes.py
exits 2 (deny), the SDK aborts the chain and this hook never fires — no baseline
is recorded for denied writes.  This is correct behaviour.

Actor ID resolution:
  actor_id = agent_id or session_id   (agent_id present only for sub-agent calls)

This hook must never block writes (always exits 0).
"""
import json
import sys
from pathlib import Path

try:
    event = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError):
    sys.exit(0)

tool = event.get("tool_name", "")
if tool not in ("Write", "Edit", "MultiEdit"):
    sys.exit(0)

tool_input = event.get("tool_input") or {}
cwd        = event.get("cwd", ".")

# ── Actor ID resolution ────────────────────────────────────────────────────────
session_id = event.get("session_id")
agent_id   = event.get("agent_id")
actor_id   = agent_id or session_id

if not actor_id:
    sys.exit(0)

# ── Collect file paths ─────────────────────────────────────────────────────────
if tool == "MultiEdit":
    edits      = tool_input.get("edits") or []
    file_paths = list({e["file_path"] for e in edits if e.get("file_path")})
else:
    fp         = tool_input.get("file_path")
    file_paths = [fp] if fp else []

if not file_paths:
    sys.exit(0)

# ── Capture baselines ──────────────────────────────────────────────────────────
db_path = str(Path(cwd) / ".contAIned" / "tracer.db")

try:
    from contained.tracer import contAInedTracer  # noqa: PLC0415
    tracer = contAInedTracer(db_path)
    for file_path in file_paths:
        tracer.capture_baseline(actor_id, file_path)
except Exception:
    pass  # tracer must never block writes

sys.exit(0)
'''

TRACER_POST_HOOK = '''\
#!/usr/bin/env python3
"""
PostToolUse hook — records file snapshots after Write, Edit, or MultiEdit.

Reads each affected file from disk (not from tool_input) so the stored blob
always matches what is actually on disk.  Handles Write, Edit, and MultiEdit
uniformly by resolving file paths from tool_input.

Actor ID resolution:
  actor_id = agent_id or session_id

This hook must never block execution (always exits 0).
"""
import json
import sys
from pathlib import Path

try:
    event = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError):
    sys.exit(0)

tool = event.get("tool_name", "")
if tool not in ("Write", "Edit", "MultiEdit"):
    sys.exit(0)

tool_input    = event.get("tool_input") or {}
tool_response = event.get("tool_response") or {}
cwd           = event.get("cwd", ".")

# Skip if the write failed (is_error means the tool errored out)
if tool_response.get("is_error"):
    sys.exit(0)

# ── Actor ID resolution ────────────────────────────────────────────────────────
session_id = event.get("session_id")
agent_id   = event.get("agent_id")
actor_id   = agent_id or session_id

if not actor_id:
    sys.exit(0)

# ── Collect file paths ─────────────────────────────────────────────────────────
if tool == "MultiEdit":
    edits      = tool_input.get("edits") or []
    file_paths = list({e["file_path"] for e in edits if e.get("file_path")})
else:
    fp         = tool_input.get("file_path")
    file_paths = [fp] if fp else []

if not file_paths:
    sys.exit(0)

# ── Record snapshots ───────────────────────────────────────────────────────────
db_path = str(Path(cwd) / ".contAIned" / "tracer.db")

try:
    from contained.tracer import contAInedTracer  # noqa: PLC0415
    tracer = contAInedTracer(db_path)
    for file_path in file_paths:
        path = Path(file_path)
        if path.exists():
            content = path.read_bytes()
            tracer.track_write(actor_id, file_path, content)
except Exception:
    pass  # tracer must never block execution

sys.exit(0)
'''

SUBAGENT_START_HOOK = '''\
#!/usr/bin/env python3
"""
SubagentStart hook — registers a new sub-agent task in tracer.db.

Fires when a sub-agent is spawned via the Agent tool.  Records the sub-agent
as an open task, linked to the root session via parent_session_id.

Event fields used:
  agent_id   — the sub-agent\'s unique identifier  (actor for this task)
  session_id — always the root session\'s ID        (parent reference)

This hook must never block execution (always exits 0).
"""
import json
import sys
from pathlib import Path

try:
    event = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError):
    sys.exit(0)

cwd        = event.get("cwd", ".")
session_id = event.get("session_id")   # root session (parent)
agent_id   = event.get("agent_id")     # sub-agent being spawned

if not agent_id or not session_id:
    sys.exit(0)

# Derive a human-readable prompt from whatever context the event provides.
agent_type  = event.get("agent_type") or event.get("subagent_type") or "sub-agent"
description = event.get("description") or event.get("prompt") or ""
prompt = ("[" + agent_type + "] " + description).strip() if description else ("[" + agent_type + "]")

db_path = str(Path(cwd) / ".contAIned" / "tracer.db")

try:
    from contained.tracer import contAInedTracer  # noqa: PLC0415
    tracer = contAInedTracer(db_path)
    tracer.open_task(agent_id, prompt, parent_session_id=session_id)
except Exception:
    pass

sys.exit(0)
'''

SUBAGENT_STOP_HOOK = '''\
#!/usr/bin/env python3
"""
SubagentStop hook — marks a sub-agent task as closed in tracer.db.

Fires when a sub-agent finishes (successfully or otherwise).  Transitions the
sub-agent\'s task from open → closed so the root summarizer can proceed.

Event fields used:
  agent_id — the sub-agent that just finished

This hook must never block execution (always exits 0).
"""
import json
import sys
from pathlib import Path

try:
    event = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError):
    sys.exit(0)

cwd      = event.get("cwd", ".")
agent_id = event.get("agent_id")

if not agent_id:
    sys.exit(0)

db_path = str(Path(cwd) / ".contAIned" / "tracer.db")

try:
    from contained.tracer import contAInedTracer  # noqa: PLC0415
    tracer = contAInedTracer(db_path)
    tracer.set_task_status(agent_id, "closed")
except Exception:
    pass

sys.exit(0)
'''

SUMMARIZER_HOOK = '''\
#!/usr/bin/env python3
"""
Stop hook — runs QA checks, builds a diff summary, and presents it to the operator.

Fires only for root-agent Stop events (not SubagentStop — that is wired to
subagent_stop.py).  This is the sole Stop hook; it owns both QA and approval.

Flow:
  1. Run qa.py inline — if any check fails, block and return to agent immediately.
  2. Defensive child check: poll up to 3 × 200 ms for open sub-agent sessions.
  3. Compute per-file unified diffs across the whole agent tree.
  4. Build action log from recent audit events (Bash, Agent, denied calls).
  5. Store JSON summary in tasks.summary; set status = closed.
  6. Render rich-formatted summary to /dev/tty (bypasses the SDK\'s stderr pipe).
"""
import json
import subprocess
import sys
import time
from pathlib import Path

try:
    event = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError):
    event = {}

cwd        = event.get("cwd", ".")
session_id = event.get("session_id")

# A Stop event for a sub-agent carries agent_id; the summarizer only runs for
# the root session.  This guard is a safety net — the hook is registered for
# Stop only, not SubagentStop, so agent_id should never be present here.
if event.get("agent_id"):
    sys.exit(0)

if not session_id:
    sys.exit(0)

# ── Phase 1: QA checks ────────────────────────────────────────────────────────
# Run qa.py inline before building the summary or showing the approval UI.
# This guarantees QA always completes first regardless of whether the SDK
# executes Stop hooks sequentially or in parallel.
_qa_script = Path(cwd) / ".contAIned" / "hooks" / "qa.py"
if _qa_script.exists():
    try:
        _qa_proc = subprocess.run(
            [sys.executable, str(_qa_script)],
            input=json.dumps(event),
            capture_output=True,
            text=True,
            cwd=cwd,
        )
        if _qa_proc.stdout.strip():
            try:
                _qa_out = json.loads(_qa_proc.stdout.strip())
                if _qa_out.get("decision") == "block":
                    # QA failed — relay the block decision to the SDK; no UI shown.
                    print(_qa_proc.stdout, end="")
                    sys.exit(0)
            except json.JSONDecodeError:
                pass  # qa emitted non-JSON to stdout — fall through
    except Exception:
        pass  # qa unavailable — proceed to approval UI

db_path = str(Path(cwd) / ".contAIned" / "tracer.db")

# ── Import tracer ──────────────────────────────────────────────────────────────
try:
    from contained.tracer import contAInedTracer  # noqa: PLC0415
    tracer = contAInedTracer(db_path)
except Exception:
    # If the tracer is unavailable the agent should still be allowed to stop.
    sys.exit(0)

# ── Defensive child check ──────────────────────────────────────────────────────
# The SDK fires SubagentStop for all children before the root Stop, but under
# parallel sub-agent execution there may be a brief race.  Poll up to 3 times.
open_children = []
for _attempt in range(3):
    try:
        rows = tracer.conn.execute(
            "SELECT session_id FROM tasks WHERE parent_session_id = ? AND status = \'open\'",
            (session_id,),
        ).fetchall()
        open_children = [r[0] for r in rows]
    except Exception:
        open_children = []
    if not open_children:
        break
    time.sleep(0.2)

# ── Collect file diffs ─────────────────────────────────────────────────────────
try:
    touched_files = tracer.list_touched_files(session_id)
except Exception:
    touched_files = []

# ── Skip summary UI if nothing was written this session ───────────────────────
if not touched_files:
    try:
        tracer.set_task_status(session_id, "closed", summary={"file_changes": [], "action_log": []})
    except Exception:
        pass
    sys.exit(0)

# Build a lookup of write-tool audit events per file path (for reasons).
try:
    all_audit = tracer.recent_audit_events(session_id, limit=500)
    _write_events_by_file: dict = {}
    for _ev in reversed(all_audit):
        if _ev["tool"] in ("Write", "Edit", "MultiEdit") and _ev.get("input"):
            _fp = _ev["input"].get("file_path") or ""
            if _fp:
                _write_events_by_file.setdefault(_fp, []).append(_ev)
            # MultiEdit may touch multiple files
            for _mfp in (_ev["input"].get("file_paths") or []):
                _write_events_by_file.setdefault(_mfp, []).append(_ev)
except Exception:
    _write_events_by_file = {}

# Resolve session tree once for baseline lookups.
try:
    _tree_ids = tracer.tree_session_ids(session_id)
    _tree_placeholders = ",".join("?" * len(_tree_ids)) if _tree_ids else "\'__none__\'"
except Exception:
    _tree_ids = []
    _tree_placeholders = "\'__none__\'"

file_diffs: list[dict] = []
for file_path in touched_files:
    try:
        diff_text = tracer.diff_task(session_id, file_path)
        if not diff_text:
            continue
        lines_added   = sum(1 for ln in diff_text.splitlines() if ln.startswith("+") and not ln.startswith("+++"))
        lines_removed = sum(1 for ln in diff_text.splitlines() if ln.startswith("-") and not ln.startswith("---"))

        # Determine change type from the earliest baseline pre_hash.
        change_type = "modified"
        try:
            if _tree_ids:
                _bl = tracer.conn.execute(
                    f"SELECT pre_hash FROM baselines WHERE file_path = ? AND session_id IN ({_tree_placeholders}) ORDER BY captured_at ASC LIMIT 1",
                    [file_path, *_tree_ids],
                ).fetchone()
                if _bl is not None:
                    change_type = "new file" if _bl[0] is None else "modified"
        except Exception:
            pass

        # Build a short human-readable reason from write-tool events for this file.
        _file_write_evs = _write_events_by_file.get(file_path, [])
        if _file_write_evs:
            _tools_used = list(dict.fromkeys(e["tool"] for e in _file_write_evs))
            reason = ", ".join(t.lower() for t in _tools_used)
        else:
            reason = change_type

        file_diffs.append({
            "file_path":     file_path,
            "diff":          diff_text,
            "lines_added":   lines_added,
            "lines_removed": lines_removed,
            "change_type":   change_type,
            "reason":        reason,
        })
    except Exception:
        pass

# ── Build action log ───────────────────────────────────────────────────────────
try:
    raw_events = tracer.recent_audit_events(session_id, limit=200)
    action_log = [
        e for e in reversed(raw_events)
        if e["tool"] in ("Bash", "Agent") or e["outcome"] == "denied"
    ]
except Exception:
    action_log = []

# ── Look up task prompt ────────────────────────────────────────────────────────
try:
    row = tracer.conn.execute(
        "SELECT prompt, started_at FROM tasks WHERE session_id = ?", (session_id,)
    ).fetchone()
    task_prompt    = row[0] if row else "(unknown)"
    task_started   = row[1] if row else None
except Exception:
    task_prompt  = "(unknown)"
    task_started = None

# ── Assemble and store summary ─────────────────────────────────────────────────
summary = {
    "file_changes": [
        {
            "file_path":   d["file_path"],
            "lines_added": d["lines_added"],
            "lines_removed": d["lines_removed"],
            "change_type": d["change_type"],
            "reason":      d["reason"],
        }
        for d in file_diffs
    ],
    "action_log": action_log,
    "incomplete_children": open_children,
}

# ── Locate Claude Code transcript for this session ────────────────────────────
# Claude Code injects transcript_path directly into the hook event payload.
# Do NOT reconstruct this path from cwd: inside the container cwd resolves to
# /workspace, but Claude Code names the project directory using the host
# absolute path, so a reconstructed path would never match the real file.
_transcript_path = event.get("transcript_path", "") or ""

# ── Enrich action_log Bash entries with full stdout from transcript ────────────
# The transcript holds untruncated tool outputs; the audit_events table has only
# the first 500 chars.  We merge in-memory so the stored summary is richer.
if _transcript_path and Path(_transcript_path).exists():
    try:
        from contained.tracer import extract_tool_outputs_from_transcript  # noqa: PLC0415
        _tool_outputs = extract_tool_outputs_from_transcript(_transcript_path)
        # Build per-command output lists (same command may be run multiple times).
        _bash_outputs: dict = {}
        for _to in _tool_outputs:
            if _to["tool_name"] == "Bash":
                _cmd = (_to["input"].get("command") or "").strip()
                if _cmd:
                    _bash_outputs.setdefault(_cmd, []).append({
                        "output":    _to["output"],
                        "exit_code": _to["exit_code"],
                    })
        # Enrich action_log entries in-place (mutates the in-memory list only).
        _bash_use_counts: dict = {}
        for _entry in action_log:
            if _entry.get("tool") == "Bash":
                _cmd = ((_entry.get("input") or {}).get("command") or "").strip()
                _idx = _bash_use_counts.get(_cmd, 0)
                _bash_use_counts[_cmd] = _idx + 1
                _avail = _bash_outputs.get(_cmd, [])
                if _idx < len(_avail):
                    _full = _avail[_idx]
                    _entry.setdefault("input", {})
                    _entry["input"]["stdout"] = _full["output"][:10240]  # cap at 10 KB
                    if _full["exit_code"] is not None:
                        _entry["input"]["exit_code"] = _full["exit_code"]
    except Exception:
        pass

# Rebuild summary with enriched action_log.
summary["action_log"] = action_log

# ── Extract structured narrative from transcript ──────────────────────────────
# Collects thinking blocks + pre-tool reasoning + closing statement in one pass.
_narrative_data: dict = {}
if _transcript_path and Path(_transcript_path).exists():
    try:
        from contained.tracer import extract_session_narrative  # noqa: PLC0415
        _narrative_data = extract_session_narrative(_transcript_path) or {}
    except Exception:
        pass

_narrative_json = json.dumps(_narrative_data) if _narrative_data else None

try:
    tracer.set_task_status(session_id, "closed", summary=summary, narrative=_narrative_json)
except Exception:
    pass

# ── Render summary to terminal ─────────────────────────────────────────────────
# Write directly to /dev/tty so the approval UI is always visible even when the
# SDK captures the hook\'s stderr (which it typically does for hook-result parsing).
try:
    _tty_w = open("/dev/tty", "w")
except OSError:
    _tty_w = sys.stderr  # fallback for CI / non-interactive environments

try:
    from rich.console import Console  # noqa: PLC0415
    from rich.panel   import Panel    # noqa: PLC0415
    from rich.text    import Text     # noqa: PLC0415

    con = Console(file=_tty_w, highlight=False)

    # Header
    started_str = ""
    if task_started:
        from datetime import datetime, timezone  # noqa: PLC0415
        dt = datetime.fromtimestamp(task_started / 1000, tz=timezone.utc)
        started_str = "  started " + dt.strftime("%Y-%m-%d %H:%M UTC")

    # header = Text()
    # header.append("Task Review", style="bold white")
    # header.append("\\n")
    # header.append(task_prompt[:120], style="dim")
    # if started_str:
    #     header.append("\\n" + started_str, style="dim")
    # if open_children:
    #     header.append("\\n[!] " + str(len(open_children)) + " sub-agent(s) still open — diffs may be incomplete", style="yellow")
    # con.print(Panel(header, border_style="blue", expand=False))

    # ── File Changes — git-status-like format ──────────────────────────────────
    if file_diffs:
        con.print("\\n[bold] Changes[/bold]  [dim](" + str(len(file_diffs)) + " file(s))[/dim]\\n")

        # Status letter mapping
        _STATUS_LABEL = {"new file": "A", "modified": "M", "deleted": "D"}
        _STATUS_STYLE = {"new file": "green", "modified": "yellow", "deleted": "red"}

        for fd in file_diffs:
            ct    = fd.get("change_type", "modified")
            label = _STATUS_LABEL.get(ct, "M")
            style = _STATUS_STYLE.get(ct, "yellow")
            stat_str = (
                "[green]+" + str(fd["lines_added"]) + "[/green]"
                "  [red]-" + str(fd["lines_removed"]) + "[/red]"
            )
            reason_str = fd.get("reason", "")
            # Print the status line: "  M  path/to/file  +N -N  (reason)"
            status_line = (
                "  [" + style + "][bold]" + label + "[/bold][/" + style + "]"
                "  [bold cyan]" + fd["file_path"] + "[/bold cyan]"
                "  " + stat_str
            )
            if reason_str and reason_str != ct:
                status_line += "  [dim](" + reason_str + ")[/dim]"
            con.print(status_line)

    else:
        con.print("\\n[dim] No file changes recorded.[/dim]\\n")

    # ── Task Completion ────────────────────────────────────────────────────────
    if file_diffs:
        _new_files  = [fd for fd in file_diffs if fd.get("change_type") == "new file"]
        _mod_files  = [fd for fd in file_diffs if fd.get("change_type") == "modified"]
        _del_files  = [fd for fd in file_diffs if fd.get("change_type") == "deleted"]
        _parts = []
        if _new_files:
            _parts.append(str(len(_new_files)) + " file(s) created")
        if _mod_files:
            _parts.append(str(len(_mod_files)) + " file(s) modified")
        if _del_files:
            _parts.append(str(len(_del_files)) + " file(s) deleted")
        _total_added   = sum(fd["lines_added"]   for fd in file_diffs)
        _total_removed = sum(fd["lines_removed"] for fd in file_diffs)
        _change_summary = ", ".join(_parts) if _parts else str(len(file_diffs)) + " file(s) changed"
        con.print("[bold] Task Completion[/bold]\\n")
        con.print(
            "  The task [dim]\\"" + task_prompt[:80] + "\\"[/dim] is complete.\\n"
            "  [green]" + _change_summary + "[/green]  "
            "([green]+" + str(_total_added) + "[/green] / [red]-" + str(_total_removed) + "[/red] lines total).\\n"
        )
        if _new_files:
            con.print("  [bold]New files:[/bold]")
            for fd in _new_files:
                con.print("    [green]" + fd["file_path"] + "[/green]")
        if _mod_files:
            con.print("  [bold]Modified:[/bold]")
            for fd in _mod_files:
                con.print("    [yellow]" + fd["file_path"] + "[/yellow]  [dim](" + fd.get("reason", "") + ")[/dim]")
        if _del_files:
            con.print("  [bold]Deleted:[/bold]")
            for fd in _del_files:
                con.print("    [red]" + fd["file_path"] + "[/red]")
        con.print("")

    # Action log
    if action_log:
        bash_count   = sum(1 for e in action_log if e["tool"] == "Bash")
        agent_count  = sum(1 for e in action_log if e["tool"] == "Agent")
        denied_count = sum(1 for e in action_log if e["outcome"] == "denied")
        parts = []
        if bash_count:
            parts.append(str(bash_count) + " bash")
        if agent_count:
            parts.append(str(agent_count) + " sub-agent")
        if denied_count:
            parts.append(str(denied_count) + " denied")
        con.print("[bold] Action Log[/bold]  [dim](" + ", ".join(parts) + ")[/dim]")

    con.print("")

except Exception:
    # Fall back to plain output if rich is unavailable.
    print("\\n=== Task Review: " + task_prompt[:80] + " ===", file=_tty_w, flush=True)
    print(str(len(file_diffs)) + " file(s) changed.", file=_tty_w)
    print("", file=_tty_w)

if _tty_w is not sys.stderr:
    _tty_w.close()
sys.exit(0)
'''

USER_PROMPT_SUBMIT_HOOK = '''\
#!/usr/bin/env python3
"""
UserPromptSubmit hook — intercepts hash commands before Claude processes them.

Commands handled here (output-only, non-interactive):
  #db [SQL]              — query tracer.db
  #status                — tail recent audit log
#update                — show current manifest policy
  #update <path>=<value> — set a manifest key by dot-path (e.g. policy.qa.lint=false)
  #review                — list recent completed tasks
  #review <n>            — show narrative + diff summary for task n

On match: output is printed to /dev/tty, hook exits 2 to block Claude.
On miss:  exit 0 — Claude\'s own /help, /compact, /clear, etc. pass through.
"""
import json
import subprocess
import sys
from pathlib import Path

try:
    event = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError):
    sys.exit(0)

prompt     = (event.get("prompt") or "").strip()
cwd        = event.get("cwd", ".")
session_id = event.get("session_id")
agent_id   = event.get("agent_id")

# ── Register root session on first prompt (idempotent) ────────────────────────
if session_id and not agent_id and not prompt.startswith("#"):
    db_path = Path(cwd) / ".contAIned" / "tracer.db"
    if db_path.exists():
        try:
            from contained.tracer import contAInedTracer  # noqa: PLC0415
            contAInedTracer(str(db_path)).open_task(session_id, prompt)
        except Exception:
            pass

if not prompt.startswith("#"):
    sys.exit(0)

parts    = prompt.split(None, 1)
cmd_word = parts[0].lower()
args     = parts[1].strip() if len(parts) > 1 else ""

_HOOK_COMMANDS = frozenset({"#db", "#status", "#update", "#review"})

if cmd_word not in _HOOK_COMMANDS:
    sys.exit(0)  # not a known hash command — pass through to Claude

# ── Open /dev/tty for output ──────────────────────────────────────────────────
try:
    _tty = open("/dev/tty", "w")
except OSError:
    _tty = sys.stderr

try:
    from rich.console import Console as _Con
    con = _Con(file=_tty, highlight=False)
except Exception:
    con = None


def _p(text="", **kw):
    if con:
        con.print(text, **kw)
    else:
        print(text, file=_tty)


# ── #db ───────────────────────────────────────────────────────────────────────
if cmd_word == "#db":
    import sqlite3 as _sl
    db_path = Path(cwd) / ".contAIned" / "tracer.db"
    if not db_path.exists():
        _p("[red]No tracer.db found.[/red] Run [bold]contAIned init[/bold] first.")
    else:
        query = args or (
            "SELECT session_id, status, "
            "datetime(started_at/1000,\'unixepoch\') AS started, "
            "substr(prompt,1,60) AS prompt "
            "FROM tasks WHERE parent_session_id IS NULL "
            "ORDER BY started_at DESC LIMIT 10"
        )
        conn = _sl.connect(str(db_path))
        conn.row_factory = _sl.Row
        try:
            rows = conn.execute(query).fetchall()
        except _sl.Error as exc:
            _p(f"[red]SQL error:[/red] {exc}")
            rows = []
        finally:
            conn.close()
        if rows and con:
            from rich.table import Table as _Table
            table = _Table(show_header=True, header_style="bold cyan", box=None)
            for col in rows[0].keys():
                table.add_column(col)
            for row in rows:
                table.add_row(*[str(v) if v is not None else "" for v in row])
            con.print(table)
        elif rows:
            for row in rows:
                print(dict(row), file=_tty)
        else:
            _p("[dim]No rows.[/dim]")

# ── #status ───────────────────────────────────────────────────────────────────
elif cmd_word == "#status":
    import sqlite3 as _sl
    db_path = Path(cwd) / ".contAIned" / "tracer.db"
    if not db_path.exists():
        _p("[red]No tracer.db found.[/red] Run [bold]contAIned init[/bold] first.")
    else:
        conn = _sl.connect(str(db_path))
        conn.row_factory = _sl.Row
        try:
            rows = conn.execute(
                "SELECT ts, substr(session_id,1,8) AS session, tool, outcome "
                "FROM audit_events ORDER BY ts DESC LIMIT 20"
            ).fetchall()
        except _sl.Error:
            rows = []
        finally:
            conn.close()
        if rows and con:
            from rich.table import Table as _Table
            table = _Table(
                show_header=True, header_style="bold cyan", box=None,
                title="Audit log — last 20 entries (newest first)",
            )
            for col in rows[0].keys():
                table.add_column(col)
            for row in rows:
                table.add_row(*[str(v) if v is not None else "" for v in row])
            con.print(table)
        elif rows:
            for row in rows:
                print(dict(row), file=_tty)
        else:
            _p("[dim]No audit events yet.[/dim]")

# ── #update ───────────────────────────────────────────────────────────────────
elif cmd_word == "#update":
    import yaml as _yaml
    _manifest_path = Path(cwd) / ".contAIned" / "manifest.yaml"

    if not _manifest_path.exists():
        _p("[red]No manifest.yaml found.[/red] Run [bold]contAIned init[/bold] first.")
    elif not args:
        # Display current manifest
        _manifest_text = _manifest_path.read_text()
        try:
            from rich.syntax import Syntax as _Syn
            con.print(_Syn(_manifest_text, "yaml", theme="monokai", line_numbers=False))
        except Exception:
            _p(_manifest_text)
    else:
        # Parse "dotpath=value" or "dotpath: value"
        if "=" in args:
            _dotpath, _, _raw_val = args.partition("=")
        elif ": " in args:
            _dotpath, _, _raw_val = args.partition(": ")
        else:
            _p("[red]Usage:[/red] #update <path>=<value>")
            _p("[dim]Example: [bold]#update policy.qa.lint=false[/bold][/dim]")
            _p("[dim]Run [bold]#update[/bold] with no arguments to see the current manifest.[/dim]")
            _dotpath = None

        if _dotpath is not None:
            _dotpath  = _dotpath.strip()
            _raw_val  = _raw_val.strip()

            # Parse value — bool, int, float, or string
            if _raw_val.lower() == "true":
                _val = True
            elif _raw_val.lower() == "false":
                _val = False
            else:
                try:
                    _val = int(_raw_val)
                except ValueError:
                    try:
                        _val = float(_raw_val)
                    except ValueError:
                        _val = _raw_val

            # Load manifest
            try:
                _data = _yaml.safe_load(_manifest_path.read_text()) or {}
            except Exception as _e:
                _p(f"[red]Could not parse manifest.yaml:[/red] {_e}")
                _data = None

            if _data is not None:
                # Navigate to parent node
                _keys = _dotpath.split(".")
                _node = _data
                _ok   = True
                for _k in _keys[:-1]:
                    if not isinstance(_node, dict) or _k not in _node:
                        _ok = False
                        break
                    _node = _node[_k]

                _final = _keys[-1]
                if not _ok or not isinstance(_node, dict) or _final not in _node:
                    _p(f"[red]Unknown path:[/red] [bold]{_dotpath}[/bold]")
                    _p("[dim]Run [bold]#update[/bold] to see all available paths.[/dim]")
                else:
                    _old = _node[_final]
                    _node[_final] = _val
                    _manifest_path.write_text(
                        _yaml.dump(_data, default_flow_style=False, sort_keys=False, allow_unicode=True)
                    )
                    _p(f"[green]✓[/green] [bold]{_dotpath}[/bold]: [dim]{_old!r}[/dim] → [bold]{_val!r}[/bold]")
                    if _dotpath.startswith("runtime.docker."):
                        _p("[dim]  Note: Docker resource changes take effect on container restart.[/dim]")

# ── #review ───────────────────────────────────────────────────────────────────
elif cmd_word == "#review":
    db_path = Path(cwd) / ".contAIned" / "tracer.db"
    if not db_path.exists():
        _p("[red]No tracer.db found.[/red] Run [bold]contAIned init[/bold] first.")
    else:
        try:
            from contained.tracer import contAInedTracer as _ST
            _tr = _ST(str(db_path))
            _tasks = _tr.conn.execute(
                """
                SELECT session_id, prompt, started_at, ended_at, summary, narrative
                FROM tasks
                WHERE status = \'closed\'
                  AND parent_session_id IS NULL
                ORDER BY ended_at DESC
                LIMIT 20
                """
            ).fetchall()
            _tasks = [
                {
                    "session_id": r[0], "prompt": r[1],
                    "started_at": r[2], "ended_at": r[3],
                    "summary": json.loads(r[4]) if r[4] else None,
                    "narrative": json.loads(r[5]) if r[5] else None,
                }
                for r in _tasks
            ]
        except Exception as _e:
            _p(f"[red]Tracer error:[/red] {_e}")
            _tasks = []

        if not _tasks:
            _p("[dim]No completed tasks found.[/dim]")
        elif not args:
            # ── List recent completed tasks ────────────────────────────────
            _p(f"\\n[bold]Recent tasks ({len(_tasks)}):[/bold]\\n")
            for _i, _r in enumerate(_tasks, 1):
                from datetime import datetime as _dt, timezone as _tz
                _ts = _dt.fromtimestamp(_r["ended_at"] / 1000, tz=_tz.utc)
                _fc_count = len((_r.get("summary") or {}).get("file_changes", []))
                _has_narrative = bool((_r.get("narrative") or {}).get("closings"))
                _p(
                    f"  [bold]{_i}.[/bold] [dim]{_r[\'session_id\'][:12]}…[/dim]"
                    f"  \\"{_r[\'prompt\'][:60]}\\"  [dim]({_ts.strftime(\'%Y-%m-%d %H:%M\')})[/dim]"
                    + (f"  [dim]{_fc_count} file(s)[/dim]" if _fc_count else "")
                    + ("  [dim cyan]narrative[/dim cyan]" if _has_narrative else "")
                )
            _p(f"\\n[dim]Type [bold]#review <n>[/bold] to see details for a task.[/dim]")
        else:
            # ── Show task detail ───────────────────────────────────────────
            if not args.isdigit() or int(args) < 1:
                _p("[red]Usage:[/red] #review <number>  (run #review to see the list)")
            else:
                _idx = int(args) - 1
                if _idx >= len(_tasks):
                    _p(f"[red]No task {args}.[/red] Type [bold]#review[/bold] to see the list.")
                else:
                    _r = _tasks[_idx]
                    from datetime import datetime as _dt, timezone as _tz
                    from rich.panel import Panel as _Panel
                    from rich.text import Text as _Text
                    _ts = _dt.fromtimestamp(_r["ended_at"] / 1000, tz=_tz.utc)
                    _hdr = _Text()
                    _hdr.append("Task", style="bold white")
                    _hdr.append(f"\\n{_r[\'prompt\'][:120]}", style="dim")
                    _hdr.append(f"\\n  completed {_ts.strftime(\'%Y-%m-%d %H:%M UTC\')}", style="dim")
                    con.print(_Panel(_hdr, border_style="blue", expand=False))

                    _narrative = _r.get("narrative") or {}
                    _closings  = _narrative.get("closings") or []
                    if _closings:
                        _p(f"\\n[bold] Narrative[/bold]\\n")
                        for _turn_i, _closing in enumerate(_closings, 1):
                            if len(_closings) > 1:
                                _p(f"  [dim]Turn {_turn_i}:[/dim]")
                            _p(f"  [dim]{_closing[:400]}[/dim]\\n")

                    _file_changes = (_r.get("summary") or {}).get("file_changes", [])
                    _action_log   = (_r.get("summary") or {}).get("action_log", [])

                    if _file_changes:
                        _p(f"\\n[bold] File Changes[/bold]  [dim]({len(_file_changes)} file(s))[/dim]\\n")
                        for _fc in _file_changes:
                            _fp  = _fc.get("file_path", "?")
                            _add = _fc.get("lines_added", 0)
                            _rem = _fc.get("lines_removed", 0)
                            _p(f"  [bold cyan]{_fp}[/bold cyan]  [green]+{_add}[/green]  [red]-{_rem}[/red]")
                            try:
                                _diff = _tr.diff_task(_r["session_id"], _fp)
                                _dlines = _diff.splitlines() if _diff else []
                            except Exception:
                                _dlines = []
                            if _dlines:
                                _dout = _Text()
                                for _ln in _dlines[:200]:
                                    if _ln.startswith("+++") or _ln.startswith("---"):
                                        _dout.append(_ln + "\\n", style="dim")
                                    elif _ln.startswith("@@"):
                                        _dout.append(_ln + "\\n", style="cyan")
                                    elif _ln.startswith("+"):
                                        _dout.append(_ln + "\\n", style="green")
                                    elif _ln.startswith("-"):
                                        _dout.append(_ln + "\\n", style="red")
                                    else:
                                        _dout.append(_ln + "\\n")
                                if len(_dlines) > 200:
                                    _dout.append("  … (diff truncated)\\n", style="dim")
                                con.print(_dout)
                    else:
                        _p("\\n[dim]  No file changes recorded.[/dim]\\n")

                    _notable = [
                        _e for _e in _action_log
                        if _e.get("tool") in ("Bash", "Agent") or _e.get("outcome") == "denied"
                    ]
                    if _notable:
                        _p(f"[bold] Action Log[/bold]  [dim]({len(_notable)} entries)[/dim]\\n")
                        for _e in _notable[-20:]:
                            _inp = _e.get("input") or {}
                            if _e.get("tool") == "Bash":
                                _cmd = (_inp.get("command") or "")[:80]
                                _ec  = _inp.get("exit_code")
                                _p(f"  ● bash: {_cmd}" + (f" (exit: {_ec})" if _ec is not None else ""))
                            elif _e.get("tool") == "Agent":
                                _p(f"  ● agent [{_inp.get(\'agent_type\') or \'agent\'}]: {(_inp.get(\'prompt_head\') or \'\')[:60]}")
                            elif _e.get("outcome") == "denied":
                                _p(f"  [red]✗ {_e.get(\'tool\')} denied: {(_e.get(\'reason\') or \'\')[:80]}[/red]")
                        _p()

print("\\n" * 5, file=_tty, end="")
if _tty is not sys.stderr:
    _tty.flush()
    _tty.close()

# Let tty output flush to the terminal before the block decision is rendered.
import time as _time
_time.sleep(0.5)

import json as _json
print(_json.dumps({"decision": "block", "reason": "Handled by contAIned"}))
sys.exit(0)
'''
