"""
Templates for files generated by `contAIned init`.
All generated content lives here so the init logic stays clean.
"""

# NOTE: .claude/settings.json is NOT written by contained init.
# All hook registration, sandbox rules, permissions, and statusLine are owned
# exclusively by /etc/claude-code/managed-settings.json, baked into the Docker
# image.  Claude Code merges hooks from all settings levels — any .claude/
# settings.json with a "hooks" key would cause every hook to fire twice.
# contained init retires any existing .claude/settings.json by renaming it
# to .claude/settings.json.bak.<timestamp>.

POLICY_MANIFEST = """\
# contAIned policy manifest
#
# Two sections:
#   1. runtime — Docker container resource settings.
#   2. policy  — enforcement settings read by the hook scripts.
#   3. agent   — model selection passed to the claude CLI.
#
# Action values accepted by policy settings:
#   block    — deny the operation outright; agent receives a clear reason
#   allow    — permit unconditionally
#   escalate — pass through to the SDK's canUseTool callback for operator approval
#
# Note: writes to .contAIned/ are always denied regardless of policy settings —
# control-plane protection is hardcoded and not configurable.

# ── Runtime ───────────────────────────────────────────────────────────────────
# Docker resource limits. Set by `contAIned init`. Require container restart to apply.
runtime:
  docker:
    image: contained:latest
    memory: 2g
    cpus: 2
    network: contAIned-net
    agent_config_volume: contAIned-agent-config

policy:

  # ── Secret-file protection ──────────────────────────────────────────────────
  secrets:
    reads:         block    # Read / Glob / Grep on secret files
    writes:        block    # Write / Edit / MultiEdit on secret files
    bash_reads:    block    # cat / head / tail / etc. targeting secret files
    safe_variants: allow    # .env.example / .env.sample / .env.template exemption

  # ── Bash command restrictions ────────────────────────────────────────────────
  bash:
    destructive:          block     # rm / rm -rf
    privilege_escalation: block     # sudo
    network_exfiltration: block     # curl / wget / nc / ncat
    package_publish:      block     # npm publish / pip upload / twine upload

  # ── Network policy ────────────────────────────────────────────────────────────
  # Controls outbound network access for both Claude Code tools and subprocesses.
  #
  # allowed_domains — domains that are silently permitted:
  #   - WebFetch / WebSearch: requests to these domains are auto-approved.
  #     Requests to any other domain surface an operator confirmation prompt and
  #     are logged as exceptions.
  #   - Bash subprocesses: HTTP traffic is routed through the Claude Code sandbox
  #     proxy; requests to non-allowed domains are blocked (HTTP 403).
  #
  # api.anthropic.com must remain in allowed_domains — the agent cannot function
  # without it.  Add project-specific domains (package registries, APIs) as needed.
  network:
    enabled: false
    allowed_domains:
      - api.anthropic.com    # required — Anthropic API
      - code.claude.com      # Claude Code telemetry / auth
      - docs.anthropic.com   # documentation lookups

  # ── Audit logging ─────────────────────────────────────────────────────────────
  # Always enabled — cannot be disabled.
  audit:
    enabled: true
    jsonl_export: false  # set true to also write .contAIned/audit/pipeline.jsonl

  # ── QA gate (stop hook) ───────────────────────────────────────────────────────
  qa:
    syntax:             true   # py_compile
    lint:               true   # ruff check
    format:             true   # ruff format --check
    type:               true   # pyright
    test:               true   # pytest tests/
    coverage:           true   # pytest --cov --cov-fail-under (requires pytest-cov)
    coverage_threshold: 80     # minimum % line coverage when coverage is true

  # ── MCP server approvals ──────────────────────────────────────────────────────
  # List of approved MCP server names.  Each entry generates an allow rule for
  # all tools from that server (mcp__<server>__*) in managed-settings.json.
  # Only servers listed here can be added when allowManagedMcpServersOnly is set.
  mcp:
    approved_servers: []   # e.g. [github, puppeteer]

  # ── Skill approvals ───────────────────────────────────────────────────────────
  # Explicit allowlist of skill names.  Each entry generates a Skill(<name>)
  # allow rule in managed-settings.json.  Unlisted skills surface an operator
  # confirmation prompt and are logged as exceptions.
  skills:
    approved_skills: []    # e.g. [commit, review-pr]

# ── Agent ─────────────────────────────────────────────────────────────────────
agent:
  # Model passed via --model to the claude CLI. Leave blank to use claude's default.
  model: claude-sonnet-4-6
    budget_tokens: 1024

# ── Sandbox ───────────────────────────────────────────────────────────────────
# Claude Code's built-in OS-level sandbox (Seatbelt on macOS, bubblewrap on
# Linux).  Complements contAIned's PreToolUse hooks: the sandbox blocks subprocess
# writes (shell scripts, Python files run via Bash, build tools, etc.) while
# contAIned hooks block Claude's own Write/Edit SDK tool calls.  Both layers are
# needed — neither alone is sufficient.
#
# This section is read by `contAIned init` and written into .claude/settings.json.
# Changes here take effect after re-running `contAIned init` (or editing
# .claude/settings.json directly).
sandbox:
  enabled: true
  filesystem:
    denyWrite:
      - .contAIned   # protect the control-plane directory from subprocess writes

# ── Sigstore provenance ────────────────────────────────────────────────────────
# When enabled, the Docker image is signed with Sigstore (cosign) during
# `contAIned init`.  Provenance is stored in .contAIned/provenance.yaml and
# verified on each session start.  Requires cosign to be installed.
sigstore:
  enabled: true
  rekor_url: https://rekor.sigstore.dev
  fulcio_url: https://fulcio.sigstore.dev
"""

POLICY_LOADER_HOOK = '''\
#!/usr/bin/env python3
"""Shared policy loader for contAIned hooks.

Reads the policy: section from /etc/contained/manifest.yaml (baked into the
container image by contAIned init) and merges it with built-in defaults so
that every key is always present.  If the manifest cannot be read the defaults
are returned unchanged — hooks degrade gracefully to the hardcoded behaviour.

Manifest location:
  /etc/contained/manifest.yaml  — baked into the image by contAIned init

Action values: "block" | "allow"
  block    — deny the operation; hook exits 2 with a reason on stderr
  allow    — permit unconditionally
"""
from pathlib import Path

_DEFAULTS = {
    "secrets": {
        "reads":         "block",
        "writes":        "block",
        "bash_reads":    "block",
        "safe_variants": "allow",
    },
    "bash": {
        "destructive":          "block",
        "privilege_escalation": "block",
        "network_exfiltration": "block",
        "package_publish":      "block",
    },
    "audit": {
        "enabled": True,
        "jsonl_export": False,
    },
    "qa": {
        "syntax":             True,
        "lint":               True,
        "format":             True,
        "type":               True,
        "test":               True,
        "coverage":           True,
        "coverage_threshold": 80,
    },
    "network": {
        "enabled":        False,
        "allowed_domains": [
            "api.anthropic.com",
            "code.claude.com",
            "docs.anthropic.com",
        ],
    },
    "mcp": {
        "approved_servers": [],
    },
    "skills": {
        "approved_skills": [],
    },
}


def _deep_merge(base, override):
    """Recursively merge *override* into *base*, returning a new dict."""
    result = dict(base)
    for key, val in override.items():
        if isinstance(val, dict) and isinstance(result.get(key), dict):
            result[key] = _deep_merge(result[key], val)
        else:
            result[key] = val
    return result


def load_policy(cwd="."):
    """Return the fully-merged policy dict.

    Always succeeds: if the manifest is unreadable the built-in defaults
    are returned so hooks continue to enforce the current behaviour.
    """
    try:
        import yaml
        manifest_path = Path("/etc/contained/manifest.yaml")
        with manifest_path.open() as fh:
            manifest = yaml.safe_load(fh) or {}
        return _deep_merge(_DEFAULTS, manifest.get("policy", {}))
    except Exception:
        return dict(_DEFAULTS)


'''

RESTRICT_WRITES_HOOK = '''\
#!/usr/bin/env python3
"""
PreToolUse hook — restricts Write, Edit, MultiEdit.

Checks in order:
  1. Control-plane protection  — .contAIned/ writes are ALWAYS denied (not configurable)
  2. Settings protection       — .claude/settings.json is ALWAYS denied (not configurable)
  3. Secret file               — driven by policy.secrets.writes

Workspace boundary is enforced by the Docker container at the kernel level.

Exits 0 to allow, 2 to deny (reason on stderr fed back to agent).
Denials are written to the audit log before blocking.
"""
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _policy import load_policy  # noqa: E402


SECRET_FILE_PATTERNS = [
    re.compile(r\'(^|[/\\\\])\\.env(\\.[^/\\\\]+)?$\', re.IGNORECASE),
    re.compile(r\'\\.(pem|key|p12|pfx|jks|keystore)$\', re.IGNORECASE),
    re.compile(r\'(^|[/\\\\])id_(rsa|dsa|ecdsa|ed25519)$\', re.IGNORECASE),
    re.compile(r\'(^|[/\\\\])(credentials|secrets|service_account)\\.(json|yaml|yml)$\', re.IGNORECASE),
    re.compile(r\'\\.(secret|secrets)$\', re.IGNORECASE),
]
SAFE_VARIANT_RE = re.compile(r\'\\.(example|sample|template)\', re.IGNORECASE)


def is_secret_file(path):
    """Return True if path refers to a secret file that should not be written."""
    if SAFE_VARIANT_RE.search(Path(path).name):
        return False
    return any(pattern.search(path) for pattern in SECRET_FILE_PATTERNS)


def log_denial(event, target, reason):
    """Append a denial entry to the audit log. Never raises — audit must not block."""
    try:
        project_root = Path(event.get("cwd", "."))
        audit_log = project_root / ".contAIned" / "audit" / "pipeline.jsonl"
        audit_log.parent.mkdir(parents=True, exist_ok=True)
        entry = {
            "ts":         datetime.now(timezone.utc).isoformat(),
            "session_id": event.get("session_id"),
            "tool":       event.get("tool_name"),
            "input":      {"file_path": target},
            "outcome":    "denied",
            "reason":     reason,
        }
        with audit_log.open("a") as f:
            f.write(json.dumps(entry) + "\\n")
    except OSError:
        pass
    # Mirror denial into tracer.db so it is queryable alongside allowed events.
    try:
        from contained.tracer import contAInedTracer  # noqa: PLC0415
        _db = str(Path(event.get("cwd", ".")) / ".contAIned" / "tracer.db")
        contAInedTracer(_db).log_event(
            session_id=event.get("agent_id") or event.get("session_id"),
            tool=event.get("tool_name", ""),
            tool_input={"file_path": target},
            outcome="denied",
            reason=reason,
        )
    except Exception:
        pass


def enforce(action, event, target, msg):
    """Act on *action*: block exits 2; allow/escalate pass through."""
    if action == "block":
        log_denial(event, target, msg)
        print(msg, file=sys.stderr)
        sys.exit(2)


try:
    event = json.load(sys.stdin)
except json.JSONDecodeError:
    sys.exit(0)  # malformed input — pass through, don\'t block

tool       = event.get("tool_name", "")
tool_input = event.get("tool_input", {})

if tool not in ("Write", "Edit", "MultiEdit"):
    sys.exit(0)

target = tool_input.get("file_path", "")
if not target:
    sys.exit(0)

cwd          = event.get("cwd", ".")
policy       = load_policy(cwd)
project_root = Path(cwd).resolve()
contAIned_dir    = project_root / ".contAIned"
resolved     = Path(target).resolve()

# ── Check 1: inside .contAIned/ control-plane (always enforced, not configurable) ─
try:
    resolved.relative_to(contAIned_dir)
    log_denial(event, target, f"write into control-plane directory: {target}")
    print(
        f"Write denied: \\'{target}\\' is inside the .contAIned/ control-plane directory.\\n"
        "Hook and policy files are managed by contAIned and must not be edited directly.",
        file=sys.stderr,
    )
    sys.exit(2)
except ValueError:
    pass  # not inside .contAIned/ — continue

# ── Check 2: .claude/settings.json — Claude Code hook registration file ───────
claude_settings = (project_root / ".claude" / "settings.json").resolve()
if resolved == claude_settings:
    log_denial(event, target, f"write to Claude Code settings file: {target}")
    print(
        f"Write denied: \\'{target}\\' is the Claude Code settings file.\\n"
        "Hook registration is managed by contAIned and must not be edited directly.",
        file=sys.stderr,
    )
    sys.exit(2)

# ── Check 3: secret file ───────────────────────────────────────────────────────
if is_secret_file(str(resolved)):
    enforce(
        policy["secrets"]["writes"], event, target,
        f"Write denied: \\'{target}\\' looks like a secret file.\\n"
        "Writing to credentials, keys, and .env files is not permitted.",
    )

sys.exit(0)
'''

RESTRICT_READS_HOOK = '''\
#!/usr/bin/env python3
"""
PreToolUse hook — restricts Read, Glob, and Grep tool calls.

Checks are driven by the policy: section of .contAIned/manifest.yaml.
  policy.secrets.reads         — action for secret-file read attempts
  policy.secrets.safe_variants — action for .env.example / template variants

Workspace boundary is enforced by the Docker container at the kernel level.

Action values: block | allow | escalate
  block    — deny (exit 2, reason on stderr)
  allow    — permit unconditionally; skip the check
  escalate — pass through (exit 0); SDK\'s canUseTool callback decides

Exits 0 to allow, 2 to deny (reason on stderr fed back to agent).
Denials are written to the audit log before blocking.
"""
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _policy import load_policy  # noqa: E402


SECRET_FILE_PATTERNS = [
    re.compile(r\'(^|[/\\\\])\\.env(\\.[^/\\\\]+)?$\', re.IGNORECASE),
    re.compile(r\'\\.(pem|key|p12|pfx|jks|keystore)$\', re.IGNORECASE),
    re.compile(r\'(^|[/\\\\])id_(rsa|dsa|ecdsa|ed25519)$\', re.IGNORECASE),
    re.compile(r\'(^|[/\\\\])(credentials|secrets|service_account)\\.(json|yaml|yml)$\', re.IGNORECASE),
    re.compile(r\'\\.(secret|secrets)$\', re.IGNORECASE),
]
SAFE_VARIANT_RE = re.compile(r\'\\.(example|sample|template)\', re.IGNORECASE)


def matches_secret_pattern(path):
    """Return True if path matches a secret file pattern (ignoring safe-variant exception)."""
    return any(pattern.search(path) for pattern in SECRET_FILE_PATTERNS)


def is_safe_variant(path):
    """Return True if path looks like a safe template/example variant."""
    return bool(SAFE_VARIANT_RE.search(Path(path).name))


def log_denial(event, target, reason):
    """Append a denial entry to the audit log. Never raises."""
    try:
        project_root = Path(event.get("cwd", "."))
        audit_log = project_root / ".contAIned" / "audit" / "pipeline.jsonl"
        audit_log.parent.mkdir(parents=True, exist_ok=True)
        entry = {
            "ts":         datetime.now(timezone.utc).isoformat(),
            "session_id": event.get("session_id"),
            "tool":       event.get("tool_name"),
            "input":      {"target": target},
            "outcome":    "denied",
            "reason":     reason,
        }
        with audit_log.open("a") as f:
            f.write(json.dumps(entry) + "\\n")
    except OSError:
        pass
    # Mirror denial into tracer.db so it is queryable alongside allowed events.
    try:
        from contained.tracer import contAInedTracer  # noqa: PLC0415
        _db = str(Path(event.get("cwd", ".")) / ".contAIned" / "tracer.db")
        contAInedTracer(_db).log_event(
            session_id=event.get("agent_id") or event.get("session_id"),
            tool=event.get("tool_name", ""),
            tool_input={"file_path": target},
            outcome="denied",
            reason=reason,
        )
    except Exception:
        pass


def enforce(action, event, target, msg):
    """Act on *action*: block exits 2; allow/escalate pass through."""
    if action == "block":
        log_denial(event, target, msg)
        print(msg, file=sys.stderr)
        sys.exit(2)


try:
    event = json.load(sys.stdin)
except json.JSONDecodeError:
    sys.exit(0)

cwd        = event.get("cwd", ".")
policy     = load_policy(cwd)
tool       = event.get("tool_name", "")
tool_input = event.get("tool_input", {})

if tool == "Read":
    target = tool_input.get("file_path", "")
elif tool == "Grep":
    target = tool_input.get("path", "")
elif tool == "Glob":
    target = tool_input.get("pattern", "")
else:
    sys.exit(0)

if not target:
    sys.exit(0)

# ── Secret file (with safe-variant override) ──────────────────────────────────
if matches_secret_pattern(target):
    if is_safe_variant(target):
        enforce(
            policy["secrets"]["safe_variants"], event, target,
            f"Access denied: \\'{target}\\' is a secret file "
            "(safe-variant exemption is disabled by policy).",
        )
    else:
        enforce(
            policy["secrets"]["reads"], event, target,
            "Access denied: secret files (credentials, keys, .env) may not be read. "
            "Only example/sample/template variants (e.g. .env.example) are permitted.",
        )

sys.exit(0)
'''

RESTRICT_BASH_HOOK = '''\
#!/usr/bin/env python3
"""
PreToolUse hook — restricts Bash tool calls.

All checks are driven by the policy: section of .contAIned/policy/manifest.yaml.

Checks applied in order:
  1. policy.secrets.bash_reads        — read cmds (cat, head, ...) on secret files
  2. policy.bash.destructive          — rm / rm -rf
  3. policy.bash.privilege_escalation — sudo
  4. policy.bash.network_exfiltration — curl / wget / nc / ncat
  5. policy.bash.package_publish      — npm publish / pip upload / twine upload

Safe read-only commands (git status/log/diff, ls, etc.) are auto-approved via
the managed-settings allow list and never reach this hook.  Side-effect commands
(git commit/push, etc.) are not in the allow list and fall through to the
permission system, which prompts the operator for approval.

For each command this hook outputs one of three JSON decisions:
  permissionDecision: "deny"  — blocked outright (secrets, destructive ops, etc.)
  permissionDecision: "allow" — safe read-only command (mirrors the allow list)
  permissionDecision: "ask"   — side-effect command; operator prompt fires

The "allow" and "ask" paths exist because a PreToolUse hook returning "ask"
overrides the managed-settings allow list.  Safe patterns are therefore matched
explicitly here so they are not accidentally caught by the "ask" fallback.
Keep _SAFE_PATTERNS in sync with the allow list in managed-settings.json.

Outputs JSON to stdout; denials also written to the audit log.
"""
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _policy import load_policy  # noqa: E402


SECRET_FILE_PATTERNS = [
    re.compile(r\'(^|[/\\\\])\\.env(\\.[^/\\\\]+)?$\', re.IGNORECASE),
    re.compile(r\'\\.(pem|key|p12|pfx|jks|keystore)$\', re.IGNORECASE),
    re.compile(r\'(^|[/\\\\])id_(rsa|dsa|ecdsa|ed25519)$\', re.IGNORECASE),
    re.compile(r\'(^|[/\\\\])(credentials|secrets|service_account)\\.(json|yaml|yml)$\', re.IGNORECASE),
    re.compile(r\'\\.(secret|secrets)$\', re.IGNORECASE),
]
SAFE_VARIANT_RE = re.compile(r\'\\.(example|sample|template)\', re.IGNORECASE)
READ_CMD_RE     = re.compile(r\'^\\s*(cat|head|tail|less|more|bat|pg|view)\\s\', re.IGNORECASE)

# Read-only commands that mirror the managed-settings allow list.
# Commands matching these patterns are auto-approved (permissionDecision: "allow").
# Keep in sync with the "allow" list in managed-settings.json.
_SAFE_PATTERNS = [
    re.compile(r\'^git\\s+status\\b\'),
    re.compile(r\'^git\\s+log\\b\'),
    re.compile(r\'^git\\s+diff\\b\'),
    re.compile(r\'^git\\s+show\\b\'),
    re.compile(r\'^git\\s+branch\\b\'),
    re.compile(r\'^git\\s+stash\\s+list\\b\'),
    re.compile(r\'^git\\s+remote\\b\'),
    re.compile(r\'^ls\\b\'),
    re.compile(r\'^pwd\\b\'),
    re.compile(r\'^echo\\s\'),
    re.compile(r\'^which\\s\'),
    # grep/rg via Bash are read-only — mirror the Grep tool\'s auto-approval.
    re.compile(r\'^grep\\b\'),
    re.compile(r\'^rg\\b\'),
]

# (policy key, compiled patterns, denial reason)
_BASH_RULES = [
    (
        "destructive",
        [re.compile(r\'^rm\\s\'), re.compile(r\'.*\\brm\\s+-rf\\b.*\')],
        "Destructive file deletion is not permitted.",
    ),
    (
        "privilege_escalation",
        [re.compile(r\'^sudo\\s\')],
        "Privilege escalation is not permitted.",
    ),
    (
        "network_exfiltration",
        [re.compile(r\'^(curl|wget|nc|ncat)\\s\')],
        "Outbound network calls from Bash are not permitted.",
    ),
    (
        "package_publish",
        [re.compile(r\'^(npm\\s+publish|pip\\s+upload|twine\\s+upload)\\b\')],
        "Package publishing requires explicit operator approval.",
    ),
]


def is_secret_file(path):
    """Return True if path refers to a secret file."""
    if SAFE_VARIANT_RE.search(Path(path).name):
        return False
    return any(pattern.search(path) for pattern in SECRET_FILE_PATTERNS)


def abs_path_tokens(command):
    """Extract tokens that resolve to absolute paths, including ~/... home-relative paths."""
    result = []
    for t in command.split():
        expanded = os.path.expanduser(t)
        if expanded.startswith("/") and len(expanded) > 1:
            result.append(expanded)
    return result


def log_denial(event, command, reason):
    try:
        project_root = Path(event.get("cwd", "."))
        audit_log = project_root / ".contAIned" / "audit" / "pipeline.jsonl"
        audit_log.parent.mkdir(parents=True, exist_ok=True)
        entry = {
            "ts":         datetime.now(timezone.utc).isoformat(),
            "session_id": event.get("session_id"),
            "tool":       event.get("tool_name"),
            "input":      {"command": command},
            "outcome":    "denied",
            "reason":     reason,
        }
        with audit_log.open("a") as f:
            f.write(json.dumps(entry) + "\\n")
    except OSError:
        pass
    # Mirror denial into tracer.db so it is queryable alongside allowed events.
    try:
        from contained.tracer import contAInedTracer  # noqa: PLC0415
        _db = str(Path(event.get("cwd", ".")) / ".contAIned" / "tracer.db")
        contAInedTracer(_db).log_event(
            session_id=event.get("agent_id") or event.get("session_id"),
            tool=event.get("tool_name", ""),
            tool_input={"command": command},
            outcome="denied",
            reason=reason,
        )
    except Exception:
        pass


def enforce(action, event, command, msg):
    """Block the tool call: log denial, output JSON deny decision, exit 2."""
    if action == "block":
        log_denial(event, command, msg)
        print(json.dumps({
            "hookSpecificOutput": {
                "hookEventName": "PreToolUse",
                "permissionDecision": "deny",
                "permissionDecisionReason": msg,
            }
        }))
        sys.exit(2)


def _ask():
    """Output a permissionDecision:ask response and exit 0."""
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "ask",
        }
    }))
    sys.exit(0)


try:
    event = json.load(sys.stdin)
except json.JSONDecodeError:
    _ask()

command = event.get("tool_input", {}).get("command", "")
if not command:
    _ask()

cwd    = event.get("cwd", ".")
policy = load_policy(cwd)

# ── Check 1: secret file reads ────────────────────────────────────────────────
if READ_CMD_RE.match(command):
    for token in command.split():
        if is_secret_file(token):
            enforce(
                policy["secrets"]["bash_reads"], event, command,
                f"Bash denied: \\'{token}\\' looks like a secret file.\\n"
                "Secret files (credentials, keys, .env) may not be read.",
            )

# ── Checks 2–5: bash command rules ────────────────────────────────────────────
for rule_key, patterns, reason in _BASH_RULES:
    action = policy["bash"][rule_key]
    if action == "allow":
        continue
    if any(pat.search(command) for pat in patterns):
        enforce(action, event, command, reason)

# ── Safe read-only commands (mirrors managed-settings allow list) ──────────────
if any(pat.match(command) for pat in _SAFE_PATTERNS):
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "allow",
        }
    }))
    sys.exit(0)

# Side-effect command — ask the operator for explicit approval.
_ask()
'''

AUDIT_HOOK = '''\
#!/usr/bin/env python3
"""
PostToolUse hook — records a structured audit entry for every tool execution.

Primary store : tracer.db via contAInedTracer.log_event() (SQLite, concurrent-safe).
Optional mirror: .contAIned/audit/pipeline.jsonl, controlled by policy.audit.jsonl_export.

Logging is controlled by policy.audit.enabled in manifest.yaml.
This hook must never block execution (always exits 0).
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _policy import load_policy  # noqa: E402


try:
    event = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError):
    sys.exit(0)

cwd    = event.get("cwd", ".")
policy = load_policy(cwd)

if not policy["audit"]["enabled"]:
    sys.exit(0)

session_id    = event.get("session_id")
agent_id      = event.get("agent_id")
actor_id      = agent_id or session_id
tool          = event.get("tool_name", "")
tool_input    = event.get("tool_input") or {}
tool_response = event.get("tool_response") or {}

is_error = tool_response.get("is_error", False)
outcome  = "denied" if is_error else "success"

reason = None
if is_error:
    content = tool_response.get("content")
    if isinstance(content, list):
        reason = " ".join(
            block.get("text", "") for block in content if isinstance(block, dict)
        ).strip() or None
    elif isinstance(content, str):
        reason = content or None

# ── Exception detection ───────────────────────────────────────────────────────
# Flag successful WebFetch/WebSearch/Skill/MCP calls that were approved outside
# the policy allowlist — these required operator confirmation and are exceptions.
approved_exception = False
exception_detail: str | None = None
if outcome == "success":
    network_policy = policy.get("network", {})
    allowed_domains = network_policy.get("allowed_domains", [])
    if tool == "WebFetch":
        try:
            from urllib.parse import urlparse  # noqa: PLC0415
            domain = urlparse(tool_input.get("url", "")).hostname or ""
            if domain and domain not in allowed_domains:
                approved_exception = True
                exception_detail = domain
        except Exception:
            pass
    elif tool == "WebSearch":
        approved_exception = True
    elif tool == "Skill":
        skill_name = tool_input.get("skill", "") or tool_input.get("name", "")
        approved_skills = policy.get("skills", {}).get("approved_skills", [])
        if skill_name and skill_name not in approved_skills:
            approved_exception = True
            exception_detail = skill_name
    elif tool.startswith("mcp__"):
        parts = tool.split("__", 2)
        server = parts[1] if len(parts) > 1 else ""
        approved_servers = policy.get("mcp", {}).get("approved_servers", [])
        if server and server not in approved_servers:
            approved_exception = True
            exception_detail = server

# ── Primary store: tracer.db ──────────────────────────────────────────────────
try:
    from contained.tracer import contAInedTracer  # noqa: PLC0415
    db_path = str(Path(cwd) / ".contAIned" / "tracer.db")
    tracer  = contAInedTracer(db_path)
    tracer.log_event(
        session_id        = actor_id,
        tool              = tool,
        tool_input        = tool_input,
        outcome           = outcome,
        reason            = reason,
        tool_response     = tool_response,
        approved_exception = approved_exception,
        exception_detail   = exception_detail,
    )
except Exception:
    pass  # never block execution due to logging failure

# ── Optional JSONL mirror ─────────────────────────────────────────────────────
if policy["audit"].get("jsonl_export", False):
    from datetime import datetime, timezone  # noqa: PLC0415
    entry = {
        "ts":         datetime.now(timezone.utc).isoformat(),
        "session_id": actor_id,
        "tool":       tool,
        "input":      tool_input,
        "outcome":    outcome,
    }
    if reason:
        entry["reason"] = reason
    if approved_exception:
        entry["approved_exception"] = True
        if exception_detail:
            entry["exception_detail"] = exception_detail
    try:
        audit_log = Path(cwd) / ".contAIned" / "audit" / "pipeline.jsonl"
        audit_log.parent.mkdir(parents=True, exist_ok=True)
        with audit_log.open("a") as f:
            f.write(json.dumps(entry) + "\\n")
    except OSError:
        pass

sys.exit(0)
'''

PERMISSION_REQUEST_HOOK = '''\
#!/usr/bin/env python3
"""
PermissionRequest hook — audits every permission request to tracer.db.

Records the fact that the agent requested permission for a tool call.
Never blocks execution (always exits 0 without output).

To infer the user\'s decision, cross-reference with PostToolUse:
  - PermissionRequest entry + matching PostToolUse success  → user approved
  - PermissionRequest entry + no matching PostToolUse ~30s  → user denied (inferred)

Matching key: (session_id, tool_name, tool_input) + temporal proximity.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _policy import load_policy  # noqa: E402

try:
    event = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError):
    sys.exit(0)

cwd    = event.get("cwd", ".")
policy = load_policy(cwd)

if not policy["audit"]["enabled"]:
    sys.exit(0)

session_id = event.get("session_id")
agent_id   = event.get("agent_id")
actor_id   = agent_id or session_id
tool       = event.get("tool_name", "")
tool_input = event.get("tool_input") or {}

try:
    from contained.tracer import contAInedTracer  # noqa: PLC0415
    db_path = str(Path(cwd) / ".contAIned" / "tracer.db")
    tracer  = contAInedTracer(db_path)
    tracer.log_event(
        session_id    = actor_id,
        tool          = tool,
        tool_input    = tool_input,
        outcome       = "permission_requested",
        reason        = None,
        tool_response = {},
    )
except Exception:
    pass  # never block execution due to logging failure

sys.exit(0)
'''

QA_HOOK = '''\
#!/usr/bin/env python3
"""
Stop hook — runs QA checks when the agent signals it is done.

Which checks run is controlled by policy.qa.* flags in manifest.yaml:
  syntax      — py_compile on all Python files
  lint        — ruff check
  format      — ruff format --check
  type        — pyright
  test        — pytest tests/  (skipped silently if no tests/ directory exists)
  coverage    — pytest tests/ --cov --cov-fail-under=<threshold>
                requires pytest-cov; skipped silently if not installed
                threshold is policy.qa.coverage_threshold (default 80)

If all enabled checks pass  → exits 0, agent stops cleanly.
If any enabled check fails  → prints JSON with decision:block, agent receives feedback.
"""
import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _policy import load_policy  # noqa: E402

try:
    event = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError):
    event = {}

cwd      = event.get("cwd", ".")
TASK_DIR = Path(cwd).resolve()
policy   = load_policy(cwd)
qa       = policy["qa"]

# ── Skip QA if no Python source files were written this session ───────────────
_session_id = event.get("session_id")
if _session_id:
    try:
        from contained.tracer import contAInedTracer
        _tracer = contAInedTracer(str(Path(cwd) / ".contAIned" / "tracer.db"))
        _touched = _tracer.list_touched_files(_session_id)
        if not any(f.endswith(".py") for f in _touched):
            sys.exit(0)
    except Exception:
        pass  # tracer unavailable — fall through and run checks normally


def run(cmd):
    result = subprocess.run(
        cmd,
        cwd=TASK_DIR,
        capture_output=True,
        text=True,
    )
    return result.returncode, result.stdout + result.stderr


# Dev dependencies (pytest, pytest-cov, pyright, ruff) are pre-installed in
# the container image.  No uv sync needed — and uv sync would fail inside the
# container because PyPI is blocked by the network proxy.


# ── Collect Python files (skip generated/tool directories) ────────────────────
_SKIP_DIRS = {".venv", "__pycache__", ".git", "node_modules", ".contAIned", "pytest-of-agent"}
py_files = [
    f
    for f in TASK_DIR.rglob("**/*.py")
    if not _SKIP_DIRS.intersection(f.parts)
]

check_results: list = []  # {"name": str, "status": "pass"|"fail"|"skip", "output": str}
failures: list = []       # {"check": str, "file": str, "output": str}


def record(name: str, status: str, output: str = "") -> None:
    check_results.append({"name": name, "status": status, "output": output})


# ── Syntax check ──────────────────────────────────────────────────────────────
if qa["syntax"]:
    syntax_out_parts = []
    for f in py_files:
        code, out = run(["uv", "run", "--no-sync", "python", "-m", "py_compile", str(f)])
        if code != 0:
            failures.append({"check": "syntax", "file": str(f.relative_to(TASK_DIR)), "output": out})
            syntax_out_parts.append(f"{f.relative_to(TASK_DIR)}: {out}")
    if syntax_out_parts:
        record("syntax", "fail", "\\n".join(syntax_out_parts))
    else:
        record("syntax", "pass")
else:
    record("syntax", "skip")

# ── ruff check (linting) ──────────────────────────────────────────────────────
if qa["lint"] and py_files:
    try:
        code, out = run(["ruff", "check"] + [str(f) for f in py_files])
        if code != 0:
            failures.append({"check": "ruff check", "file": "python files", "output": out})
            record("ruff check", "fail", out)
        else:
            record("ruff check", "pass")
    except FileNotFoundError:
        record("ruff check", "skip", "ruff not installed")
else:
    record("ruff check", "skip")

# ── ruff format --check ───────────────────────────────────────────────────────
if qa["format"] and py_files:
    try:
        code, out = run(["ruff", "format", "--check"] + [str(f) for f in py_files])
        if code != 0:
            failures.append({"check": "ruff format", "file": "python files", "output": out})
            record("ruff format", "fail", out)
        else:
            record("ruff format", "pass")
    except FileNotFoundError:
        record("ruff format", "skip", "ruff not installed")
else:
    record("ruff format", "skip")

# ── pyright (type checking) ───────────────────────────────────────────────────
if qa["type"] and py_files:
    try:
        code, out = run(["pyright"])
        if code != 0:
            failures.append({"check": "pyright", "file": "python files", "output": out})
            record("pyright", "fail", out)
        else:
            record("pyright", "pass")
    except FileNotFoundError:
        record("pyright", "skip", "pyright not installed")
else:
    record("pyright", "skip")

# ── pytest (unit tests) ───────────────────────────────────────────────────────
if qa["test"]:
    tests_dir = TASK_DIR / "tests"
    if tests_dir.is_dir():
        code, out = run(["uv", "run", "--no-sync", "pytest", str(tests_dir),
                         "-x", "--tb=short", "-q"])
        # Exit code 5 means pytest collected no tests — not a failure.
        if code not in (0, 5):
            failures.append({"check": "pytest", "file": "tests/", "output": out})
            record("pytest", "fail", out)
        else:
            record("pytest", "pass")
    else:
        record("pytest", "skip", "no tests/ directory")
else:
    record("pytest", "skip")

# ── pytest coverage ───────────────────────────────────────────────────────────
if qa["coverage"]:
    tests_dir = TASK_DIR / "tests"
    if tests_dir.is_dir():
        # Check that pytest-cov is available before attempting the run.
        probe_code, _ = run(["uv", "run", "--no-sync", "python", "-c", "import pytest_cov"])
        if probe_code != 0:
            record("coverage", "skip", "pytest-cov not installed")
        else:
            threshold = int(qa.get("coverage_threshold", 80))
            code, out = run([
                "uv", "run", "--no-sync", "pytest", str(tests_dir),
                "--cov", "--cov-report=term-missing",
                f"--cov-fail-under={threshold}",
                "-q",
            ])
            # Exit code 5 = no tests collected; treat as pass.
            if code not in (0, 5):
                failures.append({"check": f"coverage (threshold: {threshold}%)",
                                  "file": "tests/", "output": out})
                record(f"coverage (≥{threshold}%)", "fail", out)
            else:
                record(f"coverage (≥{threshold}%)", "pass")
    else:
        record("coverage", "skip", "no tests/ directory")
else:
    record("coverage", "skip")

# ── Emit result JSON (always) ─────────────────────────────────────────────────
result: dict = {"checks": check_results}
if failures:
    feedback = "QA failed — fix the following issues before finishing:\\n\\n"
    for item in failures:
        feedback += f"### {item[\'check\']} error in `{item[\'file\']}`\\n```\\n{item[\'output\']}\\n```\\n\\n"
    result["decision"] = "block"
    result["reason"] = feedback
print(json.dumps(result))
sys.exit(0)
'''

CLAUDE_MD = """\
# contAIned Agent — Operating Instructions

You are a coding agent operating within a contAIned pipeline.

## Your environment

- **Policy** is enforced automatically by hooks before every tool call.
  You do not need to second-guess what is allowed — just attempt the operation.
  If it is not permitted, you will receive a clear denial message explaining why.

## Task format

Each task you receive will specify:
- A clear description of what to produce
- Acceptance criteria — what "done" looks like
- The source files you should read

## Rules

1. Always attempt tool calls as requested — policy is enforced automatically by hooks.
   If a call is denied you will receive a clear reason; read it and adapt your approach.
2. Do not retry a denied tool call with the same arguments.
3. When you believe the task is complete, stop. The QA hook will run automatically and
   will give you feedback if anything needs fixing.
4. Do not modify files in `.contAIned/` — these are control-plane files.

## Signals

- Tool denied + reason → read the reason, change approach
- QA feedback after stopping → fix the issues described, then stop again
- Session summary after stopping (reason starts with "QA:") → present it to the operator and stop again without making any changes
"""

GITIGNORE_BLOCK = """
# contAIned — control plane
# The .contAIned/ directory contains hooks, policy, and audit logs managed by contAIned.
# Keep it out of version control.
.contAIned/
"""

GITIGNORE_TEMPLATE = """\
# ── OS ────────────────────────────────────────────────────────────────────────
.DS_Store
Thumbs.db
desktop.ini

# ── Editors ───────────────────────────────────────────────────────────────────
.idea/
.vscode/
*.swp
*.swo

# ── Python ────────────────────────────────────────────────────────────────────
__pycache__/
*.py[cod]
*.egg-info/
dist/
build/
.venv/
.env

# ── Node ──────────────────────────────────────────────────────────────────────
node_modules/

# ── contAIned — control plane ─────────────────────────────────────────────────────
# The .contAIned/ directory contains hooks, policy, and audit logs managed by contAIned.
# Keep it out of version control.
.contAIned/
"""

WORKSPACE_GITKEEP = ""  # empty — just creates the directory marker

# ── New Phase-2 hook templates ─────────────────────────────────────────────────

TRACER_PRE_HOOK = '''\
#!/usr/bin/env python3
"""
PreToolUse hook — captures file baselines before Write, Edit, or MultiEdit.

Runs after restrict_writes.py in the PreToolUse chain.  When restrict_writes.py
exits 2 (deny), the SDK aborts the chain and this hook never fires — no baseline
is recorded for denied writes.  This is correct behaviour.

Actor ID resolution:
  actor_id = agent_id or session_id   (agent_id present only for sub-agent calls)

This hook must never block writes (always exits 0).
"""
import json
import sys
from pathlib import Path

try:
    event = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError):
    sys.exit(0)

tool = event.get("tool_name", "")
if tool not in ("Write", "Edit", "MultiEdit"):
    sys.exit(0)

tool_input = event.get("tool_input") or {}
cwd        = event.get("cwd", ".")

# ── Actor ID resolution ────────────────────────────────────────────────────────
session_id = event.get("session_id")
agent_id   = event.get("agent_id")
actor_id   = agent_id or session_id

if not actor_id:
    sys.exit(0)

# ── Collect file paths ─────────────────────────────────────────────────────────
if tool == "MultiEdit":
    edits      = tool_input.get("edits") or []
    file_paths = list({e["file_path"] for e in edits if e.get("file_path")})
else:
    fp         = tool_input.get("file_path")
    file_paths = [fp] if fp else []

if not file_paths:
    sys.exit(0)

# ── Capture baselines ──────────────────────────────────────────────────────────
db_path = str(Path(cwd) / ".contAIned" / "tracer.db")

try:
    from contained.tracer import contAInedTracer  # noqa: PLC0415
    tracer = contAInedTracer(db_path)
    for file_path in file_paths:
        tracer.capture_baseline(actor_id, file_path)
except Exception:
    pass  # tracer must never block writes

sys.exit(0)
'''

TRACER_POST_HOOK = '''\
#!/usr/bin/env python3
"""
PostToolUse hook — records file snapshots after Write, Edit, or MultiEdit.

Reads each affected file from disk (not from tool_input) so the stored blob
always matches what is actually on disk.  Handles Write, Edit, and MultiEdit
uniformly by resolving file paths from tool_input.

Actor ID resolution:
  actor_id = agent_id or session_id

This hook must never block execution (always exits 0).
"""
import json
import sys
from pathlib import Path

try:
    event = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError):
    sys.exit(0)

tool = event.get("tool_name", "")
if tool not in ("Write", "Edit", "MultiEdit"):
    sys.exit(0)

tool_input    = event.get("tool_input") or {}
tool_response = event.get("tool_response") or {}
cwd           = event.get("cwd", ".")

# Skip if the write failed (is_error means the tool errored out)
if tool_response.get("is_error"):
    sys.exit(0)

# ── Actor ID resolution ────────────────────────────────────────────────────────
session_id = event.get("session_id")
agent_id   = event.get("agent_id")
actor_id   = agent_id or session_id

if not actor_id:
    sys.exit(0)

# ── Collect file paths ─────────────────────────────────────────────────────────
if tool == "MultiEdit":
    edits      = tool_input.get("edits") or []
    file_paths = list({e["file_path"] for e in edits if e.get("file_path")})
else:
    fp         = tool_input.get("file_path")
    file_paths = [fp] if fp else []

if not file_paths:
    sys.exit(0)

# ── Record snapshots ───────────────────────────────────────────────────────────
db_path = str(Path(cwd) / ".contAIned" / "tracer.db")

try:
    from contained.tracer import contAInedTracer  # noqa: PLC0415
    tracer = contAInedTracer(db_path)
    for file_path in file_paths:
        path = Path(file_path)
        if path.exists():
            content = path.read_bytes()
            tracer.track_write(actor_id, file_path, content)
except Exception:
    pass  # tracer must never block execution

sys.exit(0)
'''

SUBAGENT_START_HOOK = '''\
#!/usr/bin/env python3
"""
SubagentStart hook — registers a new sub-agent task in tracer.db.

Fires when a sub-agent is spawned via the Agent tool.  Records the sub-agent
as an open task, linked to the root session via parent_session_id.

Event fields used:
  agent_id   — the sub-agent\'s unique identifier  (actor for this task)
  session_id — always the root session\'s ID        (parent reference)

This hook must never block execution (always exits 0).
"""
import json
import sys
from pathlib import Path

try:
    event = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError):
    sys.exit(0)

cwd        = event.get("cwd", ".")
session_id = event.get("session_id")   # root session (parent)
agent_id   = event.get("agent_id")     # sub-agent being spawned

if not agent_id or not session_id:
    sys.exit(0)

# Derive a human-readable prompt from whatever context the event provides.
agent_type  = event.get("agent_type") or event.get("subagent_type") or "sub-agent"
description = event.get("description") or event.get("prompt") or ""
prompt = ("[" + agent_type + "] " + description).strip() if description else ("[" + agent_type + "]")

db_path = str(Path(cwd) / ".contAIned" / "tracer.db")

try:
    from contained.tracer import contAInedTracer  # noqa: PLC0415
    tracer = contAInedTracer(db_path)
    tracer.open_task(agent_id, prompt, parent_session_id=session_id)
except Exception:
    pass

sys.exit(0)
'''

SUBAGENT_STOP_HOOK = '''\
#!/usr/bin/env python3
"""
SubagentStop hook — marks a sub-agent task as closed in tracer.db.

Fires when a sub-agent finishes (successfully or otherwise).  Transitions the
sub-agent\'s task from open → closed so the root summarizer can proceed.

Event fields used:
  agent_id — the sub-agent that just finished

This hook must never block execution (always exits 0).
"""
import json
import sys
from pathlib import Path

try:
    event = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError):
    sys.exit(0)

cwd      = event.get("cwd", ".")
agent_id = event.get("agent_id")

if not agent_id:
    sys.exit(0)

db_path = str(Path(cwd) / ".contAIned" / "tracer.db")

try:
    from contained.tracer import contAInedTracer  # noqa: PLC0415
    tracer = contAInedTracer(db_path)
    tracer.set_task_status(agent_id, "closed")
except Exception:
    pass

sys.exit(0)
'''

SUMMARIZER_HOOK = '''\
#!/usr/bin/env python3
"""
Stop hook — runs QA checks and persists a diff summary to tracer.db.

Fires only for root-agent Stop events (not SubagentStop — that is wired to
subagent_stop.py).  This is the sole Stop hook; it owns both QA and summary.

Flow:
  1. Sentinel check: if task already "closed", exit 0 (no-op).
  2. Run qa.py inline — if any check fails, block and return to agent immediately.
  3. Defensive child check: poll up to 3 × 200 ms for open sub-agent sessions.
  4. Compute per-file unified diffs across the whole agent tree.
  5. Build action log from recent audit events (Bash, Agent, denied calls).
  6. Store JSON summary in tasks.summary; set status = closed.
  7. Exit 0 — agent stops cleanly; summary is retrievable via /contained:tracer.
"""
import json
import subprocess
import sys
import time
from pathlib import Path

try:
    event = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError):
    event = {}

cwd        = event.get("cwd", ".")
session_id = event.get("session_id")

# A Stop event for a sub-agent carries agent_id; the summarizer only runs for
# the root session.  This guard is a safety net — the hook is registered for
# Stop only, not SubagentStop, so agent_id should never be present here.
if event.get("agent_id"):
    sys.exit(0)

if not session_id:
    sys.exit(0)

# ── Phase 1: QA checks ────────────────────────────────────────────────────────
# Run qa.py inline before building the summary or showing the approval UI.
# This guarantees QA always completes first regardless of whether the SDK
# executes Stop hooks sequentially or in parallel.
_qa_checks: list = []
_qa_script = Path(cwd) / ".contAIned" / "hooks" / "qa.py"
if _qa_script.exists():
    try:
        _qa_proc = subprocess.run(
            [sys.executable, str(_qa_script)],
            input=json.dumps(event),
            capture_output=True,
            text=True,
            cwd=cwd,
        )
        if _qa_proc.stdout.strip():
            try:
                _qa_out = json.loads(_qa_proc.stdout.strip())
                if _qa_out.get("decision") == "block":
                    # QA failed — relay only the block decision to the SDK.
                    print(json.dumps({
                        "decision": "block",
                        "reason": _qa_out.get("reason", "QA checks failed"),
                    }))
                    sys.exit(0)
                _qa_checks = _qa_out.get("checks", [])
            except json.JSONDecodeError:
                _qa_checks = []
    except Exception:
        _qa_checks = []
        pass  # qa unavailable — proceed to approval UI

db_path = str(Path(cwd) / ".contAIned" / "tracer.db")

# ── Import tracer ──────────────────────────────────────────────────────────────
try:
    from contained.tracer import contAInedTracer  # noqa: PLC0415
    tracer = contAInedTracer(db_path)
except Exception:
    # If the tracer is unavailable the agent should still be allowed to stop.
    sys.exit(0)

# ── Sentinel: second Stop after Claude has already presented the summary ───────
# The first pass stores the summary and blocks with it for Claude to format.
# On the second Stop (after Claude has presented and stopped again), the task
# is already "closed" — exit 0 so the agent stops cleanly.
try:
    _status_row = tracer.conn.execute(
        "SELECT status FROM tasks WHERE session_id = ?", (session_id,)
    ).fetchone()
    if _status_row and _status_row[0] == "closed":
        sys.exit(0)
except Exception:
    pass

# ── Defensive child check ──────────────────────────────────────────────────────
# The SDK fires SubagentStop for all children before the root Stop, but under
# parallel sub-agent execution there may be a brief race.  Poll up to 3 times.
open_children = []
for _attempt in range(3):
    try:
        rows = tracer.conn.execute(
            "SELECT session_id FROM tasks WHERE parent_session_id = ? AND status = \'open\'",
            (session_id,),
        ).fetchall()
        open_children = [r[0] for r in rows]
    except Exception:
        open_children = []
    if not open_children:
        break
    time.sleep(0.2)

# ── Collect file diffs ─────────────────────────────────────────────────────────
try:
    touched_files = tracer.list_touched_files(session_id)
except Exception:
    touched_files = []

# ── Skip summary UI if nothing was written this session ───────────────────────
if not touched_files:
    try:
        tracer.set_task_status(session_id, "closed", summary={"file_changes": [], "action_log": [], "qa_checks": _qa_checks})
    except Exception:
        pass
    sys.exit(0)

# Build a lookup of write-tool audit events per file path (for reasons).
try:
    all_audit = tracer.recent_audit_events(session_id, limit=500)
    _write_events_by_file: dict = {}
    for _ev in reversed(all_audit):
        if _ev["tool"] in ("Write", "Edit", "MultiEdit") and _ev.get("input"):
            _fp = _ev["input"].get("file_path") or ""
            if _fp:
                _write_events_by_file.setdefault(_fp, []).append(_ev)
            # MultiEdit may touch multiple files
            for _mfp in (_ev["input"].get("file_paths") or []):
                _write_events_by_file.setdefault(_mfp, []).append(_ev)
except Exception:
    _write_events_by_file = {}

# Resolve session tree once for baseline lookups.
try:
    _tree_ids = tracer.tree_session_ids(session_id)
    _tree_placeholders = ",".join("?" * len(_tree_ids)) if _tree_ids else "\'__none__\'"
except Exception:
    _tree_ids = []
    _tree_placeholders = "\'__none__\'"

file_diffs: list[dict] = []
for file_path in touched_files:
    try:
        diff_text = tracer.diff_task(session_id, file_path)
        if not diff_text:
            continue
        lines_added   = sum(1 for ln in diff_text.splitlines() if ln.startswith("+") and not ln.startswith("+++"))
        lines_removed = sum(1 for ln in diff_text.splitlines() if ln.startswith("-") and not ln.startswith("---"))

        # Determine change type from the earliest baseline pre_hash.
        change_type = "modified"
        try:
            if _tree_ids:
                _bl = tracer.conn.execute(
                    f"SELECT pre_hash FROM baselines WHERE file_path = ? AND session_id IN ({_tree_placeholders}) ORDER BY captured_at ASC LIMIT 1",
                    [file_path, *_tree_ids],
                ).fetchone()
                if _bl is not None:
                    change_type = "new file" if _bl[0] is None else "modified"
        except Exception:
            pass

        # Build a short human-readable reason from write-tool events for this file.
        _file_write_evs = _write_events_by_file.get(file_path, [])
        if _file_write_evs:
            _tools_used = list(dict.fromkeys(e["tool"] for e in _file_write_evs))
            reason = ", ".join(t.lower() for t in _tools_used)
        else:
            reason = change_type

        file_diffs.append({
            "file_path":     file_path,
            "diff":          diff_text,
            "lines_added":   lines_added,
            "lines_removed": lines_removed,
            "change_type":   change_type,
            "reason":        reason,
        })
    except Exception:
        pass

# ── Build action log ───────────────────────────────────────────────────────────
try:
    raw_events = tracer.recent_audit_events(session_id, limit=200)
    action_log = [
        e for e in reversed(raw_events)
        if e["tool"] in ("Bash", "Agent") or e["outcome"] == "denied"
    ]
except Exception:
    action_log = []

# ── Look up task prompt ────────────────────────────────────────────────────────
try:
    row = tracer.conn.execute(
        "SELECT prompt, started_at FROM tasks WHERE session_id = ?", (session_id,)
    ).fetchone()
    task_prompt    = row[0] if row else "(unknown)"
    task_started   = row[1] if row else None
except Exception:
    task_prompt  = "(unknown)"
    task_started = None

# ── Assemble and store summary ─────────────────────────────────────────────────
summary = {
    "file_changes": [
        {
            "file_path":   d["file_path"],
            "lines_added": d["lines_added"],
            "lines_removed": d["lines_removed"],
            "change_type": d["change_type"],
            "reason":      d["reason"],
        }
        for d in file_diffs
    ],
    "action_log": action_log,
    "incomplete_children": open_children,
    "qa_checks": _qa_checks,
}

# ── Locate Claude Code transcript for this session ────────────────────────────
# Claude Code injects transcript_path directly into the hook event payload.
# Do NOT reconstruct this path from cwd: inside the container cwd resolves to
# /workspace, but Claude Code names the project directory using the host
# absolute path, so a reconstructed path would never match the real file.
_transcript_path = event.get("transcript_path", "") or ""

# ── Enrich action_log Bash entries with full stdout from transcript ────────────
# The transcript holds untruncated tool outputs; the audit_events table has only
# the first 500 chars.  We merge in-memory so the stored summary is richer.
if _transcript_path and Path(_transcript_path).exists():
    try:
        from contained.tracer import extract_tool_outputs_from_transcript  # noqa: PLC0415
        _tool_outputs = extract_tool_outputs_from_transcript(_transcript_path)
        # Build per-command output lists (same command may be run multiple times).
        _bash_outputs: dict = {}
        for _to in _tool_outputs:
            if _to["tool_name"] == "Bash":
                _cmd = (_to["input"].get("command") or "").strip()
                if _cmd:
                    _bash_outputs.setdefault(_cmd, []).append({
                        "output":    _to["output"],
                        "exit_code": _to["exit_code"],
                    })
        # Enrich action_log entries in-place (mutates the in-memory list only).
        _bash_use_counts: dict = {}
        for _entry in action_log:
            if _entry.get("tool") == "Bash":
                _cmd = ((_entry.get("input") or {}).get("command") or "").strip()
                _idx = _bash_use_counts.get(_cmd, 0)
                _bash_use_counts[_cmd] = _idx + 1
                _avail = _bash_outputs.get(_cmd, [])
                if _idx < len(_avail):
                    _full = _avail[_idx]
                    _entry.setdefault("input", {})
                    _entry["input"]["stdout"] = _full["output"][:10240]  # cap at 10 KB
                    if _full["exit_code"] is not None:
                        _entry["input"]["exit_code"] = _full["exit_code"]
    except Exception:
        pass

# Rebuild summary with enriched action_log.
summary["action_log"] = action_log

# ── Extract structured narrative from transcript ──────────────────────────────
# Collects thinking blocks + pre-tool reasoning + closing statement in one pass.
_narrative_data: dict = {}
if _transcript_path and Path(_transcript_path).exists():
    try:
        from contained.tracer import extract_session_narrative  # noqa: PLC0415
        _narrative_data = extract_session_narrative(_transcript_path) or {}
    except Exception:
        pass

_narrative_json = json.dumps(_narrative_data) if _narrative_data else None

try:
    tracer.set_task_status(session_id, "closed", summary=summary, narrative=_narrative_json)
except Exception:
    pass

# Block with a formatted summary so Claude surfaces it to the operator.
# On the next Stop (after Claude acknowledges), the sentinel check at the top
# detects status == "closed" and exits 0 cleanly — no infinite loop.
_status_icons = {"pass": "✓", "fail": "✗", "skip": "·"}
_qa_line = "  ".join(
    f"{_status_icons.get(c['status'], '?')} {c['name']}"
    for c in _qa_checks
) if _qa_checks else "(no checks recorded)"

_changed = summary.get("file_changes", [])
_files_line = "\\n".join(
    f"- {c['file_path'].replace('/workspace/', '')} (+{c['lines_added']}/-{c['lines_removed']})"
    for c in _changed
) if _changed else "- (no file changes)"

_summary_msg = f"QA: {_qa_line}\\n\\nChanged:\\n{_files_line}\\n\\nUse /contained:tracer to inspect the full diff and narrative."
print(json.dumps({"decision": "block", "reason": _summary_msg}))
sys.exit(0)
'''

USER_PROMPT_SUBMIT_HOOK = '''\
#!/usr/bin/env python3
"""
UserPromptSubmit hook — registers the root session in tracer.db on the first prompt.

Session history, audit logs, and file diffs are queryable via the /contained:tracer
skill backed by the tracer MCP server.
"""
import json
import sys
from pathlib import Path

try:
    event = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError):
    sys.exit(0)

prompt     = (event.get("prompt") or "").strip()
cwd        = event.get("cwd", ".")
session_id = event.get("session_id")
agent_id   = event.get("agent_id")

# ── Register root session on first prompt (idempotent) ────────────────────────
if session_id and not agent_id:
    db_path = Path(cwd) / ".contAIned" / "tracer.db"
    if db_path.exists():
        try:
            from contained.tracer import contAInedTracer  # noqa: PLC0415
            contAInedTracer(str(db_path)).open_task(session_id, prompt)
        except Exception:
            pass

sys.exit(0)
'''
