"""
Templates for files generated by `slash init`.
All generated content lives here so the init logic stays clean.
"""

SETTINGS_JSON = """\
{
  "permissions": {
    "allow": [
      "Read",
      "Glob",
      "Grep"
    ],
    "deny": [
      "Bash(rm*)",
      "Bash(sudo*)",
      "Bash(curl*)",
      "Bash(wget*)"
    ]
  },
  "hooks": {
    "PreToolUse": [
      {
        "matcher": "Write|Edit|MultiEdit",
        "hooks": [
          {
            "type": "command",
            "command": "python3 .slash/hooks/restrict_writes.py"
          }
        ]
      }
    ],
    "PostToolUse": [
      {
        "matcher": "*",
        "hooks": [
          {
            "type": "command",
            "command": "python3 .slash/hooks/audit.py"
          }
        ]
      }
    ],
    "Stop": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "python3 .slash/hooks/qa.py"
          }
        ]
      }
    ]
  }
}
"""

POLICY_MANIFEST = """\
# Slash policy manifest
# Controls what the agent can and cannot do.
#
# Evaluation order (first match wins):
#   PreToolUse hook (this file) → deny rules → allow rules → canUseTool callback
#
# Tiers:
#   allow  — hook exits 0, tool proceeds
#   deny   — hook exits 2, tool blocked, reason fed back to agent
#   (anything not listed here falls through to the canUseTool callback)

allow:
  # Read-only tools — always safe
  - tool: Read
  - tool: Glob
  - tool: Grep

  # Safe bash patterns
  - tool: Bash
    pattern: "^git (status|diff|log|show).*"
  - tool: Bash
    pattern: "^(npm test|pytest|python -m pytest).*"
  - tool: Bash
    pattern: "^(eslint|prettier --check|ruff check|mypy).*"
  - tool: Bash
    pattern: "^(cat|ls|find|echo|pwd|which|head|tail|wc).*"

deny:
  # Destructive shell commands
  - tool: Bash
    pattern: '^rm\s'
    reason: "Destructive file deletion is not permitted"
  - tool: Bash
    pattern: '.*rm\s+-rf.*'
    reason: "Recursive deletion is not permitted"
  - tool: Bash
    pattern: '^sudo\s'
    reason: "Privilege escalation is not permitted"

  # Network exfiltration
  - tool: Bash
    pattern: '^(curl|wget|nc|ncat)\s'
    reason: "Outbound network calls from Bash are not permitted"

  # Git mutations (escalate these via canUseTool instead)
  - tool: Bash
    pattern: "^git push.*"
    reason: "Git push requires explicit operator approval — use the canUseTool prompt"
  - tool: Bash
    pattern: "^git (commit|reset|rebase|merge).*"
    reason: "Git mutations require explicit operator approval"

  # Package publishing
  - tool: Bash
    pattern: "^(npm publish|pip upload|twine upload).*"
    reason: "Package publishing requires explicit operator approval"

# Agent model settings
agent:
  # Output verbosity during `slash run`:
  #   verbose  — full streaming output: thinking, text, every tool call and result (default)
  #   concise  — single updating status line showing the current tool call
  #   none     — silent during execution; only the final result is printed
  verbosity: verbose
  thinking:
    enabled: false
    budget_tokens: 1024
"""

RESTRICT_WRITES_HOOK = '''\
#!/usr/bin/env python3
"""
PreToolUse hook — restricts Write, Edit, MultiEdit to within the project root.

Reads tool call JSON from stdin.
Exits 0 to allow, 2 to deny (reason on stderr fed back to agent).
Denials are written to the audit log before blocking.
"""
import json
import sys
from datetime import datetime, timezone
from pathlib import Path


def log_denial(event: dict, target: str, reason: str) -> None:
    """Append a denial entry to the audit log. Never raises — audit must not block."""
    try:
        project_root = Path(event.get("cwd", "."))
        audit_log = project_root / ".slash" / "audit" / "pipeline.jsonl"
        audit_log.parent.mkdir(parents=True, exist_ok=True)
        entry = {
            "ts":         datetime.now(timezone.utc).isoformat(),
            "session_id": event.get("session_id"),
            "tool":       event.get("tool_name"),
            "input":      {"file_path": target},
            "outcome":    "denied",
            "reason":     reason,
        }
        with audit_log.open("a") as f:
            f.write(json.dumps(entry) + "\\n")
    except OSError:
        pass


try:
    event = json.load(sys.stdin)
except json.JSONDecodeError:
    sys.exit(0)  # malformed input — pass through, don't block

tool       = event.get("tool_name", "")
tool_input = event.get("tool_input", {})

if tool not in ("Write", "Edit", "MultiEdit"):
    sys.exit(0)

target = tool_input.get("file_path", "")
if not target:
    sys.exit(0)

# Allow writes anywhere within the project root; block everything outside.
project_root = Path(event.get("cwd", ".")).resolve()

try:
    Path(target).resolve().relative_to(project_root)
    sys.exit(0)
except ValueError:
    reason = f"write outside project root: {target}"
    log_denial(event, target, reason)
    print(
        f"Write denied: \\'{target}\\' is outside the project root.\\n"
        f"You may only write within: {project_root}",
        file=sys.stderr,
    )
    sys.exit(2)
'''

AUDIT_HOOK = '''\
#!/usr/bin/env python3
"""
PostToolUse hook — appends a structured audit entry for every tool execution.

This hook must never block execution (always exits 0).
"""
import json
import sys
from datetime import datetime, timezone
from pathlib import Path


try:
    event = json.load(sys.stdin)
except json.JSONDecodeError:
    sys.exit(0)

tool_response = event.get("tool_response") or {}
is_error = tool_response.get("is_error", False)
outcome = "denied" if is_error else "success"

entry = {
    "ts":         datetime.now(timezone.utc).isoformat(),
    "session_id": event.get("session_id"),
    "task_id":    event.get("cwd", "").split("/")[-1],  # last path segment as task hint
    "tool":       event.get("tool_name"),
    "input":      event.get("tool_input"),
    "outcome":    outcome,
}

if is_error:
    # Capture the error message for denied/failed tool calls
    content = tool_response.get("content")
    if isinstance(content, list):
        # SDK returns content as a list of blocks; extract text
        entry["reason"] = " ".join(
            block.get("text", "") for block in content if isinstance(block, dict)
        ).strip()
    elif isinstance(content, str):
        entry["reason"] = content

try:
    project_root = Path(event.get("cwd", "."))
    audit_log = project_root / ".slash" / "audit" / "pipeline.jsonl"
    audit_log.parent.mkdir(parents=True, exist_ok=True)
    with audit_log.open("a") as f:
        f.write(json.dumps(entry) + "\\n")
except OSError:
    pass  # never block execution due to logging failure

sys.exit(0)
'''

QA_HOOK = '''\
#!/usr/bin/env python3
"""
Stop hook — runs QA checks when the agent signals it is done.

If checks pass  → exits 0, agent stops cleanly.
If checks fail  → prints JSON with decision:block, agent receives feedback and continues.
"""
import json
import subprocess
import sys
from pathlib import Path

try:
    event = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError):
    event = {}

TASK_DIR = Path(event.get("cwd", ".")).resolve()


def run(cmd: list[str]) -> tuple[int, str]:
    result = subprocess.run(
        cmd,
        cwd=TASK_DIR,
        capture_output=True,
        text=True,
    )
    return result.returncode, result.stdout + result.stderr


def block(reason: str) -> None:
    """Tell the SDK to keep the agent running with this feedback."""
    print(json.dumps({"decision": "block", "reason": reason}))
    sys.exit(0)


# ── Syntax check all Python files the agent produced ──────────────────────────
py_files = list(TASK_DIR.glob("*.py"))

failures = []
for f in py_files:
    code, out = run(["python", "-m", "py_compile", f.name])
    if code != 0:
        failures.append({"check": "syntax", "file": f.name, "output": out})

if failures:
    feedback = "QA failed — fix the following issues before finishing:\\n\\n"
    for item in failures:
        feedback += f"### {item[\'check\']} error in `{item[\'file\']}`\\n```\\n{item[\'output\']}\\n```\\n\\n"
    block(feedback)

# ── ruff check (linting) ──────────────────────────────────────────────────────
if py_files:
    try:
        code, out = run(["ruff", "check"] + [f.name for f in py_files])
        if code != 0:
            failures.append({"check": "ruff check", "file": "python files", "output": out})
    except FileNotFoundError:
        print("ruff not installed — skipping ruff check", file=sys.stderr)

# ── ruff format --check ───────────────────────────────────────────────────────
if py_files:
    try:
        code, out = run(["ruff", "format", "--check"] + [f.name for f in py_files])
        if code != 0:
            failures.append({"check": "ruff format", "file": "python files", "output": out})
    except FileNotFoundError:
        print("ruff not installed — skipping ruff format --check", file=sys.stderr)

if failures:
    feedback = "QA failed — fix the following issues before finishing:\\n\\n"
    for item in failures:
        feedback += f"### {item[\'check\']} error in `{item[\'file\']}`\\n```\\n{item[\'output\']}\\n```\\n\\n"
    block(feedback)

# All checks passed
sys.exit(0)
'''

CLAUDE_MD = """\
# Slash Agent — Operating Instructions

You are a coding agent operating within a slash pipeline.

## Your environment

- **Policy** is enforced automatically by hooks before every tool call.
  You do not need to second-guess what is allowed — just attempt the operation.
  If it is not permitted, you will receive a clear denial message explaining why.

## Task format

Each task you receive will specify:
- A clear description of what to produce
- Acceptance criteria — what "done" looks like
- The source files you should read

## Rules

1. Always attempt tool calls as requested — policy is enforced automatically by hooks.
   If a call is denied you will receive a clear reason; read it and adapt your approach.
2. Do not retry a denied tool call with the same arguments.
3. When you believe the task is complete, stop. The QA hook will run automatically and
   will give you feedback if anything needs fixing.
4. Do not modify files in `.slash/` — these are control-plane files.

## Signals

- Tool denied + reason → read the reason, change approach
- QA feedback after stopping → fix the issues described, then stop again
"""

GITIGNORE_BLOCK = """\

# slash — control plane
# The .slash/ directory contains hooks, policy, and audit logs managed by slash.
# Keep it out of version control.
.slash/
"""

GITIGNORE_TEMPLATE = """\
# ── OS ────────────────────────────────────────────────────────────────────────
.DS_Store
Thumbs.db
desktop.ini

# ── Editors ───────────────────────────────────────────────────────────────────
.idea/
.vscode/
*.swp
*.swo

# ── Python ────────────────────────────────────────────────────────────────────
__pycache__/
*.py[cod]
*.egg-info/
dist/
build/
.venv/
.env

# ── Node ──────────────────────────────────────────────────────────────────────
node_modules/

# ── slash — control plane ─────────────────────────────────────────────────────
# The .slash/ directory contains hooks, policy, and audit logs managed by slash.
# Keep it out of version control.
.slash/
"""

WORKSPACE_GITKEEP = ""  # empty — just creates the directory marker
