"""
Templates for files generated by `slash init`.
All generated content lives here so the init logic stays clean.
"""

SETTINGS_JSON = """\
{{
  "permissions": {{
    "allow": [
      "Read({workspace}/**)",
      "Glob({workspace}/**)",
      "Grep({workspace}/**)"
    ]
  }},
  "hooks": {{
    "PreToolUse": [
      {{
        "matcher": "Read|Glob|Grep",
        "hooks": [
          {{
            "type": "command",
            "command": "python3 .slash/hooks/restrict_reads.py"
          }}
        ]
      }},
      {{
        "matcher": "Write|Edit|MultiEdit",
        "hooks": [
          {{
            "type": "command",
            "command": "python3 .slash/hooks/restrict_writes.py"
          }}
        ]
      }},
      {{
        "matcher": "Bash",
        "hooks": [
          {{
            "type": "command",
            "command": "python3 .slash/hooks/restrict_bash.py"
          }}
        ]
      }}
    ],
    "PostToolUse": [
      {{
        "matcher": "*",
        "hooks": [
          {{
            "type": "command",
            "command": "python3 .slash/hooks/audit.py"
          }}
        ]
      }}
    ],
    "Stop": [
      {{
        "hooks": [
          {{
            "type": "command",
            "command": "python3 .slash/hooks/qa.py"
          }}
        ]
      }}
    ]
  }}
}}
"""

POLICY_MANIFEST = """\
# Slash policy manifest
#
# Three sections:
#   1. runtime — controls whether slash runs locally or inside a Docker container.
#   2. policy  — enforcement settings read by the hook scripts.
#   3. agent   — model, verbosity, and thinking settings for slash run/repl.
#
# Action values accepted by policy settings:
#   block    — deny the operation outright; agent receives a clear reason
#   allow    — permit unconditionally
#   escalate — pass through to the SDK's canUseTool callback for operator approval
#
# Note: writes to .slash/ are always denied regardless of policy settings —
# control-plane protection is hardcoded and not configurable.

# ── Runtime ───────────────────────────────────────────────────────────────────
# Set by `slash init`. Do not edit by hand once slash init has written this.
#   mode: local   — hook-based policy only (default)
#   mode: docker  — kernel-enforced filesystem isolation + hook policy
runtime:
  mode: local
  docker:
    image: slash:latest
    memory: 2g
    cpus: 2
    network: slash-net
    agent_config_volume: slash-agent-config

policy:

  # ── Secret-file protection ──────────────────────────────────────────────────
  secrets:
    reads:         block    # Read / Glob / Grep on secret files
    writes:        block    # Write / Edit / MultiEdit on secret files
    bash_reads:    block    # cat / head / tail / etc. targeting secret files
    safe_variants: allow    # .env.example / .env.sample / .env.template exemption

  # ── Workspace boundary ───────────────────────────────────────────────────────
  # In Docker mode these checks are redundant (Docker enforces the boundary at
  # the kernel level), but they remain in the manifest for local-mode workspaces.
  workspace:
    reads:      escalate  # Read / Grep outside the project root → operator approval
    writes:     block     # Write / Edit / MultiEdit outside the project root
    bash_paths: block     # Bash absolute paths outside the project workspace

  # ── Bash command restrictions ────────────────────────────────────────────────
  bash:
    destructive:          block  # rm / rm -rf
    privilege_escalation: block  # sudo
    network_exfiltration: block  # curl / wget / nc / ncat
    git_mutations:        block  # git commit / reset / rebase / merge / push
    package_publish:      block  # npm publish / pip upload / twine upload

  # ── Audit logging ─────────────────────────────────────────────────────────────
  audit:
    enabled: true

  # ── QA gate (stop hook) ───────────────────────────────────────────────────────
  qa:
    syntax_check: true   # py_compile
    lint_check:   true   # ruff check
    format_check: true   # ruff format --check
    type_check:   true   # pyright

  # ── Rate limiting ─────────────────────────────────────────────────────────────
  rate_limiting:
    enabled: false       # limit expensive tool calls (reserved for future hooks)

# ── Agent model settings ──────────────────────────────────────────────────────
agent:
  # Model passed to the Claude Agent SDK. Leave blank to use the SDK default.
  model: claude-sonnet-4-6
  # Output verbosity during `slash run`:
  #   verbose  — full streaming output: thinking, text, every tool call and result (default)
  #   concise  — single updating status line showing the current tool call
  #   none     — silent during execution; only the final result is printed
  verbosity: verbose
  thinking:
    enabled: false
    budget_tokens: 1024
"""

POLICY_LOADER_HOOK = '''\
#!/usr/bin/env python3
"""Shared policy loader for slash hooks.

Reads the policy: and runtime: sections from .slash/manifest.yaml and merges
them with built-in defaults so that every key is always present.  If the
manifest cannot be read for any reason the defaults are returned unchanged —
hooks degrade gracefully to the original hardcoded behaviour.

Manifest location:
  Primary:   .slash/manifest.yaml          (new path, written by slash init)
  Fallback:  .slash/policy/manifest.yaml   (legacy path — compatibility shim)

Action values: "block" | "allow" | "escalate"
  block    — deny the operation; hook exits 2 with a reason on stderr
  allow    — permit unconditionally
  escalate — pass through (exit 0); the SDK\'s canUseTool callback decides
"""
from pathlib import Path

_DEFAULTS = {
    "secrets": {
        "reads":         "block",
        "writes":        "block",
        "bash_reads":    "block",
        "safe_variants": "allow",
    },
    "workspace": {
        "reads":      "escalate",
        "writes":     "block",
        "bash_paths": "block",
    },
    "bash": {
        "destructive":          "block",
        "privilege_escalation": "block",
        "network_exfiltration": "block",
        "git_mutations":        "block",
        "package_publish":      "block",
    },
    "audit": {
        "enabled": True,
    },
    "qa": {
        "syntax_check": True,
        "lint_check":   True,
        "format_check": True,
        "type_check":   True,
    },
    "rate_limiting": {
        "enabled": False,
    },
}


def _deep_merge(base, override):
    """Recursively merge *override* into *base*, returning a new dict."""
    result = dict(base)
    for key, val in override.items():
        if isinstance(val, dict) and isinstance(result.get(key), dict):
            result[key] = _deep_merge(result[key], val)
        else:
            result[key] = val
    return result


def _find_manifest(cwd="."):
    """Return the manifest Path, preferring the new location with fallback."""
    root = Path(cwd)
    new_path = root / ".slash" / "manifest.yaml"
    if new_path.exists():
        return new_path
    old_path = root / ".slash" / "policy" / "manifest.yaml"
    if old_path.exists():
        return old_path
    return new_path  # return new path even if missing — caller handles FileNotFoundError


def load_policy(cwd="."):
    """Return the fully-merged policy dict for the project rooted at *cwd*.

    Always succeeds: if the manifest is unreadable the built-in defaults
    are returned so hooks continue to enforce the current behaviour.
    """
    try:
        import yaml
        manifest_path = _find_manifest(cwd)
        with manifest_path.open() as fh:
            manifest = yaml.safe_load(fh) or {}
        return _deep_merge(_DEFAULTS, manifest.get("policy", {}))
    except Exception:
        return dict(_DEFAULTS)


def get_runtime_mode(cwd="."):
    """Return the runtime mode: \'local\' or \'docker\'.

    Returns \'local\' if the manifest is unreadable or the key is absent.
    """
    try:
        import yaml
        manifest_path = _find_manifest(cwd)
        with manifest_path.open() as fh:
            manifest = yaml.safe_load(fh) or {}
        return manifest.get("runtime", {}).get("mode", "local")
    except Exception:
        return "local"
'''

RESTRICT_WRITES_HOOK = '''\
#!/usr/bin/env python3
"""
PreToolUse hook — restricts Write, Edit, MultiEdit to within the project root.

Three checks in order:
  1. Workspace boundary        — driven by policy.workspace.writes
  2. Control-plane protection  — .slash/ writes are ALWAYS denied (not configurable)
  3. Secret file               — driven by policy.secrets.writes

Exits 0 to allow, 2 to deny (reason on stderr fed back to agent).
Denials are written to the audit log before blocking.
"""
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _policy import load_policy  # noqa: E402


SECRET_FILE_PATTERNS = [
    re.compile(r\'(^|[/\\\\])\\.env(\\.[^/\\\\]+)?$\', re.IGNORECASE),
    re.compile(r\'\\.(pem|key|p12|pfx|jks|keystore)$\', re.IGNORECASE),
    re.compile(r\'(^|[/\\\\])id_(rsa|dsa|ecdsa|ed25519)$\', re.IGNORECASE),
    re.compile(r\'(^|[/\\\\])(credentials|secrets|service_account)\\.(json|yaml|yml)$\', re.IGNORECASE),
    re.compile(r\'\\.(secret|secrets)$\', re.IGNORECASE),
]
SAFE_VARIANT_RE = re.compile(r\'\\.(example|sample|template)\', re.IGNORECASE)


def is_secret_file(path):
    """Return True if path refers to a secret file that should not be written."""
    if SAFE_VARIANT_RE.search(Path(path).name):
        return False
    return any(pattern.search(path) for pattern in SECRET_FILE_PATTERNS)


def log_denial(event, target, reason):
    """Append a denial entry to the audit log. Never raises — audit must not block."""
    try:
        project_root = Path(event.get("cwd", "."))
        audit_log = project_root / ".slash" / "audit" / "pipeline.jsonl"
        audit_log.parent.mkdir(parents=True, exist_ok=True)
        entry = {
            "ts":         datetime.now(timezone.utc).isoformat(),
            "session_id": event.get("session_id"),
            "tool":       event.get("tool_name"),
            "input":      {"file_path": target},
            "outcome":    "denied",
            "reason":     reason,
        }
        with audit_log.open("a") as f:
            f.write(json.dumps(entry) + "\\n")
    except OSError:
        pass


def enforce(action, event, target, msg):
    """Act on *action*: block exits 2; allow/escalate pass through."""
    if action == "block":
        log_denial(event, target, msg)
        print(msg, file=sys.stderr)
        sys.exit(2)


try:
    event = json.load(sys.stdin)
except json.JSONDecodeError:
    sys.exit(0)  # malformed input — pass through, don\'t block

tool       = event.get("tool_name", "")
tool_input = event.get("tool_input", {})

if tool not in ("Write", "Edit", "MultiEdit"):
    sys.exit(0)

target = tool_input.get("file_path", "")
if not target:
    sys.exit(0)

cwd          = event.get("cwd", ".")
policy       = load_policy(cwd)
project_root = Path(cwd).resolve()
slash_dir    = project_root / ".slash"
resolved     = Path(target).resolve()

# ── Check 1: outside project root ─────────────────────────────────────────────
try:
    resolved.relative_to(project_root)
except ValueError:
    enforce(
        policy["workspace"]["writes"], event, target,
        f"Write denied: \\'{target}\\' is outside the project root.\\n"
        f"You may only write within: {project_root}",
    )
    sys.exit(0)  # allow or escalate

# ── Check 2: inside .slash/ control-plane (always enforced, not configurable) ─
try:
    resolved.relative_to(slash_dir)
    log_denial(event, target, f"write into control-plane directory: {target}")
    print(
        f"Write denied: \\'{target}\\' is inside the .slash/ control-plane directory.\\n"
        "Hook and policy files are managed by slash and must not be edited directly.",
        file=sys.stderr,
    )
    sys.exit(2)
except ValueError:
    pass  # not inside .slash/ — continue

# ── Check 3: secret file ───────────────────────────────────────────────────────
if is_secret_file(str(resolved)):
    enforce(
        policy["secrets"]["writes"], event, target,
        f"Write denied: \\'{target}\\' looks like a secret file.\\n"
        "Writing to credentials, keys, and .env files is not permitted.",
    )

sys.exit(0)
'''

RESTRICT_READS_HOOK = '''\
#!/usr/bin/env python3
"""
PreToolUse hook — restricts Read, Glob, and Grep tool calls.

Checks are driven by the policy: section of .slash/policy/manifest.yaml.
  policy.secrets.reads         — action for secret-file read attempts
  policy.secrets.safe_variants — action for .env.example / template variants
  policy.workspace.reads       — action for reads outside the project root

Action values: block | allow | escalate
  block    — deny (exit 2, reason on stderr)
  allow    — permit unconditionally; skip the check
  escalate — pass through (exit 0); SDK\'s canUseTool callback decides

Exits 0 to allow, 2 to deny (reason on stderr fed back to agent).
Denials are written to the audit log before blocking.
"""
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _policy import get_runtime_mode, load_policy  # noqa: E402


SECRET_FILE_PATTERNS = [
    re.compile(r\'(^|[/\\\\])\\.env(\\.[^/\\\\]+)?$\', re.IGNORECASE),
    re.compile(r\'\\.(pem|key|p12|pfx|jks|keystore)$\', re.IGNORECASE),
    re.compile(r\'(^|[/\\\\])id_(rsa|dsa|ecdsa|ed25519)$\', re.IGNORECASE),
    re.compile(r\'(^|[/\\\\])(credentials|secrets|service_account)\\.(json|yaml|yml)$\', re.IGNORECASE),
    re.compile(r\'\\.(secret|secrets)$\', re.IGNORECASE),
]
SAFE_VARIANT_RE = re.compile(r\'\\.(example|sample|template)\', re.IGNORECASE)


def matches_secret_pattern(path):
    """Return True if path matches a secret file pattern (ignoring safe-variant exception)."""
    return any(pattern.search(path) for pattern in SECRET_FILE_PATTERNS)


def is_safe_variant(path):
    """Return True if path looks like a safe template/example variant."""
    return bool(SAFE_VARIANT_RE.search(Path(path).name))


def log_denial(event, target, reason):
    """Append a denial entry to the audit log. Never raises."""
    try:
        project_root = Path(event.get("cwd", "."))
        audit_log = project_root / ".slash" / "audit" / "pipeline.jsonl"
        audit_log.parent.mkdir(parents=True, exist_ok=True)
        entry = {
            "ts":         datetime.now(timezone.utc).isoformat(),
            "session_id": event.get("session_id"),
            "tool":       event.get("tool_name"),
            "input":      {"target": target},
            "outcome":    "denied",
            "reason":     reason,
        }
        with audit_log.open("a") as f:
            f.write(json.dumps(entry) + "\\n")
    except OSError:
        pass


def enforce(action, event, target, msg):
    """Act on *action*: block exits 2; allow/escalate pass through."""
    if action == "block":
        log_denial(event, target, msg)
        print(msg, file=sys.stderr)
        sys.exit(2)


try:
    event = json.load(sys.stdin)
except json.JSONDecodeError:
    sys.exit(0)

cwd          = event.get("cwd", ".")
policy       = load_policy(cwd)
runtime_mode = get_runtime_mode(cwd)
tool         = event.get("tool_name", "")
tool_input   = event.get("tool_input", {})

if tool == "Read":
    target = tool_input.get("file_path", "")
elif tool == "Grep":
    target = tool_input.get("path", "")
elif tool == "Glob":
    target = tool_input.get("pattern", "")
else:
    sys.exit(0)

if not target:
    sys.exit(0)

# ── Check 1: secret file (with safe-variant override) ────────────────────────
if matches_secret_pattern(target):
    if is_safe_variant(target):
        enforce(
            policy["secrets"]["safe_variants"], event, target,
            f"Access denied: \\'{target}\\' is a secret file "
            "(safe-variant exemption is disabled by policy).",
        )
    else:
        enforce(
            policy["secrets"]["reads"], event, target,
            "Access denied: secret files (credentials, keys, .env) may not be read. "
            "Only example/sample/template variants (e.g. .env.example) are permitted.",
        )
    sys.exit(0)  # allow or escalate: pass through

# ── Check 2: workspace boundary (Read and Grep only — Glob patterns are virtual) ──
# Skipped in Docker mode — the workspace boundary is enforced by the container
# runtime at the kernel level; path-string analysis is redundant.
if tool in ("Read", "Grep") and runtime_mode != "docker":
    workspace = Path(cwd).resolve()
    try:
        Path(target).resolve().relative_to(workspace)
    except ValueError:
        enforce(
            policy["workspace"]["reads"], event, target,
            f"Read outside workspace: \\'{target}\\' is not within {workspace}.",
        )

sys.exit(0)
'''

RESTRICT_BASH_HOOK = '''\
#!/usr/bin/env python3
"""
PreToolUse hook — restricts Bash tool calls.

All checks are driven by the policy: section of .slash/policy/manifest.yaml.

Checks applied in order:
  1. policy.secrets.bash_reads        — read cmds (cat, head, ...) on secret files
  2. policy.workspace.bash_paths      — absolute paths outside the project workspace
  3. policy.bash.destructive          — rm / rm -rf
  4. policy.bash.privilege_escalation — sudo
  5. policy.bash.network_exfiltration — curl / wget / nc / ncat
  6. policy.bash.git_mutations        — git commit / reset / rebase / merge / push
  7. policy.bash.package_publish      — npm publish / pip upload / twine upload

Action values: block | allow | escalate
  block    — deny (exit 2, reason on stderr)
  allow    — permit unconditionally; skip the check
  escalate — pass through (exit 0); SDK\'s canUseTool callback decides

Exits 0 to allow, 2 to deny (reason on stderr fed back to agent).
Denials are written to the audit log before blocking.
"""
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _policy import get_runtime_mode, load_policy  # noqa: E402


SECRET_FILE_PATTERNS = [
    re.compile(r\'(^|[/\\\\])\\.env(\\.[^/\\\\]+)?$\', re.IGNORECASE),
    re.compile(r\'\\.(pem|key|p12|pfx|jks|keystore)$\', re.IGNORECASE),
    re.compile(r\'(^|[/\\\\])id_(rsa|dsa|ecdsa|ed25519)$\', re.IGNORECASE),
    re.compile(r\'(^|[/\\\\])(credentials|secrets|service_account)\\.(json|yaml|yml)$\', re.IGNORECASE),
    re.compile(r\'\\.(secret|secrets)$\', re.IGNORECASE),
]
SAFE_VARIANT_RE = re.compile(r\'\\.(example|sample|template)\', re.IGNORECASE)
READ_CMD_RE     = re.compile(r\'^\\s*(cat|head|tail|less|more|bat|pg|view)\\s\', re.IGNORECASE)

# (policy key, compiled patterns, denial reason)
_BASH_RULES = [
    (
        "destructive",
        [re.compile(r\'^rm\\s\'), re.compile(r\'.*\\brm\\s+-rf\\b.*\')],
        "Destructive file deletion is not permitted.",
    ),
    (
        "privilege_escalation",
        [re.compile(r\'^sudo\\s\')],
        "Privilege escalation is not permitted.",
    ),
    (
        "network_exfiltration",
        [re.compile(r\'^(curl|wget|nc|ncat)\\s\')],
        "Outbound network calls from Bash are not permitted.",
    ),
    (
        "git_mutations",
        [re.compile(r\'^git\\s+(commit|reset|rebase|merge)\\b\'), re.compile(r\'^git\\s+push\\b\')],
        "Git mutations require explicit operator approval.",
    ),
    (
        "package_publish",
        [re.compile(r\'^(npm\\s+publish|pip\\s+upload|twine\\s+upload)\\b\')],
        "Package publishing requires explicit operator approval.",
    ),
]


def is_secret_file(path):
    """Return True if path refers to a secret file."""
    if SAFE_VARIANT_RE.search(Path(path).name):
        return False
    return any(pattern.search(path) for pattern in SECRET_FILE_PATTERNS)


def abs_path_tokens(command):
    """Extract tokens that resolve to absolute paths, including ~/... home-relative paths."""
    result = []
    for t in command.split():
        expanded = os.path.expanduser(t)
        if expanded.startswith("/") and len(expanded) > 1:
            result.append(expanded)
    return result


def log_denial(event, command, reason):
    try:
        project_root = Path(event.get("cwd", "."))
        audit_log = project_root / ".slash" / "audit" / "pipeline.jsonl"
        audit_log.parent.mkdir(parents=True, exist_ok=True)
        entry = {
            "ts":         datetime.now(timezone.utc).isoformat(),
            "session_id": event.get("session_id"),
            "tool":       event.get("tool_name"),
            "input":      {"command": command},
            "outcome":    "denied",
            "reason":     reason,
        }
        with audit_log.open("a") as f:
            f.write(json.dumps(entry) + "\\n")
    except OSError:
        pass


def enforce(action, event, command, msg):
    """Act on *action*: block exits 2; allow/escalate pass through."""
    if action == "block":
        log_denial(event, command, msg)
        print(msg, file=sys.stderr)
        sys.exit(2)


try:
    event = json.load(sys.stdin)
except json.JSONDecodeError:
    sys.exit(0)

command = event.get("tool_input", {}).get("command", "")
if not command:
    sys.exit(0)

cwd          = event.get("cwd", ".")
policy       = load_policy(cwd)
runtime_mode = get_runtime_mode(cwd)

# ── Check 1: secret file reads ────────────────────────────────────────────────
if READ_CMD_RE.match(command):
    for token in command.split():
        if is_secret_file(token):
            enforce(
                policy["secrets"]["bash_reads"], event, command,
                f"Bash denied: \\'{token}\\' looks like a secret file.\\n"
                "Secret files (credentials, keys, .env) may not be read.",
            )

# ── Check 2: absolute paths outside workspace ─────────────────────────────────
# Skipped in Docker mode — the workspace boundary is enforced by the container
# runtime at the kernel level; path-string analysis is redundant.
if runtime_mode != "docker":
    workspace = Path(cwd).resolve()
    for token in abs_path_tokens(command):
        try:
            Path(token).resolve().relative_to(workspace)
        except ValueError:
            enforce(
                policy["workspace"]["bash_paths"], event, command,
                f"Bash denied: \\'{token}\\' is outside the project workspace.\\n"
                f"Bash commands may only reference paths within: {workspace}",
            )

# ── Checks 3–7: bash command rules ────────────────────────────────────────────
for rule_key, patterns, reason in _BASH_RULES:
    action = policy["bash"][rule_key]
    if action == "allow":
        continue
    if any(pat.search(command) for pat in patterns):
        enforce(action, event, command, reason)

sys.exit(0)
'''

AUDIT_HOOK = '''\
#!/usr/bin/env python3
"""
PostToolUse hook — appends a structured audit entry for every tool execution.

Logging is controlled by policy.audit.enabled in manifest.yaml.
This hook must never block execution (always exits 0).
"""
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _policy import load_policy  # noqa: E402


try:
    event = json.load(sys.stdin)
except json.JSONDecodeError:
    sys.exit(0)

cwd    = event.get("cwd", ".")
policy = load_policy(cwd)

if not policy["audit"]["enabled"]:
    sys.exit(0)

tool_response = event.get("tool_response") or {}
is_error = tool_response.get("is_error", False)
outcome = "denied" if is_error else "success"

entry = {
    "ts":         datetime.now(timezone.utc).isoformat(),
    "session_id": event.get("session_id"),
    "task_id":    cwd.split("/")[-1],  # last path segment as task hint
    "tool":       event.get("tool_name"),
    "input":      event.get("tool_input"),
    "outcome":    outcome,
}

if is_error:
    # Capture the error message for denied/failed tool calls
    content = tool_response.get("content")
    if isinstance(content, list):
        # SDK returns content as a list of blocks; extract text
        entry["reason"] = " ".join(
            block.get("text", "") for block in content if isinstance(block, dict)
        ).strip()
    elif isinstance(content, str):
        entry["reason"] = content

try:
    project_root = Path(cwd)
    audit_log = project_root / ".slash" / "audit" / "pipeline.jsonl"
    audit_log.parent.mkdir(parents=True, exist_ok=True)
    with audit_log.open("a") as f:
        f.write(json.dumps(entry) + "\\n")
except OSError:
    pass  # never block execution due to logging failure

sys.exit(0)
'''

QA_HOOK = '''\
#!/usr/bin/env python3
"""
Stop hook — runs QA checks when the agent signals it is done.

Which checks run is controlled by policy.qa.* flags in manifest.yaml:
  syntax_check  — py_compile on all Python files
  lint_check    — ruff check
  format_check  — ruff format --check
  type_check    — pyright

If all enabled checks pass  → exits 0, agent stops cleanly.
If any enabled check fails  → prints JSON with decision:block, agent receives feedback.
"""
import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _policy import load_policy  # noqa: E402

try:
    event = json.load(sys.stdin)
except (json.JSONDecodeError, EOFError):
    event = {}

cwd      = event.get("cwd", ".")
TASK_DIR = Path(cwd).resolve()
policy   = load_policy(cwd)
qa       = policy["qa"]


def run(cmd):
    result = subprocess.run(
        cmd,
        cwd=TASK_DIR,
        capture_output=True,
        text=True,
    )
    return result.returncode, result.stdout + result.stderr


def block(reason):
    """Tell the SDK to keep the agent running with this feedback."""
    print(json.dumps({"decision": "block", "reason": reason}))
    sys.exit(0)


# ── Collect Python files (skip generated/tool directories) ────────────────────
_SKIP_DIRS = {".venv", "__pycache__", ".git", "node_modules", ".slash"}
py_files = [
    f
    for f in TASK_DIR.rglob("**/*.py")
    if not _SKIP_DIRS.intersection(f.parts)
]

failures = []

# ── Syntax check ──────────────────────────────────────────────────────────────
if qa["syntax_check"]:
    for f in py_files:
        code, out = run(["python", "-m", "py_compile", str(f)])
        if code != 0:
            failures.append({"check": "syntax", "file": str(f.relative_to(TASK_DIR)), "output": out})
    if failures:
        feedback = "QA failed — fix the following issues before finishing:\\n\\n"
        for item in failures:
            feedback += f"### {item[\'check\']} error in `{item[\'file\']}`\\n```\\n{item[\'output\']}\\n```\\n\\n"
        block(feedback)

# ── ruff check (linting) ──────────────────────────────────────────────────────
if qa["lint_check"] and py_files:
    try:
        code, out = run(["ruff", "check"] + [str(f) for f in py_files])
        if code != 0:
            failures.append({"check": "ruff check", "file": "python files", "output": out})
    except FileNotFoundError:
        print("ruff not installed — skipping ruff check", file=sys.stderr)

# ── ruff format --check ───────────────────────────────────────────────────────
if qa["format_check"] and py_files:
    try:
        code, out = run(["ruff", "format", "--check"] + [str(f) for f in py_files])
        if code != 0:
            failures.append({"check": "ruff format", "file": "python files", "output": out})
    except FileNotFoundError:
        print("ruff not installed — skipping ruff format --check", file=sys.stderr)

# ── pyright (type checking) ───────────────────────────────────────────────────
if qa["type_check"] and py_files:
    try:
        code, out = run(["pyright"])
        if code != 0:
            failures.append({"check": "pyright", "file": "python files", "output": out})
    except FileNotFoundError:
        print("pyright not installed — skipping type checks", file=sys.stderr)

if failures:
    feedback = "QA failed — fix the following issues before finishing:\\n\\n"
    for item in failures:
        feedback += f"### {item[\'check\']} error in `{item[\'file\']}`\\n```\\n{item[\'output\']}\\n```\\n\\n"
    block(feedback)

# All checks passed
sys.exit(0)
'''

CLAUDE_MD = """\
# Slash Agent — Operating Instructions

You are a coding agent operating within a slash pipeline.

## Your environment

- **Policy** is enforced automatically by hooks before every tool call.
  You do not need to second-guess what is allowed — just attempt the operation.
  If it is not permitted, you will receive a clear denial message explaining why.

## Task format

Each task you receive will specify:
- A clear description of what to produce
- Acceptance criteria — what "done" looks like
- The source files you should read

## Rules

1. Always attempt tool calls as requested — policy is enforced automatically by hooks.
   If a call is denied you will receive a clear reason; read it and adapt your approach.
2. Do not retry a denied tool call with the same arguments.
3. When you believe the task is complete, stop. The QA hook will run automatically and
   will give you feedback if anything needs fixing.
4. Do not modify files in `.slash/` — these are control-plane files.

## Signals

- Tool denied + reason → read the reason, change approach
- QA feedback after stopping → fix the issues described, then stop again
"""

GITIGNORE_BLOCK = """
# slash — control plane
# The .slash/ directory contains hooks, policy, and audit logs managed by slash.
# Keep it out of version control.
.slash/
"""

GITIGNORE_TEMPLATE = """\
# ── OS ────────────────────────────────────────────────────────────────────────
.DS_Store
Thumbs.db
desktop.ini

# ── Editors ───────────────────────────────────────────────────────────────────
.idea/
.vscode/
*.swp
*.swo

# ── Python ────────────────────────────────────────────────────────────────────
__pycache__/
*.py[cod]
*.egg-info/
dist/
build/
.venv/
.env

# ── Node ──────────────────────────────────────────────────────────────────────
node_modules/

# ── slash — control plane ─────────────────────────────────────────────────────
# The .slash/ directory contains hooks, policy, and audit logs managed by slash.
# Keep it out of version control.
.slash/
"""

WORKSPACE_GITKEEP = ""  # empty — just creates the directory marker
